import { useState, type ReactNode } from "react";
import { BarChart3, CalendarDays, Check, Clock3, Coffee, Download, Edit3, Eye, Fingerprint, IdCard, LogIn, LogOut, MapPin, QrCode, Search, UserRound, Users, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import employeeImage from "@/assets/saudi-employee.jpg";
import { attendanceReferenceRows } from "@/data/mockData";

const panel = "rounded-md border border-border bg-card shadow-sm";
const field = "h-9 rounded border border-input bg-card px-2 text-[10px] font-bold outline-none";
const attendanceTone = (status: string) => status === "حاضر" ? "bg-success-soft text-success" : status === "غائب" ? "bg-destructive/10 text-destructive" : status === "متأخر" ? "bg-warning-soft text-warning" : "bg-primary-soft text-primary";

function PageTitle({ title, subtitle, checkout = false }: { title: string; subtitle: string; checkout?: boolean }) {
  return <header className="mb-4"><nav className="text-[9px] text-muted-foreground">الرئيسية　›　الحضور والانصراف　›　{title}</nav><h1 className={`mt-1 flex items-center gap-2 text-xl font-black ${checkout ? "text-destructive" : "text-buy-navy"}`}>{checkout ? <LogOut size={22} /> : <Clock3 size={22} />}{title}</h1><p className="text-[9px] text-muted-foreground">{subtitle}</p></header>;
}

function MethodTabs() {
  const methods: [typeof Fingerprint, string][] = [[Fingerprint, "بصمة الوجه"], [QrCode, "الباركود"], [IdCard, "رقم الموظف"], [MapPin, "الموقع الجغرافي"]];
  return <div className="grid grid-cols-4 overflow-hidden rounded border border-border bg-search">{methods.map(([Icon, label], index) => <button type="button" key={label} className={`grid h-[82px] place-content-center gap-2 border-l border-border text-[10px] font-black last:border-0 ${index === 0 ? "border-b-2 border-b-primary bg-primary-soft text-primary" : "text-buy-navy"}`}><Icon className="mx-auto" size={24} />{label}</button>)}</div>;
}

function EmployeeSummary() {
  return <section className={`${panel} p-4`}><h2 className="mb-4 flex items-center gap-2 text-sm font-black"><UserRound size={16} /> بيانات الموظف</h2><div className="grid grid-cols-[72px_1fr] items-center gap-4"><img src={employeeImage} width={768} height={896} loading="lazy" alt="أحمد محمد عبدالله" className="size-[72px] rounded-full object-cover" /><div><b className="text-sm">أحمد محمد عبدالله</b><p className="mt-1 text-[9px] text-muted-foreground">استشاري جراحة عامة</p><p className="mt-2 text-[9px]">رقم الموظف: <b>100245</b></p></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-[9px]">{[[MapPin, "الموقع", "المبنى الرئيسي"], [IdCard, "الوظيفة", "استشاري جراحة عامة"], [BarChart3, "القسم", "الجراحة العامة"]].map(([Icon, label, value]) => { const I = Icon as typeof MapPin; return <div key={String(label)}><I className="mx-auto mb-2 text-primary" size={17} /><b>{String(label)}</b><p className="mt-1">{String(value)}</p></div>; })}</div></section>;
}

function FaceCapture({ checkout }: { checkout: boolean }) {
  return <section className={`${panel} p-4`}><MethodTabs /><div className="mt-5 grid gap-5 md:grid-cols-[minmax(0,1fr)_260px] [direction:ltr]"><div dir="rtl" className="relative"><div className="relative overflow-hidden rounded-md bg-muted"><img src={employeeImage} width={768} height={896} alt="صورة التحقق من الموظف" className="h-[330px] w-full object-cover object-top" /><span className="absolute inset-6 rounded-md border-2 border-primary-foreground/80" /><span className="absolute bottom-4 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-success px-4 py-2 text-[10px] font-bold text-primary-foreground"><Check className="inline" size={14} /> تم التعرف عليك بنجاح</span></div><h3 className="mt-3 text-center text-base font-black">أحمد محمد عبدالله</h3><p className="text-center text-[9px]">رقم الموظف: 100245　|　الإدارة: الجراحة العامة</p></div><div dir="rtl" className="flex flex-col justify-center text-center"><span className={`mx-auto grid size-20 place-items-center rounded-full ${checkout ? "bg-destructive/10 text-destructive" : "bg-primary-soft text-primary"}`}>{checkout ? <LogOut size={40} /> : <span className="text-4xl">👋</span>}</span><h2 className="mt-3 text-xl font-black">{checkout ? "تسجيل الانصراف" : "مرحباً بك"}</h2><p className="mt-1 text-[10px]">السبت 2026/04/06</p><div className="my-4 rounded-md bg-search py-4 text-5xl font-black text-buy-navy" dir="ltr">{checkout ? "16:32" : "08:01"} <small className="text-base font-normal">{checkout ? "مساءً" : "صباحاً"}</small></div><Button className={`h-12 text-base ${checkout ? "bg-destructive hover:bg-destructive/90" : "bg-success hover:bg-success/90"}`}>{checkout ? <LogOut /> : <LogIn />}{checkout ? "تسجيل الانصراف" : "تسجيل الحضور"}</Button><div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline"><MapPin /> تبديل الموقع</Button>{!checkout && <Button variant="outline" className="text-destructive"><LogOut /> تسجيل الانصراف</Button>}</div></div></div><div className="mt-5 flex items-center justify-between rounded bg-primary-soft p-4 text-[10px]"><div><span className="text-muted-foreground">الموقع الحالي</span><b className="block">المبنى الرئيسي - الرياض</b><span className="text-success"><Check className="inline" size={13} /> ضمن النطاق المسموح</span></div><MapPin className="text-primary" /></div></section>;
}

function Timeline({ checkout }: { checkout: boolean }) {
  const items = [[LogIn, "تسجيل الحضور", "08:01"], [Coffee, "خروج استراحة", checkout ? "10:30" : "--:--"], [Coffee, "عودة من الاستراحة", checkout ? "10:45" : "--:--"], [LogOut, "تسجيل الانصراف", checkout ? "16:32" : "--:--"]] as const;
  return <section className={`${panel} p-4`}><div className="flex justify-between"><h2 className="text-sm font-black">حالة الحضور اليوم</h2><span className="rounded bg-success-soft px-4 py-1 text-[9px] text-success">● حاضر</span></div><div className="mt-6 grid grid-cols-4 text-center text-[8px]">{items.map(([Icon, title, value], index) => <div key={title} className="relative before:absolute before:left-1/2 before:top-4 before:h-px before:w-full before:bg-border last:before:hidden"><span className={`relative z-10 mx-auto grid size-8 place-items-center rounded-full ${index === 0 ? "bg-success-soft text-success" : checkout && index === 3 ? "bg-destructive/10 text-destructive" : "bg-search text-muted-foreground"}`}><Icon size={15} /></span><b className="mt-2 block">{title}</b><span className="font-bold">{value}</span></div>)}</div></section>;
}

function MiniTable() {
  return <section className={`${panel} overflow-hidden`}><div className="flex items-center justify-between border-b border-border p-3"><h2 className="text-sm font-black">سجل الحضور والانصراف</h2><span className="text-[9px] text-primary">عرض الكل</span></div><div className="overflow-x-auto"><table className="w-full min-w-[470px] text-center text-[8px]"><thead className="bg-primary-soft"><tr>{["التاريخ", "اليوم", "وقت الحضور", "وقت الانصراف", "المدة", "الحالة"].map((label) => <th className="p-2" key={label}>{label}</th>)}</tr></thead><tbody>{attendanceReferenceRows.slice(0, 5).map((row) => <tr className="border-t border-border" key={row.id}><td className="p-2">{row.date}</td><td>{row.day}</td><td>{row.inTime}</td><td>{row.outTime}</td><td>{row.hours}</td><td><span className={`rounded px-2 py-1 ${attendanceTone(row.status)}`}>{row.status}</span></td></tr>)}</tbody></table></div></section>;
}

function DayColumn({ checkout }: { checkout: boolean }) {
  return <div className="space-y-3"><EmployeeSummary /><Timeline checkout={checkout} />{checkout ? <><div className="grid grid-cols-2 gap-3"><section className={`${panel} p-4 text-center`}><CalendarDays className="mx-auto text-primary" /><b className="mt-2 block">الدوام الرسمي</b><p className="mt-2 text-success">من 08:00 صباحاً<br />إلى 16:00 مساءً</p></section><section className={`${panel} p-4 text-center`}><Clock3 className="mx-auto text-primary" /><b className="mt-2 block">إجمالي مدة العمل</b><strong className="mt-2 block text-2xl">8 س 31 د</strong><div className="mt-3 h-2 rounded bg-success" /></section></div><section className={`${panel} p-4 text-[9px]`}><b>ملاحظات الانصراف (اختياري)</b><textarea className="mt-2 h-20 w-full rounded border border-input p-2" placeholder="إضافة ملاحظات ..." /></section></> : <MiniTable />}</div>;
}

export function AttendancePunchPage({ mode }: { mode: "check-in" | "check-out" }) {
  const checkout = mode === "check-out";
  return <AppShell><main dir="rtl" className="min-w-0 p-3 sm:p-4"><PageTitle title={checkout ? "تسجيل الانصراف" : "تسجيل الحضور"} subtitle={checkout ? "تسجيل نهاية الدوام وحفظ بيانات الانصراف" : "سجل حضورك وانصرافك بسهولة وسرعة"} checkout={checkout} /><div className="grid gap-3 xl:grid-cols-[1.08fr_.92fr] [direction:ltr]"><div dir="rtl"><FaceCapture checkout={checkout} /></div><div dir="rtl"><DayColumn checkout={checkout} /></div></div><p className="mt-2 text-[8px] text-muted-foreground">عرض تجريبي — لا يتم تسجيل بصمة أو موقع أو دوام فعلي.</p></main></AppShell>;
}

function MetricCards({ manage = false }: { manage?: boolean }) {
  const items: [typeof Users, string, string, string][] = manage ? [[Users, "إجمالي الموظفين", "157", "text-primary"], [UserRound, "حاضر الآن", "28", "text-success"], [X, "غائب", "12", "text-destructive"], [Clock3, "متأخر", "8", "text-warning"]] : [[Users, "إجمالي الموظفين", "157", "text-primary"], [CalendarDays, "حاضرين اليوم", "138", "text-primary"], [Clock3, "متأخرين اليوم", "7", "text-warning"], [X, "غائبين اليوم", "12", "text-destructive"]];
  return <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{items.map(([Icon, label, value, color]) => <section className={`${panel} flex h-20 items-center justify-between p-3`} key={label}><div><b className={`text-xl ${color}`}>{value}</b><p className="text-[9px] font-black">{label}</p>{!manage && <span className="text-[7px] text-primary">عرض التفاصيل</span>}</div><span className={`grid size-11 place-items-center rounded-full bg-primary-soft ${color}`}><Icon /></span></section>)}</div>;
}

function WeeklyChart() {
  const heights = ["h-[58%]", "h-[66%]", "h-[64%]", "h-[62%]", "h-[76%]", "h-[80%]", "h-[76%]"];
  return <section className={`${panel} p-3`}><h2 className="text-sm font-black">الحضور والانصراف خلال الأسبوع</h2><div className="mt-2 flex gap-4 text-[8px]"><span>■ حضور</span><span className="text-primary">■ غياب</span></div><div className="mt-3 flex h-36 items-end justify-around border-b border-border">{heights.map((height, index) => <div className="flex h-full items-end gap-1" key={height + index}><span className={`w-5 bg-primary ${height}`} /><span className="h-[10%] w-3 bg-primary-soft" /></div>)}</div><div className="mt-1 grid grid-cols-7 text-center text-[7px]">{["السبت", "الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"].map((day) => <span key={day}>{day}</span>)}</div></section>;
}

function DonutCard() {
  return <section className={`${panel} p-3`}><h2 className="text-sm font-black">إحصائية الحضور اليوم</h2><div className="mt-3 grid grid-cols-[130px_1fr] items-center"><div className="relative size-32 rounded-full border-[22px] border-success"><span className="absolute inset-0 grid place-content-center text-center"><b className="text-xl">157</b><small>موظف</small></span><i className="absolute left-0 top-0 size-6 rounded-full bg-warning" /><i className="absolute bottom-0 left-2 size-5 rounded-full bg-destructive" /></div><dl className="space-y-2 text-[9px]">{[["حاضر", "138", "text-success"], ["متأخر", "7", "text-warning"], ["غائب", "12", "text-destructive"], ["في إجازة", "0", "text-primary"]].map(([label, value, color]) => <div className="flex justify-between" key={label}><dt className={color}>● {label}</dt><dd className="font-black">{value}</dd></div>)}</dl></div></section>;
}

function ClockCard() {
  return <section className={`${panel} p-4 text-center`}><b className="text-2xl" dir="ltr">08:32:15</b><p className="text-[9px]">السبت 2026/04/06</p><span className="my-3 inline-block rounded bg-success-soft px-4 py-1 text-[9px] text-success">● داخل الدوام</span><div className="grid grid-cols-2 gap-2"><Button className="bg-success"><LogIn />تسجيل الحضور</Button><Button variant="destructive"><LogOut />تسجيل الانصراف</Button></div><p className="mt-3 text-[8px]"><MapPin className="inline" size={13} /> موقع العمل: الرياض - المبنى الرئيسي</p></section>;
}

function FilterBar() {
  return <div className="grid gap-2 p-2 sm:grid-cols-[minmax(170px,1fr)_repeat(4,130px)_80px]"><label className="relative"><Search className="absolute right-2 top-2.5 text-primary" size={14} /><input className={`${field} w-full pr-7`} placeholder="البحث عن موظف بالاسم أو رقم الهوية..." /></label>{["جميع الحالات", "جميع الأقسام", "2026/04/06", "2026/04/06"].map((value, index) => <select className={field} key={`${value}-${index}`}><option>{value}</option></select>)}<Button size="sm">بحث</Button></div>;
}

function RecordsTable({ editable = false, onSelect }: { editable?: boolean; onSelect?: (index: number) => void }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-center text-[8px]"><thead className="bg-primary-soft"><tr>{["م", "الموظف", "رقم الموظف", "القسم", "التاريخ", "وقت الحضور", "وقت الانصراف", "ساعات العمل", "الحالة", "الموقع", "الإجراءات"].map((label) => <th className="p-2" key={label}>{label}</th>)}</tr></thead><tbody>{attendanceReferenceRows.slice(0, 10).map((row, index) => <tr onClick={() => onSelect?.(index)} className="cursor-pointer border-t border-border hover:bg-primary-soft/40" key={row.id}><td>{index + 1}</td><td><span className="inline-flex items-center gap-1 font-black"><img src={employeeImage} width={768} height={896} loading="lazy" className="size-6 rounded-full object-cover" alt="" />{row.name}</span></td><td>{row.id}</td><td>{row.department}</td><td>{row.date}</td><td>{row.inTime}</td><td>{row.outTime}</td><td>{row.hours}</td><td><span className={`rounded px-2 py-1 ${attendanceTone(row.status)}`}>{row.status}</span></td><td>المبنى الرئيسي</td><td><Button variant="ghost" size="icon" className="size-6"><Eye /></Button>{editable && <Button variant="ghost" size="icon" className="size-6 text-primary"><Edit3 /></Button>}</td></tr>)}</tbody></table></div>;
}

function LocationAside() {
  return <aside className="space-y-3"><section className={`${panel} p-3`}><h2 className="font-black">تحديد الموقع الجغرافي</h2><div className="mt-3 grid h-36 place-content-center rounded bg-search text-center"><MapPin className="mx-auto text-primary" size={36} /><b>المركز الرئيسي</b><span className="text-[8px]">الرياض - حي الملعا</span></div></section><section className={`${panel} p-3`}><h2 className="font-black">سجل حركة الموظف</h2><div className="mt-3 space-y-3 text-[8px]">{[["08:01", "تسجيل الحضور", "text-success"], ["12:30", "استراحة", "text-warning"], ["13:00", "العودة من الاستراحة", "text-success"], ["17:05", "تسجيل الانصراف", "text-primary"]].map(([time, label, color]) => <div className="grid grid-cols-[36px_12px_1fr] items-center" key={time}><b>{time}</b><span className={color}>●</span><span>{label}</span></div>)}</div></section></aside>;
}

export function AttendanceDashboardPage() {
  return <AppShell><main dir="rtl" className="min-w-0 p-3 sm:p-4"><PageTitle title="الحضور والانصراف" subtitle="متابعة وإدارة حضور وانصراف الموظفين" /><MetricCards /><div className="my-3 grid gap-3 lg:grid-cols-[1.15fr_.9fr_.8fr]"><WeeklyChart /><DonutCard /><ClockCard /></div><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_190px] [direction:ltr]"><section dir="rtl" className={`${panel} min-w-0 overflow-hidden`}><FilterBar /><div className="flex justify-between border-t border-border p-2"><h2 className="text-sm font-black">سجل الموظفين</h2><Button variant="outline" size="sm"><Download />تصدير التقرير</Button></div><RecordsTable /><div className="p-2 text-[8px]">إظهار 1 إلى 10 من أصل 157 موظف</div></section><div dir="rtl"><LocationAside /></div></div></main></AppShell>;
}

function EditPanel({ index }: { index: number }) {
  const row = attendanceReferenceRows[index] ?? attendanceReferenceRows[0];
  return <aside dir="rtl" className={`${panel} overflow-hidden`}><h2 className="flex items-center justify-between border-b border-border p-3 font-black">تعديل سجل الحضور والانصراف <X size={16} /></h2><div className="space-y-3 p-3 text-[9px]"><div className="flex items-center gap-2"><img src={employeeImage} width={768} height={896} loading="lazy" className="size-12 rounded-full object-cover" alt={row.name} /><div><b>{row.name}</b><p>{row.department} · رقم الموظف: {row.id}</p></div></div>{[["التاريخ", row.date], ["وقت الحضور", row.inTime], ["وقت الانصراف", row.outTime], ["ساعات العمل (محسوبة تلقائياً)", row.hours], ["الحالة", row.status], ["الموقع", "المبنى الرئيسي"]].map(([label, value]) => <label className="block font-bold" key={label}>{label}<input className={`${field} mt-1 w-full`} value={value} readOnly /></label>)}<label className="block font-bold">ملاحظات التعديل<textarea className="mt-1 h-20 w-full rounded border border-input p-2" defaultValue="تعديل بناءً على طلب الموظف" /></label><div className="grid grid-cols-2 gap-2"><Button>حفظ التعديل</Button><Button variant="outline">إلغاء</Button></div><p className="text-muted-foreground">تعديل تجريبي محلي وغير محفوظ.</p></div></aside>;
}

export function AttendanceManagePage() {
  const [selected, setSelected] = useState(0);
  return <AppShell><main dir="rtl" className="min-w-0 p-3 sm:p-4"><PageTitle title="إدارة الحضور والانصراف" subtitle="مراجعة وتعديل سجلات الحضور والانصراف للموظفين" /><MetricCards manage /><div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1fr)_285px] [direction:ltr]"><section dir="rtl" className={`${panel} min-w-0 overflow-hidden`}><FilterBar /><div className="flex justify-between p-2"><h2 className="font-black">سجلات الحضور والانصراف</h2><Button variant="outline" size="sm"><Download />تصدير البيانات</Button></div><RecordsTable editable onSelect={setSelected} /><div className="p-3 text-[8px]">إظهار 1 إلى 10 من أصل 157 سجل</div></section><EditPanel index={selected} /></div></main></AppShell>;
}