import { useMemo, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { BriefcaseBusiness, CalendarDays, CheckCircle2, CloudUpload, Download, Eye, FileBadge, FileCheck2, FileText, Folder, GraduationCap, IdCard, MoreVertical, Plus, Search, ShieldCheck, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { employeeDocumentCategories,employeeDocumentRows } from "@/data/mockData";
import employee from "@/assets/candidate-ahmed.jpg";

const panel="rounded-md border border-border bg-card shadow-sm";
const categoryIcon=(type:string)=>type==="folder"?Folder:type==="education"?GraduationCap:type==="insurance"?ShieldCheck:type==="id"?IdCard:FileBadge;
const statusClass=(s:string)=>s==="ساري"?"bg-success-soft text-success":s==="قرب الانتهاء"?"bg-warning-soft text-warning":"bg-primary-soft text-primary";
export function EmployeeDocuments(){const [q,setQ]=useState("");const [cat,setCat]=useState("جميع المستندات");const [rows,setRows]=useState(employeeDocumentRows.map(r=>[...r] as string[]));const file=useRef<HTMLInputElement>(null);const visible=useMemo(()=>rows.filter(r=>{const name=r[0]??"",type=r[1]??"";return (cat==="جميع المستندات"||type.includes(cat.replace("المؤهلات العلمية","مؤهل علمي")))&&(!q||name.includes(q)||type.includes(q))}),[rows,q,cat]);const add=(files:FileList|null)=>{const f=files?.[0];if(f)setRows(p=>[[f.name.replace(/\.[^.]+$/, ""),"نموذج آخر","2026/10/09","-","معتمد",`${Math.max(.1,f.size/1024/1024).toFixed(1)} MB`],...p])};return <AppShell><main dir="rtl" className="min-w-0 p-3 sm:p-4"><div className="mx-auto max-w-[1450px]">
 <div className="mb-3 text-[10px] text-muted-foreground">الرئيسية　‹　الموظفين　‹　ملف الموظف</div><h1 className="mb-3 flex items-center gap-2 text-xl font-black text-buy-navy"><Folder className="text-primary"/>ملف الموظف</h1>
 <section className={`${panel} flex flex-col gap-4 p-4 lg:flex-row lg:items-center`}><img src={employee} alt="أحمد محمد عبدالله" className="size-24 rounded-full object-cover"/><div className="min-w-52"><h2 className="text-xl font-black">أحمد محمد عبدالله</h2><p className="text-sm">استشاري جراحة عامة</p><p className="mt-2 text-[10px]"><b>رقم الموظف</b>　100245</p></div><div className="grid flex-1 grid-cols-2 gap-3 border-r border-border pr-4 text-xs sm:grid-cols-3 lg:grid-cols-5">{[[IdCard,"رقم الهوية","1045678901"],[CheckCircle2,"الجنسية","سعودي"],[BriefcaseBusiness,"القسم","قسم الجراحة"],[BriefcaseBusiness,"نوع التوظيف","متعاقد جزئي"],[CalendarDays,"حالة الموظف","نشط"]].map(([I,k,v])=>{const Icon=I as typeof IdCard;return <div key={String(k)} className="flex items-start gap-3 px-3"><Icon size={24} className="mt-1 shrink-0 text-buy-navy"/><div><span className="block text-xs text-muted-foreground">{String(k)}</span><b className="mt-1 block text-sm">{String(v)}</b></div></div>})}</div></section>
 <nav className="mt-2 flex gap-1 overflow-x-auto border-b border-border bg-card px-2">{["البيانات الأساسية","البيانات الوظيفية","الرواتب والبدلات","العقود","الإجازات","التقييمات","الجزاءات","المستندات","السجل الوظيفي"].map(x=><Link key={x} to="/employees/profile" className={`shrink-0 px-4 py-3 text-[10px] font-bold ${x==="المستندات"?"border-b-2 border-primary text-primary":""}`}>{x}</Link>)}</nav>
 <section className="mt-3 grid gap-3 lg:grid-cols-[.72fr_1.3fr] [direction:ltr]"><div dir="rtl" className={`${panel} p-4`}><CloudUpload className="float-left size-12 rounded-full bg-muted p-2 text-muted-foreground"/><p className="text-sm text-muted-foreground">المساحة المستخدمة</p><b className="mt-1 block text-base">120 ميجابايت من 1 جيجابايت</b><div className="mt-3 h-2 rounded bg-muted"><i className="block h-full w-[12%] rounded bg-primary"/></div><b className="mt-2 block text-left text-[10px]">12%</b></div><button dir="rtl" onClick={()=>file.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();add(e.dataTransfer.files)}} className="grid min-h-32 place-content-center rounded-md border-2 border-dashed border-primary/40 bg-primary-soft/20 text-center"><CloudUpload className="mx-auto text-primary" size={32}/><b className="mt-2">اسحب الملفات هنا</b><span className="text-[9px] text-muted-foreground">أو اضغط لاختيار الملفات</span><span className="mx-auto mt-2 rounded bg-buy-navy px-6 py-1.5 text-[10px] text-primary-foreground">اختيار ملفات</span></button><input ref={file} type="file" hidden onChange={e=>add(e.target.files)}/></section>
 <section className="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-5 lg:grid-cols-9">{employeeDocumentCategories.map(([name,count,type])=>{const Icon=categoryIcon(type);return <button key={name} onClick={()=>setCat(name)} className={`${panel} relative grid min-h-24 place-content-center p-2 text-center ${cat===name?"border-primary bg-primary-soft":""}`}><span className="absolute right-2 top-2 grid size-6 place-items-center rounded-full bg-primary-soft text-xs font-bold">{count}</span><Icon size={30} className="mx-auto text-buy-navy"/><b className="mt-2 text-xs">{name}</b></button>})}</section>
 <div className="mt-4 flex flex-wrap items-center gap-3"><h2 className="ml-auto text-lg font-black">قائمة المستندات</h2><label className="relative min-w-48 sm:w-80"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} className="h-10 w-full rounded-md border border-border bg-muted/40 pl-9 pr-3 text-xs" placeholder="البحث في المستندات ..."/></label><select className="h-10 w-40 rounded-md border border-border bg-card px-3 text-xs"><option>جميع الأنواع</option></select><Button className="h-10 bg-buy-navy px-6" onClick={()=>file.current?.click()}><Plus/>إضافة مستند</Button></div>
 <section className={`${panel} mt-2 overflow-x-auto`}><table className="w-full min-w-[820px] text-center text-xs [&_td]:p-3 [&_th]:p-2.5"><thead className="bg-primary-soft"><tr><th className="text-right">اسم المستند</th><th>نوع المستند</th><th>تاريخ الإصدار</th><th>تاريخ الانتهاء</th><th>الحالة</th><th>الحجم</th><th>الخيارات</th></tr></thead><tbody>{visible.map((r,ri)=><tr key={`${r[0]}-${ri}`} className="border-t border-border"><td className="font-black text-right"><FileText className="ml-2 inline size-4 text-buy-navy"/>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><span className={`rounded px-3 py-1 font-bold ${statusClass(r[4]??"")}`}>{r[4]}</span></td><td dir="ltr">{r[5]}</td><td><span className="inline-flex gap-2"><Eye className="size-4"/><Download className="size-4"/><Trash2 className="size-4 text-destructive"/><MoreVertical className="size-4"/></span></td></tr>)}</tbody></table></section><p className="mt-2 text-[8px] text-muted-foreground">عرض توضيحي تجريبي — الملفات المضافة لا تُحفظ بعد تحديث الصفحة.</p>
 </div></main></AppShell>}