import { useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { BriefcaseBusiness, Check, ChevronLeft, ClipboardList, FileText, Pencil, Save, Send, Upload } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { onboardingDocuments, onboardingStages, onboardingTasks } from "@/data/mockData";
import employeePhoto from "@/assets/candidate-ahmed.jpg";

const panel = "min-w-0 rounded-md border border-border bg-card p-3 shadow-sm";
const inputClass = "mt-1 h-8 w-full min-w-0 rounded border border-input bg-card px-2 text-[11px] text-buy-navy outline-none focus:border-primary focus:ring-1 focus:ring-ring";
const startingFields = { name:"أحمد محمد العتيبي", identity:"1012345678", nationality:"سعودي", gender:"ذكر", birth:"1990-05-12", marital:"متزوج", phone:"05xxxxxxxx", email:"ahmed@example.com", address:"الرياض - حي النخيل", city:"الرياض", dept:"الخدمات الطبية", position:"استشاري قلب", contract:"دوام كامل", start:"2026-10-10", manager:"د. خالد الشمري", cost:"مستشفى الرياض العام" };
type FieldKey = keyof typeof startingFields;
const personalFields: {key:FieldKey;label:string;required?:boolean;options?:string[]}[] = [
  {key:"name",label:"الاسم الكامل",required:true},{key:"identity",label:"رقم الهوية / الإقامة",required:true},
  {key:"nationality",label:"الجنسية",required:true,options:["سعودي","غير سعودي"]},{key:"birth",label:"تاريخ الميلاد",required:true},
  {key:"gender",label:"الجنس",required:true,options:["ذكر","أنثى"]},{key:"marital",label:"الحالة الاجتماعية",options:["متزوج","أعزب"]},
  {key:"phone",label:"رقم الجوال",required:true},{key:"email",label:"البريد الإلكتروني"},
  {key:"address",label:"العنوان",required:true},{key:"city",label:"المدينة",required:true,options:["الرياض","جدة","الدمام"]},
];
const jobFields: typeof personalFields = [
  {key:"dept",label:"القسم",required:true,options:["الخدمات الطبية","الشؤون المالية","الموارد البشرية","خدمة العملاء"]},
  {key:"position",label:"المسمى الوظيفي",required:true,options:["استشاري قلب","طبيب عام","أخصائي","موظف"]},
  {key:"contract",label:"نوع العقد",required:true,options:["دوام كامل","دوام جزئي"]},
  {key:"start",label:"تاريخ المباشرة",required:true},
  {key:"manager",label:"المدير المباشر",required:true},
  {key:"cost",label:"مركز التكلفة",options:["مستشفى الرياض العام","الإدارة العامة"]},
];
function SectionTitle({title}:{title:string}) {return <h2 className="mb-2 flex items-center gap-2 rounded bg-primary-soft px-2 py-1.5 text-xs font-extrabold text-buy-navy"><BriefcaseBusiness size={14}/>{title}</h2>}
export function EmployeeOnboarding() {
  const [fields,setFields] = useState(startingFields);
  const [stage,setStage] = useState(0);
  const [tasks,setTasks] = useState<string[]>([onboardingTasks[0].title,onboardingTasks[1].title,onboardingTasks[2].title,onboardingTasks[3].title]);
  const [docs,setDocs] = useState<Record<string,string>>(Object.fromEntries(onboardingDocuments.map(d=>[d.title,d.status])));
  const [selectedDoc,setSelectedDoc] = useState("");
  const [notes,setNotes] = useState("");
  const [feedback,setFeedback] = useState("");
  const fileInput = useRef<HTMLInputElement>(null);
  const setField = (key:FieldKey,value:string) => setFields(current=>({...current,[key]:value}));
  const toggleTask = (title:string) => setTasks(current=>current.includes(title)?current.filter(t=>t!==title):[...current,title]);
  const field = ({key,label,required,options}:{key:FieldKey;label:string;required?:boolean;options?:string[]}) => <label key={key} className="min-w-0 text-[10px] font-bold text-buy-navy">{label} {required && <span className="text-destructive">*</span>}{options?<select aria-label={label} value={fields[key]} onChange={e=>setField(key,e.target.value)} className={inputClass}>{options.map(x=><option key={x}>{x}</option>)}</select>:<input aria-label={label} type={key==="birth"||key==="start"?"date":"text"} value={fields[key]} onChange={e=>setField(key,e.target.value)} className={inputClass}/>}</label>;
  const upload = (title:string) => {setSelectedDoc(title);fileInput.current?.click()};
  return <AppShell><main dir="rtl" className="min-w-0 bg-background px-3 py-3 text-buy-navy md:px-4"><div className="mb-3"><h1 className="text-xl font-black">تهيئة الموظف</h1><div className="flex flex-wrap items-center gap-1 text-[10px] text-muted-foreground"><Link to="/" className="hover:text-primary">الرئيسية</Link><ChevronLeft size={10}/><Link to="/employees/profile" className="hover:text-primary">الموظفين</Link><ChevronLeft size={10}/>تهيئة الموظف</div></div>
    <div className="grid min-w-0 gap-2.5 xl:grid-cols-[minmax(0,1fr)_235px]"><div className="min-w-0 space-y-2.5"><div className={`${panel} overflow-x-auto`}><div className="flex min-w-[620px] items-start">{onboardingStages.map((s,i)=><Button key={s} type="button" variant="ghost" onClick={()=>setStage(i)} className="relative h-auto min-w-0 flex-1 flex-col gap-2 px-0 text-[10px] hover:bg-transparent"><span className={`relative z-10 grid size-7 place-items-center rounded-full font-bold ${stage===i?"bg-primary text-primary-foreground":"bg-primary-soft text-buy-navy"}`}>{i+1}</span><span className={stage===i?"font-extrabold text-primary":"text-buy-navy"}>{s}</span>{i<onboardingStages.length-1&&<span className="absolute top-3.5 right-1/2 h-0.5 w-full bg-primary-soft"/>}</Button>)}</div></div>
      <div className="grid min-w-0 gap-2.5 lg:grid-cols-[minmax(0,1.4fr)_minmax(260px,0.9fr)]"><section className={panel}><SectionTitle title="البيانات الأساسية للموظف"/><div className="grid gap-x-3 gap-y-2 sm:grid-cols-2">{personalFields.map(field)}</div><div className="mt-4"><SectionTitle title="بيانات الوظيفة"/><div className="grid gap-x-3 gap-y-2 sm:grid-cols-2">{jobFields.map(field)}</div></div></section>
      <section className={`${panel} flex flex-col`}><SectionTitle title="قائمة مهام التهيئة"/><div className="flex items-center justify-between gap-3 px-1 py-2"><div className="text-center text-xs font-bold">{tasks.length}/8</div><div className="flex-1"><div className="flex justify-between text-[10px] font-bold"><span>إكمال المهام</span><span>{Math.round(tasks.length/8*100)}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-primary-soft"><div className="h-full rounded-full bg-success" style={{width:`${tasks.length/8*100}%`}}/></div></div></div><div className="my-2 space-y-1">{onboardingTasks.map(t=><Button type="button" variant="ghost" key={t.title} onClick={()=>toggleTask(t.title)} className="flex h-8 w-full items-center justify-between gap-1 px-1 text-[10px] font-medium text-buy-navy"><span className="flex min-w-0 items-center gap-1 truncate"><ClipboardList size={13} className="shrink-0 text-buy-navy"/>{t.title}</span><span className={`shrink-0 rounded-full px-2 py-0.5 text-[9px] ${tasks.includes(t.title)?"bg-success-soft text-success":t.status==="قيد التنفيذ"?"bg-primary-soft text-primary":"bg-muted text-muted-foreground"}`}>{tasks.includes(t.title)?"مكتمل":t.status==="مكتمل"?"بانتظار":t.status}</span></Button>)}</div><div className="mt-auto"><SectionTitle title="ملاحظات التهيئة"/><textarea aria-label="ملاحظات التهيئة" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="أضف أي ملاحظات ..." className="h-24 w-full resize-none rounded border border-input bg-card p-2 text-[11px] outline-none focus:ring-1 focus:ring-ring"/><div className="mt-2 flex flex-wrap gap-2"><Button className="flex-1" variant="outline" onClick={()=>setFeedback("تم إعداد نسخة تجريبية للمراجعة؛ لن تُحفظ بعد تحديث الصفحة.")}><Send size={14}/>إرسال للمراجعة</Button><Button className="flex-1" onClick={()=>setFeedback("تم إعداد المسودة محليًا؛ لن تُحفظ بعد تحديث الصفحة.")}><Save size={14}/>حفظ كمسودة</Button></div>{feedback&&<p role="status" className="mt-2 text-[10px] text-success">{feedback}</p>}</div></section></div></div>
      <aside className="min-w-0 space-y-2.5"><section className={panel}><div className="relative flex flex-col items-center border-b border-border pb-3 text-center"><img src={employeePhoto} alt="صورة توضيحية للموظف" className="size-24 rounded-full border border-border object-cover"/><span className="absolute right-[calc(50%-48px)] top-16 grid size-6 place-items-center rounded-full bg-buy-navy text-primary-foreground"><Pencil size={12}/></span><h2 className="mt-2 text-sm font-extrabold">{fields.name}</h2><span className="text-[10px]">{fields.position}</span><span className="mt-2 rounded-full bg-success-soft px-3 py-1 text-[10px] font-bold text-success">قيد التهيئة</span></div><dl className="space-y-2 pt-3 text-[10px]">{[["رقم الموظف","EMP-001"],["رقم الهوية",fields.identity],["الجنسية",fields.nationality],["رقم الجوال",fields.phone],["البريد الإلكتروني",fields.email],["تاريخ المباشرة",fields.start]].map(([k,v])=><div key={k} className="flex justify-between gap-2"><dt className="text-muted-foreground">{k}</dt><dd className="min-w-0 truncate font-bold" dir={k==="البريد الإلكتروني"?"ltr":undefined}>{v}</dd></div>)}</dl></section>
      <section className={panel}><h2 className="mb-2 flex items-center gap-2 text-xs font-extrabold"><FileText size={15}/>المستندات المطلوبة</h2><input ref={fileInput} type="file" className="hidden" aria-label="رفع مستند" onChange={e=>{if(e.target.files?.length){setDocs(current=>({...current,[selectedDoc]:"مرفوع"}));setFeedback(`تم اختيار المستند ${selectedDoc} محليًا فقط؛ لن يُرفع إلى خادم.`);e.target.value=""}}}/><div className="space-y-1">{onboardingDocuments.map(d=><div key={d.title} className="flex items-center justify-between gap-1 border-b border-border py-1.5 text-[10px] last:border-0"><span className="min-w-0 truncate font-semibold">{d.title}</span><span className={`shrink-0 rounded-full px-2 py-0.5 ${docs[d.title]==="مرفوع"?"bg-success-soft text-success":docs[d.title]==="قيد المراجعة"?"bg-warning-soft text-warning":"bg-muted text-muted-foreground"}`}>{docs[d.title]==="مرفوع"?<Check className="inline size-3"/>:null} {docs[d.title]}</span><Button type="button" variant="ghost" size="icon" className="size-6 shrink-0" aria-label={`رفع ${d.title}`} onClick={()=>upload(d.title)}><Upload size={15}/></Button></div>)}</div></section></aside>
    </div><p className="mt-2 text-[9px] text-muted-foreground">هذه شاشة توضيحية، ولا تُحفظ البيانات أو الملفات بعد تحديث الصفحة.</p></main></AppShell>;
}
