import type { LucideIcon } from "lucide-react";
import {
  ArrowLeft, Banknote, BarChart3, Building2, Check, CheckCircle2, ChevronLeft,
  CircleDollarSign, CreditCard, FileBarChart, FileText, HandCoins, Landmark,
  ReceiptText, Send, TrendingUp, WalletCards,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { financeAccounts, financeStats, financeTransactions } from "@/data/mockData";

const iconMap:Record<string,LucideIcon>={flow:TrendingUp,bank:Landmark,document:FileText,card:CreditCard,cash:HandCoins};
const tones=["tone-green bg-success-soft","tone-sky bg-search","tone-purple bg-muted","tone-orange bg-warning-soft","tone-green bg-success-soft"];

function PanelTitle({title,action}:{title:string;action?:string}){return <div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-xs font-extrabold">{title}</h2>{action&&<button className="flex items-center gap-1 text-[8px] text-primary">{action}<ChevronLeft size={12}/></button>}</div>}

function Stats(){return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{financeStats.map((s,i)=>{const Icon=iconMap[s[4]]??FileText;return <article key={s[0]} className={`panel min-h-[150px] p-4 ${tones[i]}`}><div className="flex items-start justify-between"><div><h2 className="text-[10px] font-extrabold text-foreground">{s[0]}</h2><strong className="mt-5 block text-xl text-foreground">{s[1]}</strong><p className="mt-3 text-[8px] text-muted-foreground">{s[2]}</p></div><span className="icon-well"><Icon size={18}/></span></div><button className="mt-4 flex items-center gap-1 text-[8px] text-primary">{s[3]}<ArrowLeft size={11}/></button></article>})}</section>}

function Accounts(){return <section className="panel"><PanelTitle title="حركة الحسابات البنكية" action="عرض الكل"/><div className="grid divide-y divide-border">{financeAccounts.map((a,i)=><div key={a[0]} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 p-3"><span className={`icon-well ${i===0?"tone-green":i===1?"tone-blue":"tone-purple"}`}><Building2 size={16}/></span><div><b className="block text-[9px]">{a[0]}</b><span className="text-[7px] text-muted-foreground">{a[1]}</span></div><div className="text-left"><span className="block text-[7px] text-success">نشط</span><b className="text-[10px]">{a[2]}</b></div></div>)}</div></section>}

function ExpenseDistribution(){const rows=[["المشروعات","32%","bg-success"],["الموارد البشرية","18%","bg-primary"],["التشغيل والصيانة","15%","bg-warning"],["التسويق","12%","bg-destructive"],["أخرى","23%","bg-muted-foreground"]];return <section className="panel"><PanelTitle title="توزيع المصروفات حسب القطاع"/><div className="grid items-center gap-4 p-4 sm:grid-cols-[1fr_130px]"><div className="report-ring"><strong>1,250,000</strong><span>ر.س</span></div><div className="grid gap-3">{rows.map(([n,p,c])=><div key={n} className="grid grid-cols-[auto_1fr_auto] items-center gap-2 text-[8px]"><span className={`h-2 w-2 rounded-full ${c}`}/><span>{n}</span><b>{p}</b></div>)}</div></div></section>}

function CashChart(){const months=["أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر"];const green=[64,50,43,55,56,60],blue=[42,38,26,45,34,48];return <section className="panel"><PanelTitle title="تحليل المصروفات والإيرادات"/><div className="flex justify-end gap-4 px-4 pt-2 text-[8px]"><span className="text-success">● الإيرادات</span><span className="text-primary">● المصروفات</span></div><div className="flex h-40 items-end justify-around gap-2 border-b border-border px-5 pb-1">{months.map((m,i)=><div key={m} className="flex h-full flex-1 flex-col justify-end"><div className="flex h-[110px] items-end justify-center gap-1"><span className="w-3 bg-primary" style={{height:`${blue[i]}%`}}/><span className="w-3 bg-success" style={{height:`${green[i]}%`}}/></div><span className="mt-2 text-center text-[7px]">{m}</span></div>)}</div></section>}

function Journey(){const steps:{title:string;text:string;Icon:LucideIcon}[]=[{title:"استقبال المعاملة",text:"تم استلام المعاملة وتسجيلها",Icon:ReceiptText},{title:"المراجعة والموافقة",text:"جاري المراجعة من الإدارة المختصة",Icon:CheckCircle2},{title:"الترحيل للصندوق",text:"تم الترحيل إلى الصندوق",Icon:WalletCards},{title:"أمر الصرف / الدفع",text:"تم إصدار أمر الصرف أو الدفع",Icon:FileText},{title:"تنفيذ المعاملة",text:"تم تنفيذ المعاملة بنجاح",Icon:Check}];return <section className="panel"><PanelTitle title="رحلة المعاملة المالية"/><div className="overflow-x-auto p-4"><div className="flex min-w-[760px] flex-row-reverse">{steps.map(({title,text,Icon},i)=><div key={title} className="relative flex flex-1 flex-col items-center text-center after:absolute after:left-1/2 after:top-5 after:h-px after:w-full after:bg-border last:after:hidden"><span className={`z-10 grid h-10 w-10 place-items-center rounded-full ${i<2?"bg-success-soft text-success":"bg-search text-primary"}`}><Icon size={18}/></span><b className="mt-2 text-[8px]">{title}</b><span className="mt-1 text-[7px] text-muted-foreground">{text}</span></div>)}</div></div></section>}

function FinancialSummary(){const rows=[["إجمالي الإيرادات","2,850,000 ر.س","+ 12%","text-success"],["إجمالي المصروفات","1,250,000 ر.س","- 8%","text-destructive"],["صافي التدفق النقدي","1,600,000 ر.س","+ 15%","text-success"]];return <section className="panel"><PanelTitle title="ملخص مالي"/>{rows.map(([n,v,p,c])=><div key={n} className="flex items-center justify-between border-b border-border p-3 last:border-0"><div><span className="text-[8px]">{n}</span><b className="mt-1 block text-[11px]">{v}</b></div><strong className={`text-[9px] ${c}`}>{p}</strong></div>)}</section>}

function Transactions(){return <section className="panel overflow-hidden"><PanelTitle title="أحدث المعاملات المالية" action="عرض الكل"/><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-[8px]"><thead className="bg-search"><tr>{["رقم المعاملة","نوع المعاملة","المبلغ","الجهة","الحالة","التاريخ",""].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{financeTransactions.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c} className="p-2 font-bold">{i===4?<span className={`rounded-full px-2 py-1 ${c.includes("تمت")?"bg-success-soft text-success":c.includes("الترحيل")?"bg-search text-primary":"bg-warning-soft text-warning"}`}>{c}</span>:c}</td>)}<td className="p-2">••</td></tr>)}</tbody></table></div></section>}

function QuickTools(){const tools:{name:string;Icon:LucideIcon;tone:string}[]=[{name:"رفع سند قبض",Icon:ReceiptText,tone:"tone-sky"},{name:"إصدار أمر دفع",Icon:CreditCard,tone:"tone-blue"},{name:"إصدار أمر صرف",Icon:Send,tone:"tone-green"},{name:"تحليل البيانات",Icon:BarChart3,tone:"tone-purple"}];return <section className="panel"><PanelTitle title="أدوات سريعة"/><div className="grid grid-cols-2 gap-px bg-border p-px sm:grid-cols-4 lg:grid-cols-2 xl:grid-cols-4">{tools.map(({name,Icon,tone})=><Button key={name} variant="ghost" className="h-20 flex-col rounded-none bg-card text-[8px]"><span className={`icon-well ${tone}`}><Icon size={17}/></span>{name}</Button>)}</div></section>}

export function FinanceDashboardPage(){return <main className="min-h-screen bg-background p-3 sm:p-4" dir="rtl"><div className="mx-auto max-w-[1250px]"><section className="panel mb-3 overflow-hidden bg-search px-6 py-5"><div className="flex items-center justify-between gap-4"><div><h1 className="text-2xl font-extrabold">مرحباً، أحمد 👋</h1><p className="mt-2 text-[10px] text-muted-foreground">تابع معاملاتك المالية، وأصدر الموافقات، واطلع على حركة حسابات الشركة في مكان واحد.</p></div><span className="grid h-20 w-24 place-items-center text-primary"><CircleDollarSign size={62}/></span></div></section><Stats/><div className="mt-3 grid gap-3 lg:grid-cols-3"><Accounts/><ExpenseDistribution/><CashChart/></div><div className="mt-3"><Journey/></div><div className="mt-3 grid gap-3 lg:grid-cols-[220px_minmax(0,1fr)_250px]"><FinancialSummary/><Transactions/><QuickTools/></div></div></main>}