import { useMemo, useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { formTemplates } from "@/data/mockData";
import { Clipboard, Copy, Ellipsis, FileText, Pencil, Plus, Printer, Search, Trash2, Users, WalletCards, CalendarDays, ClipboardCheck, FolderOpen, Eye, X } from "lucide-react";

type Template = { id: number; name: string; category: string; description: string; date: string; status: string };
const initial: Template[] = formTemplates.map(([name, category, description, date], i) => ({ id: i + 1, name, category, description, date, status: i === 8 ? "تحت المراجعة" : "مفعل" }));
const field = "h-9 min-w-0 w-full rounded border border-input bg-card px-2 text-xs outline-none focus:border-primary";
const categories = ["نماذج التوظيف", "شؤون الموظفين", "الرواتب والبدلات", "نماذج الإجازات", "نماذج التقييم", "أخرى"];
const statCards = [
  { label: "جميع النماذج", value: 24, icon: FileText, tone: "text-primary", bg: "bg-primary-soft" },
  { label: "نماذج التوظيف", value: 6, icon: Clipboard, tone: "text-success", bg: "bg-success-soft" },
  { label: "نماذج شؤون الموظفين", value: 5, icon: Users, tone: "text-finance-orange", bg: "bg-finance-peach" },
  { label: "نماذج الرواتب والبدلات", value: 4, icon: WalletCards, tone: "text-buy-violet", bg: "bg-buy-violet-soft" },
  { label: "نماذج الإجازات", value: 4, icon: CalendarDays, tone: "text-destructive", bg: "bg-destructive/10" },
  { label: "نماذج التقييم", value: 3, icon: ClipboardCheck, tone: "text-finance-teal", bg: "bg-finance-mint" },
  { label: "نماذج أخرى", value: 2, icon: FolderOpen, tone: "text-primary", bg: "bg-primary-soft" },
];
export function FormsPage() {
  const [rows, setRows] = useState<Template[]>(initial);
  const [selectedId, setSelectedId] = useState(1);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  const [status, setStatus] = useState("");
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(10);
  const [editor, setEditor] = useState<Template | null>(null);
  const [editing, setEditing] = useState(false);
  const [filling, setFilling] = useState(false);
  const [filled, setFilled] = useState({ name: "", id: "", phone: "", job: "", department: "", qualification: "", experience: "", notes: "" });
  const [notice, setNotice] = useState("");
  const selected = rows.find(r => r.id === selectedId);
  const visible = useMemo(() => rows.filter(r => (!query || `${r.name} ${r.description}`.includes(query)) && (!category || r.category === category) && (!status || r.status === status)), [rows, query, category, status]);
  const pageCount = Math.max(1, Math.ceil(visible.length / size));
  const current = Math.min(page, pageCount);
  const shown = visible.slice((current - 1) * size, current * size);
  function save(e: FormEvent) { e.preventDefault(); if (!editor?.name.trim() || !editor.description.trim()) return; if (editing) { setRows(rows.map(r => r.id === editor.id ? editor : r)); setSelectedId(editor.id); } else { setRows([editor, ...rows]); setSelectedId(editor.id); } setNotice(editing ? "تم تعديل النموذج في هذه الجلسة" : "تمت إضافة النموذج في هذه الجلسة"); setEditor(null); }
  function remove(r: Template) { if (!window.confirm(`حذف نموذج «${r.name}» من هذه الجلسة؟`)) return; const next = rows.filter(x => x.id !== r.id); setRows(next); if (selectedId === r.id) setSelectedId(next[0]?.id ?? 0); setNotice("تم حذف النموذج في هذه الجلسة"); }
  function copy(r: Template) { const id = Math.max(0, ...rows.map(x => x.id)) + 1; setRows([{ ...r, id, name: `${r.name} - نسخة` }, ...rows]); setSelectedId(id); setNotice("تم نسخ النموذج في هذه الجلسة"); }
  const openNew = () => { setEditing(false); setEditor({ id: Math.max(0, ...rows.map(x => x.id)) + 1, name: "", category: categories[0] ?? "أخرى", description: "", date: new Date().toISOString().slice(0, 10).replaceAll("-", "/"), status: "مفعل" }); };
  return <AppShell><main dir="rtl" className="min-w-0 space-y-3 px-3 py-3 md:px-5">
    <header><h1 className="text-xl font-extrabold text-buy-navy">النماذج</h1><p className="text-[11px] text-primary"><Link to="/">الرئيسية</Link> / الموارد البشرية / النماذج</p></header>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7">{statCards.map((s, i) => <div key={s.label} className="flex min-w-0 items-center justify-between gap-1 rounded border border-border bg-card px-2 py-2 shadow-sm"><div className="min-w-0"><p className="text-[9px] font-bold leading-4 text-foreground">{s.label}</p><p className={`text-xl font-extrabold ${s.tone}`}>{s.value + (i === 0 ? rows.length - initial.length : 0)}</p><span className="text-[9px] text-muted-foreground">نموذج</span></div><span className={`grid size-9 shrink-0 place-items-center rounded-full ${s.bg} ${s.tone}`}><s.icon size={19}/></span></div>)}</div>
    <div className="grid min-w-0 gap-3 xl:grid-cols-[minmax(320px,.82fr)_minmax(0,1.7fr)]">
      <section className="min-w-0 xl:order-1"><div className="mb-2 flex items-center justify-between"><h2 className="flex items-center gap-1 text-sm font-bold"><Eye size={16}/> معاينة النموذج</h2><div className="flex gap-1"><Button size="sm" variant="outline" disabled={!selected} onClick={() => { setFilling(true); setNotice(""); }}><Clipboard/> استخدام النموذج</Button><Button size="sm" disabled={!selected} className="bg-buy-navy text-primary-foreground" onClick={() => window.print()}><Printer/> PDF</Button></div></div>
        <div id="form-preview" className="min-h-[490px] rounded border border-border bg-card p-4 text-[10px] shadow-sm sm:p-5"><div className="flex items-end justify-between border-b border-buy-navy pb-2"><div><b className="text-base text-buy-navy">تكامل بلس</b><p>إدارة الموارد البشرية</p></div><FileText className="text-primary"/></div>{selected ? <><h3 className="my-5 text-center text-sm font-extrabold text-buy-navy">{selected.name}</h3><p className="mb-3 bg-primary-soft px-2 py-1 font-bold">البيانات الشخصية</p><div className="grid grid-cols-2 gap-x-2 gap-y-0.5">{[["الاسم الكامل",filled.name],["رقم الهوية / الإقامة",filled.id],["الجنسية",""],["تاريخ الميلاد",""],["الحالة الاجتماعية",""],["رقم الجوال",filled.phone],["البريد الإلكتروني",""],["العنوان الوطني",""]].map(([k,v]) => <div key={k} className="flex min-h-7 border border-border"><span className="w-2/5 bg-primary-soft/60 px-1 py-1 font-bold">{k}</span><span className="flex-1 px-1 py-1">{filling ? v : ""}</span></div>)}</div><p className="mb-2 mt-4 bg-primary-soft px-2 py-1 font-bold">البيانات المهنية</p><div className="grid grid-cols-2 gap-0.5">{[["الوظيفة المطلوبة",filled.job],["القسم",filled.department],["المؤهل العلمي",filled.qualification],["الخبرات السابقة",filled.experience],["اللغات", ""],["المهارات", ""]].map(([k,v]) => <div key={k} className="flex min-h-7 border border-border"><span className="w-2/5 bg-primary-soft/60 px-1 py-1 font-bold">{k}</span><span className="flex-1 px-1 py-1">{filling ? v : ""}</span></div>)}</div><p className="mb-2 mt-4 bg-primary-soft px-2 py-1 font-bold">المرفقات</p><div className="flex min-h-12 items-center justify-center border border-dashed border-border text-muted-foreground">إرفاق السيرة الذاتية والمستندات المطلوبة</div><div className="mt-5 flex justify-between border-t border-border pt-2"><span>تاريخ التقديم: ......................</span><span>توقيع مقدم الطلب: ......................</span></div></> : <p className="py-24 text-center text-muted-foreground">لا يوجد نموذج محدد</p>}</div>
      </section>
      <section className="min-w-0 xl:order-2"><div className="mb-2 grid gap-1.5 sm:grid-cols-[minmax(0,1fr)_130px_130px_auto]"><label className="relative"><Search size={15} className="absolute right-2 top-2.5 text-primary"/><input className={`${field} pr-8`} placeholder="البحث في النماذج ..." aria-label="البحث في النماذج" value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/></label><select className={field} aria-label="حالة النماذج" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">جميع الحالات</option><option>مفعل</option><option>تحت المراجعة</option></select><select className={field} aria-label="فئة النماذج" value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">جميع الفئات</option>{categories.map(c => <option key={c}>{c}</option>)}</select><Button className="bg-buy-navy text-primary-foreground" onClick={openNew}><Plus/> إضافة نموذج جديد</Button></div>
        <div className="min-w-0 overflow-x-auto rounded border border-border bg-card shadow-sm"><table className="w-full min-w-[650px] text-right text-[10px]"><thead className="bg-primary-soft/70"><tr>{["م","اسم النموذج","الفئة","الوصف","تاريخ الإنشاء","الحالة","الإجراءات"].map(h => <th key={h} className="whitespace-nowrap px-2 py-2 font-bold">{h}</th>)}</tr></thead><tbody>{shown.map(r => <tr key={r.id} onClick={() => { setSelectedId(r.id); setFilling(false); }} className={`cursor-pointer border-t border-border ${selectedId === r.id ? "bg-primary-soft/25" : ""}`}><td className="px-2 py-2">{r.id}</td><td className="whitespace-nowrap px-2 py-2 font-bold">{r.name}</td><td className="whitespace-nowrap px-2 py-2">{r.category}</td><td className="max-w-48 truncate px-2 py-2" title={r.description}>{r.description}</td><td className="whitespace-nowrap px-2 py-2" dir="ltr">{r.date}</td><td className="px-2 py-2"><span className={`whitespace-nowrap rounded px-2 py-0.5 ${r.status === "مفعل" ? "bg-success-soft text-success" : "bg-warning-soft text-warning"}`}>{r.status}</span></td><td className="px-1 py-1"><div className="flex items-center"><Button variant="ghost" size="icon" className="size-6" title="المزيد" aria-label={`المزيد ${r.name}`} onClick={e => { e.stopPropagation(); setSelectedId(r.id); }}><Ellipsis/></Button><Button variant="ghost" size="icon" className="size-6" title="تعديل" aria-label={`تعديل ${r.name}`} onClick={e => { e.stopPropagation(); setEditor({...r}); setEditing(true); }}><Pencil/></Button><Button variant="ghost" size="icon" className="size-6" title="نسخ" aria-label={`نسخ ${r.name}`} onClick={e => { e.stopPropagation(); copy(r); }}><Copy/></Button><Button variant="ghost" size="icon" className="size-6 text-destructive" title="حذف" aria-label={`حذف ${r.name}`} onClick={e => { e.stopPropagation(); remove(r); }}><Trash2/></Button></div></td></tr>)}{!shown.length && <tr><td colSpan={7} className="py-12 text-center text-muted-foreground">لا توجد نماذج مطابقة</td></tr>}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-2 rounded-b border border-t-0 border-border bg-card px-2 py-2 text-[11px]"><div className="flex items-center gap-2"><select className="rounded border border-border px-1" value={size} aria-label="عدد النماذج في الصفحة" onChange={e => { setSize(+e.target.value); setPage(1); }}><option>10</option><option>25</option></select>عرض {visible.length ? (current-1)*size+1 : 0} إلى {Math.min(current*size,visible.length)} من أصل {visible.length} نتيجة</div><div className="flex gap-1">{Array.from({length:pageCount},(_,i) => <Button key={i} variant={current === i+1 ? "default" : "outline"} size="icon" className="size-7" onClick={() => setPage(i+1)}>{i+1}</Button>)}</div></div>{notice && <p role="status" className="mt-2 text-xs text-success">{notice}</p>}</section>
    </div>
    {editor && <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-3" onClick={() => setEditor(null)}><form onClick={e => e.stopPropagation()} onSubmit={save} className="w-full max-w-md space-y-3 rounded border border-border bg-card p-5 shadow-xl"><div className="flex justify-between"><h2 className="font-bold">{editing ? "تعديل النموذج" : "إضافة نموذج جديد"}</h2><Button type="button" variant="ghost" size="icon" onClick={() => setEditor(null)} aria-label="إغلاق"><X/></Button></div><label className="block text-xs">اسم النموذج<input required className={`${field} mt-1`} value={editor.name} onChange={e => setEditor({...editor,name:e.target.value})}/></label><label className="block text-xs">الفئة<select className={`${field} mt-1`} value={editor.category} onChange={e => setEditor({...editor,category:e.target.value})}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label className="block text-xs">الوصف<textarea required className={`${field} mt-1 h-20 p-2`} value={editor.description} onChange={e => setEditor({...editor,description:e.target.value})}/></label><label className="block text-xs">الحالة<select className={`${field} mt-1`} value={editor.status} onChange={e => setEditor({...editor,status:e.target.value})}><option>مفعل</option><option>تحت المراجعة</option></select></label><Button type="submit" className="w-full">حفظ النموذج</Button></form></div>}
    {filling && <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-3" onClick={() => setFilling(false)}><form onClick={e => e.stopPropagation()} onSubmit={e => { e.preventDefault(); setFilling(false); setNotice("تمت تعبئة المعاينة محليًا، يمكنك طباعتها كـ PDF"); }} className="max-h-[90vh] w-full max-w-lg space-y-3 overflow-y-auto rounded border border-border bg-card p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">تعبئة {selected?.name}</h2><Button type="button" variant="ghost" size="icon" onClick={() => setFilling(false)} aria-label="إغلاق"><X/></Button></div><div className="grid grid-cols-2 gap-2">{([ ["name","الاسم الكامل"],["id","رقم الهوية / الإقامة"],["phone","رقم الجوال"],["job","الوظيفة المطلوبة"],["department","القسم"],["qualification","المؤهل العلمي"],["experience","الخبرات السابقة"],["notes","ملاحظات"]] as const).map(([key,label]) => <label key={key} className="min-w-0 text-xs">{label}<input className={`${field} mt-1`} value={filled[key]} onChange={e => setFilled({...filled,[key]:e.target.value})}/></label>)}</div><Button type="submit" className="w-full">عرض البيانات في النموذج</Button></form></div>}
  </main></AppShell>;
}
