import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUp, BarChart3, Bell, CalendarDays, ChevronDown, Coins, FilePlus2, FileText, Headset, PieChart, ReceiptText, Send, UploadCloud, UserRoundPlus, Users, Wallet } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { homeSummary, homeDepartments, homeTicketStatuses, homeTransactionTypes, homeRevenueMonths, homeRecentEmployees, homeRecentTransactions, homeRecentTickets } from "@/data/mockData";

const panel = "min-w-0 rounded-md border border-border bg-card shadow-sm";
const tones = {blue: "bg-primary-soft text-primary", amber: "bg-warning-soft text-warning", green: "bg-success-soft text-success", violet: "bg-buy-violet-soft text-buy-violet"};
const statIcons = [Headset, FileText, Coins, Users];
const quick = [
  { label: "اعتماد طلب", icon: FilePlus2, to: "/requests/tracking", tone: "bg-primary-soft text-primary" },
  { label: "إنشاء تذكرة دعم", icon: Headset, to: "/customer-service/inbox", tone: "bg-buy-violet-soft text-buy-violet" },
  { label: "إضافة مصروف", icon: ReceiptText, to: "/finance/payment-orders", tone: "bg-warning-soft text-warning" },
  { label: "إصدار راتب", icon: Coins, to: "/salaries/payroll", tone: "bg-success-soft text-success" },
  { label: "إضافة موظف", icon: UserRoundPlus, to: "/employees/new", tone: "bg-warning-soft text-warning" },
  { label: "إرسال إشعار", icon: Send, to: "/notifications", tone: "bg-destructive/10 text-destructive" },
  { label: "إضافة عميل", icon: UserRoundPlus, to: "/customer-service/inbox", tone: "bg-warning-soft text-warning" },
  { label: "إنشاء تقرير", icon: BarChart3, to: "/reports/hr", tone: "bg-primary-soft text-primary" },
  { label: "رفع مستند", icon: UploadCloud, to: "/employees/documents", tone: "bg-buy-violet-soft text-buy-violet" },
  { label: "إضافة ميزانية", icon: PieChart, to: "/finance", tone: "bg-success-soft text-success" },
] as const;
function Period({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <label className="relative inline-flex shrink-0 items-center rounded border border-border bg-card text-[10px] font-bold text-buy-navy"><CalendarDays className="mr-1 size-3 text-buy-navy"/><select aria-label="الفترة الزمنية" value={value} onChange={e => onChange(e.target.value)} className="appearance-none bg-transparent py-1 pr-2 pl-5 outline-none"><option>هذا الشهر</option><option>الشهر السابق</option><option>هذا العام</option></select><ChevronDown className="pointer-events-none absolute left-1 size-3"/></label>;
}
function Header({ title, period, onPeriod }: {title: string;period?: string;onPeriod?: (value: string) => void}) {
  return <div className="mb-3 flex min-h-7 items-center justify-between gap-2"><h2 className="text-xs font-extrabold text-buy-navy sm:text-sm">{title}</h2>{period && onPeriod && <Period value={period} onChange={onPeriod}/>}</div>;
}
function Ring({ data, total, label }: { data: readonly {label:string;value:number;color:string}[];total:number;label:string }) {
  let start = 0;
  const segments = data.map(d => { const from = start; start += d.value / total * 100; return `${d.color} ${from}% ${start}%`; }).join(", ");
  return <div className="relative mx-auto size-[118px] shrink-0 rounded-full sm:size-[132px]" style={{background: `conic-gradient(${segments})`}}><div className="absolute inset-[20%] flex flex-col items-center justify-center rounded-full bg-card text-center"><strong className="text-xl font-black text-buy-navy">{total}</strong><small className="text-[10px] text-buy-navy">{label}</small></div></div>;
}
function Status({ text }: {text:string}) {const tone = text === "مفعل" || text === "معتمدة" || text === "مغلقة" ? "bg-success-soft text-success" : text === "مفتوحة" || text === "مرفوضة" ? "bg-destructive/10 text-destructive" : text.includes("العميل") ? "bg-primary-soft text-primary" : "bg-warning-soft text-warning";return <span className={`inline-block whitespace-nowrap rounded-full px-2 py-0.5 text-[9px] font-bold ${tone}`}>{text}</span>;}
function TableCard({title,headers,rows,to}:{title:string;headers:string[];rows:React.ReactNode[][];to:"/employees/profile"|"/finance"|"/customer-service/inbox"}) {return <section className={`${panel} p-2`}><div className="mb-1 flex items-center justify-between"><h2 className="text-xs font-extrabold text-buy-navy">{title}</h2><Link to={to} className="text-[10px] font-bold text-warning hover:underline">عرض الكل</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[340px] text-right text-[9px]"><thead className="bg-primary-soft text-buy-navy"><tr>{headers.map(h=><th key={h} className="whitespace-nowrap px-1.5 py-1.5">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-b border-border last:border-0">{row.map((cell,j)=><td key={j} className="whitespace-nowrap px-1.5 py-1.5">{cell}</td>)}</tr>)}</tbody></table></div></section>}
export function HomeDashboard() {
  const [period, setPeriod] = useState("هذا الشهر");
  return <AppShell><main dir="rtl" className="min-w-0 space-y-2.5 bg-background p-3 text-buy-navy md:p-4">
    <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{homeSummary.map((s,i)=>{const Icon=statIcons[i] ?? Users;return <section key={s.title} className={`${panel} min-h-[112px] border-b-2 p-3`}><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-extrabold">{s.title}</p><strong className="mt-1 block text-xl font-black sm:text-2xl">{s.value}</strong></div><span className={`grid size-11 shrink-0 place-items-center rounded-full ${tones[s.color]}`}><Icon size={23}/></span></div><div className="mt-1 flex items-end justify-between gap-1"><span className="text-[9px]">مقارنة بالشهر السابق</span><span className={`flex items-center text-sm font-extrabold ${s.title === "إجمالي المصروفات" ? "text-destructive" : "text-success"}`}><ArrowUp size={14}/>{s.change}</span></div></section>})}</div>
    <div className="grid min-w-0 gap-2.5 lg:grid-cols-[minmax(0,1.75fr)_minmax(290px,1fr)]"><section className={`${panel} p-3`}><Header title="أدوات سريعة"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{quick.map(q=><Link key={q.label} to={q.to} className={`flex h-[76px] flex-col items-center justify-center gap-1 rounded text-center text-[10px] font-extrabold transition-transform hover:-translate-y-0.5 ${q.tone}`}><q.icon size={27} strokeWidth={1.9}/>{q.label}</Link>)}</div></section><section className={`${panel} p-3`}><Header title="توزيع الموظفين حسب الأقسام" period={period} onPeriod={setPeriod}/><div className="flex flex-wrap items-center justify-center gap-3 sm:flex-nowrap"><Ring data={homeDepartments} total={312} label="موظف"/><div className="min-w-[155px] flex-1 space-y-1.5">{homeDepartments.map(d=><div key={d.label} className="flex items-center gap-1 text-[10px]"><span className="size-2.5 shrink-0 rounded-full" style={{backgroundColor:d.color}}/><span className="flex-1">{d.label}</span><span>{Math.round(d.value/312*100)}%</span><b className="w-7 text-left">{d.value}</b></div>)}</div></div></section></div>
    <div className="grid min-w-0 gap-2.5 lg:grid-cols-3"><section className={`${panel} p-3`}><Header title="المعاملات حسب النوع" period={period} onPeriod={setPeriod}/><div className="space-y-3 pt-1">{homeTransactionTypes.map(d=><div key={d.label} className="flex items-center gap-2 text-[10px]"><b className="w-[94px] shrink-0 text-left font-semibold">{d.label}</b><div className="h-3 flex-1 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${d.tone}`} style={{width:`${d.value/320*100}%`}}/></div><b className="w-7">{d.value}</b></div>)}</div></section><section className={`${panel} p-3`}><Header title="المصروفات والإيرادات" period={period} onPeriod={setPeriod}/><div className="mb-1 flex justify-center gap-4 text-[10px]"><span className="text-primary">● الإيرادات</span><span className="text-success">● المصروفات</span></div><div className="h-[130px] w-full" dir="ltr"><ResponsiveContainer width="100%" height="100%"><AreaChart data={homeRevenueMonths} margin={{top:3,right:5,left:-25,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="month" tick={{fontSize:8}}/><YAxis tick={{fontSize:8}}/><Tooltip/><Area type="monotone" dataKey="revenue" name="الإيرادات" stroke="var(--primary)" fill="var(--primary-soft)" strokeWidth={2} isAnimationActive={false}/><Area type="monotone" dataKey="expenses" name="المصروفات" stroke="var(--success)" fill="transparent" strokeWidth={2} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section><section className={`${panel} p-3`}><Header title="حالة طلبات خدمة العملاء" period={period} onPeriod={setPeriod}/><div className="flex flex-wrap items-center justify-center gap-3 sm:flex-nowrap"><Ring data={homeTicketStatuses} total={248} label="طلب"/><div className="min-w-[145px] flex-1 space-y-2">{homeTicketStatuses.map(d=><div key={d.label} className="flex items-center gap-1 text-[10px]"><span className="size-2.5 shrink-0 rounded-full" style={{backgroundColor:d.color}}/><span className="flex-1">{d.label}</span><b>{d.value}</b></div>)}</div></div></section></div>
    <div className="grid min-w-0 gap-2.5 lg:grid-cols-3"><TableCard title="أحدث الموظفين المضافين" headers={["الاسم","الوظيفة","القسم","التاريخ","الحالة"]} rows={homeRecentEmployees.map(r=>[r.name,r.job,r.dept,r.date,<Status text={r.status}/>])} to="/employees/profile"/><TableCard title="أحدث المعاملات المالية" headers={["رقم المعاملة","النوع","المبلغ (ريال)","الحالة","التاريخ"]} rows={homeRecentTransactions.map(r=>[r.code,r.kind,r.amount,<Status text={r.status}/>,r.date])} to="/finance"/><TableCard title="أحدث طلبات خدمة العملاء" headers={["رقم التذكرة","رقم التذكرة","الموضوع","الأولوية","التاريخ"]} rows={homeRecentTickets.map(r=>[r.code,r.id,r.subject,<Status text={r.priority}/>,r.date])} to="/customer-service/inbox"/></div>
    <p className="text-[9px] text-muted-foreground">بيانات توضيحية للعرض فقط</p>
  </main></AppShell>;
}
