import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { CalendarDays, Check, Eye, FileText, Plus, Search, Trash2, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { leaveReferenceRows } from "@/data/mockData";

const panel="rounded-md border border-border bg-card shadow-sm";
const months=[18,22,16,20,14,11,10,6,8,12,20,10];
const monthNames=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
const statusClass=(s:string)=>s.includes("موافق")?"bg-success-soft text-success":s.includes("مرفوض")?"bg-destructive/10 text-destructive":s.includes("ملغاة")?"bg-muted text-muted-foreground":"bg-warning-soft text-warning";

export function LeavesDashboard(){
 const [q,setQ]=useState(""); const [status,setStatus]=useState("");
 const rows=useMemo(()=>leaveReferenceRows.filter(r=>(!q||r[1].includes(q)||r[0].includes(q))&&(!status||r[7]===status)),[q,status]);
 return <AppShell><main dir="rtl" className="min-w-0 p-3 sm:p-4"><div className="mx-auto max-w-[1450px]">
  <div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] text-muted-foreground">الرئيسية　‹　الموظفين　‹　الإجازات</p><h1 className="mt-1 flex items-center gap-2 text-xl font-black text-buy-navy"><CalendarDays className="text-primary"/>الإجازات</h1></div><Button asChild><Link to="/leaves/new"><Plus/>طلب إجازة جديدة</Link></Button></div>
  <section className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{[["إجمالي أيام الإجازات","210","هذا العام",CalendarDays,"primary"],["مرفوضة","5","هذا العام",X,"destructive"],["موافق عليها","48","هذا العام",Check,"success"],["طلبات الإجازة","12","بانتظار الموافقة",FileText,"warning"]].map(([l,v,s,I,t])=>{const Icon=I as typeof CalendarDays;return <div key={String(l)} className={`${panel} flex items-center gap-4 p-4`}><span className={`grid size-12 place-items-center rounded-full bg-${String(t)}-soft text-${String(t)}`}><Icon/></span><div><b className="text-2xl">{String(v)}</b><p className="text-[10px] font-bold">{String(l)}</p><span className="text-[9px] text-muted-foreground">{String(s)}</span></div></div>})}</section>
  <section className="mt-3 grid gap-3 xl:grid-cols-[.9fr_1.35fr_.9fr] [direction:ltr]">
   <div dir="rtl" className={`${panel} p-4`}><h2 className="font-black">حالات الإجازات</h2><div className="mt-4 flex items-center gap-5"><div className="grid size-32 shrink-0 place-items-center rounded-full" style={{background:"conic-gradient(var(--success) 0 70%,var(--warning) 70% 88%,var(--destructive) 88% 95%,var(--muted) 95%)"}}><div className="grid size-20 place-items-center rounded-full bg-card text-center"><b className="text-2xl">68</b><span className="text-[8px]">إجمالي الطلبات</span></div></div><ul className="space-y-2 text-[9px]">{[["موافق عليها","48","success"],["بانتظار الموافقة","12","warning"],["مرفوضة","5","destructive"],["ملغاة","3","muted-foreground"]].map(([a,b,c])=><li key={a} className="grid grid-cols-[8px_1fr_auto] items-center gap-2"><i className={`size-2 rounded-full bg-${c}`}/><span>{a}</span><b>{b}</b></li>)}</ul></div></div>
   <div dir="rtl" className={`${panel} p-4`}><div className="flex items-center justify-between"><h2 className="font-black">عدد الإجازات حسب الأشهر</h2><select className="rounded border border-border bg-card px-3 py-1 text-[10px]"><option>2026</option></select></div><div className="mt-5 flex h-32 items-end justify-between gap-2 border-b border-border">{months.map((v,i)=><div key={monthNames[i]} className="flex flex-1 flex-col items-center justify-end"><b className="mb-1 text-[8px]">{v}</b><i className="w-full max-w-7 rounded-t bg-primary" style={{height:`${v*4}px`}}/><span className="mt-1 text-[7px]">{monthNames[i]}</span></div>)}</div></div>
   <div dir="rtl" className={`${panel} p-4`}><h2 className="font-black">أرصدة الإجازات للموظف</h2>{[["الإجازة السنوية","20 من 30 يوم","67","primary"],["إجازة مرضية","5 من 10 يوم","50","success"],["إجازة طارئة","3 من 5 يوم","60","warning"],["إجازة بدون راتب","0 من 90 يوم","0","muted-foreground"]].map(([a,b,n,c])=><div className="mt-3" key={a}><div className="flex justify-between text-[9px]"><b>{a}</b><span>{b}</span></div><div className="mt-1 h-1.5 rounded bg-muted"><i className={`block h-full rounded bg-${c}`} style={{width:`${n}%`}}/></div></div>)}</div>
  </section>
  <section className={`${panel} mt-3 overflow-hidden`}><div className="flex flex-wrap items-end justify-between gap-2 p-3"><h2 className="text-base font-black">طلبات الإجازات</h2><div className="flex flex-1 flex-wrap justify-end gap-2"><label className="relative min-w-48"><Search className="absolute right-3 top-2.5 size-4 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} className="h-9 w-full rounded border border-border bg-card pr-9 text-[10px]" placeholder="ابحث عن موظف..."/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="h-9 rounded border border-border bg-card px-3 text-[10px]"><option value="">جميع الحالات</option><option>موافق عليها</option><option>بانتظار الموافقة</option><option>مرفوضة</option><option>ملغاة</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-center text-[9px] [&_td]:p-2 [&_th]:p-2"><thead className="bg-primary-soft"><tr>{["رقم الطلب","اسم الموظف","القسم","نوع الإجازة","تاريخ البداية","تاريخ النهاية","عدد الأيام","الحالة","الإجراءات"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t border-border" key={r[0]}>{r.map((c,i)=><td key={i}>{i===7?<span className={`rounded px-3 py-1 font-bold ${statusClass(c)}`}>{c}</span>:c}</td>)}<td><span className="inline-flex gap-2"><Eye className="size-4 text-primary"/><Trash2 className="size-4 text-destructive"/></span></td></tr>)}</tbody></table></div></section>
  <p className="mt-2 text-[8px] text-muted-foreground">بيانات توضيحية تجريبية — لا يتم حفظ الطلبات أو تنفيذها فعليًا.</p>
 </div></main></AppShell>
}