import { Link } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Building2, CalendarDays, Check, CheckCircle2, ClipboardCheck, Download, FileText, FlaskConical, Mail, Search, Send, Stethoscope, UserRound, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { medicalFlowSteps, medicalTests, medicalTrackingRows } from "@/data/mockData";

type MedicalStepId = (typeof medicalFlowSteps)[number]["id"];
const medicalPaths: Record<MedicalStepId, string> = {
  request: "/medical-exam/request", tests: "/medical-exam/tests", center: "/medical-exam/center", result: "/medical-exam/result",
  company: "/medical-exam/company", hr: "/medical-exam/hr", employee: "/medical-exam/employee", tracking: "/medical-exam/tracking",
};
const titleIcons: Record<MedicalStepId, typeof Stethoscope> = { request: Stethoscope, tests: FlaskConical, center: Building2, result: ClipboardCheck, company: FileText, hr: UsersRound, employee: Mail, tracking: Search };

export function MedicalExamPage({ step }: { step: MedicalStepId }) {
  const meta = medicalFlowSteps.find((item) => item.id === step);
  if (!meta) return null;
  const Icon = titleIcons[step];
  return <AppShell><main className="p-3 sm:p-5 lg:px-6 lg:py-4">
    <div className="mb-2 flex items-center gap-2 text-[9px] text-muted-foreground"><span>الرئيسية</span><span>/</span><span>الفحص الطبي</span><span>/</span><b className="text-foreground">{meta.title}</b></div>
    <header className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3">
      <div className="flex min-w-0 items-start gap-2"><Icon className="mt-1 shrink-0 text-primary" size={25}/><div className="min-w-0"><h1 className="truncate text-lg font-extrabold">{meta.title}</h1><p className="mt-1 text-[10px] text-muted-foreground">{meta.subtitle}</p></div></div>
      <span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-primary text-sm font-extrabold text-primary-foreground">{meta.number}</span>
    </header>
    <div className="mt-3"><MedicalContent step={step}/></div>
    <MedicalNavigation step={step}/>
    <MedicalJourney active={Math.min(meta.number, 7)}/>
  </main></AppShell>;
}

function MedicalContent({step}:{step:MedicalStepId}) {
  if(step==="request") return <RequestScreen/>;
  if(step==="tests") return <TestsScreen/>;
  if(step==="center") return <CenterScreen/>;
  if(step==="result") return <ResultScreen/>;
  if(step==="company") return <CompanyScreen/>;
  if(step==="hr") return <HrScreen/>;
  if(step==="employee") return <EmployeeScreen/>;
  return <TrackingScreen/>;
}

function RequestScreen(){const [sent,setSent]=useState(false);return <section className="panel mx-auto max-w-3xl overflow-hidden"><SectionTitle title="طلب فحص طبي جديد"/><div className="grid gap-5 p-4 md:grid-cols-[220px_minmax(0,1fr)]"><EmployeeCard/><div className="space-y-3"><Field label="المركز الطبي المعتمد" value="مركز الحياة الطبي"/><Field label="نوع الفحص" value="فحص طبي شامل"/><Field label="تاريخ الموعد المقترح" value="2025/09/25" icon={<CalendarDays size={15}/>}/><label className="block text-[10px] font-bold">ملاحظات (اختياري)<textarea className="mt-1 h-16 w-full resize-none rounded-md border border-input bg-background p-2 outline-none focus:ring-2 focus:ring-ring"/></label><div className="flex justify-end gap-2"><Button variant="secondary">إلغاء</Button><Button onClick={()=>setSent(true)}><Send/>إرسال الطلب</Button></div>{sent&&<SuccessLine>تم إرسال طلب الفحص الطبي بنجاح</SuccessLine>}</div></div></section>}

function TestsScreen(){return <section className="panel mx-auto max-w-4xl overflow-hidden"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center border-b border-border p-4"><h2 className="truncate text-sm font-extrabold">طلب التحاليل مخبرية</h2><Status text="تم الإرسال"/></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] border-collapse text-right text-[10px]"><thead className="bg-search"><tr>{["التحليل","العدد","ملاحظات"].map(x=><th className="border-b border-border p-3" key={x}>{x}</th>)}</tr></thead><tbody>{medicalTests.map(r=><tr key={r[0]}>{r.map(c=><td className="border-b border-border p-3" key={c}>{c}</td>)}</tr>)}</tbody></table></div><div className="m-4"><SuccessLine>تم إرسال طلب التحاليل إلى إدارة المشتريات / الشركة</SuccessLine><p className="mt-2 text-center text-[8px] text-muted-foreground">2025/09/20 10:30 ص</p></div></section>}

function CenterScreen(){return <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="panel p-4"><div className="grid gap-4 sm:grid-cols-2"><div><Status text="تم الاستلام"/><h2 className="mt-3 text-sm font-extrabold">بيانات الفحص الطبي</h2><InfoRows items={[["اسم المركز","مركز الحياة الطبي"],["رقم الاعتماد","MED-4587"],["تاريخ الفحص","2025/09/22"],["الطبيب المعتمد","د. خالد السبيعي"]]}/></div><div className="grid min-h-48 place-items-center rounded-md border border-border bg-search"><Building2 className="text-primary" size={52}/><div className="text-center"><b className="block text-xs">مركز الحياة الطبي</b><small className="text-muted-foreground">إدارة الفحوصات الطبية</small></div></div></div></section><aside className="panel p-4"><EmployeeCard/><div className="mt-4"><Field label="رقم الطلب" value="MC-2025-4587"/><div className="mt-3"><Field label="تاريخ الموعد" value="2025/09/22"/></div></div></aside></div>}

function ResultScreen(){return <section className="panel mx-auto max-w-4xl p-4"><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_280px]"><div><Status text="تم الاستلام"/><h2 className="mt-3 text-sm font-extrabold">نتائج الفحص الطبي</h2><InfoRows items={[["اسم المركز","مركز الحياة الطبي"],["رقم التقرير","ME-2025-4587"],["تاريخ الفحص","2025/09/22"],["صالح حتى","2026/09/22"]]}/><div className="mt-4 rounded-md border border-border p-3"><b className="text-[10px]">ملاحظات الطبيب</b><p className="mt-2 text-[9px] text-muted-foreground">لا توجد ملاحظات، الحالة الصحية جيدة ومؤهلة لمزاولة العمل.</p></div></div><ResultSeal/></div><Button className="mt-4 w-full"><Send/>إرسال النتيجة إلى الشركة</Button></section>}

function CompanyScreen(){return <section className="panel mx-auto max-w-4xl overflow-hidden"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center border-b border-border p-4"><h2 className="truncate text-sm font-extrabold">تقرير الفحص الطبي للموظف</h2><Status text="تم الاستلام"/></div><div className="grid gap-5 p-4 sm:grid-cols-[220px_minmax(0,1fr)]"><EmployeeCard/><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-md border border-border p-4"><span className="text-[9px] text-muted-foreground">النتيجة</span><div className="mt-2"><Status text="مطابق"/></div><p className="mt-4 text-[9px] text-muted-foreground">تاريخ الصلاحية</p><b className="text-lg">2026/09/22</b></div><div className="rounded-md border border-border p-4"><FileText className="text-destructive" size={30}/><h3 className="mt-2 text-xs font-extrabold">تقرير الفحص الطبي</h3><p className="text-[9px] text-muted-foreground">تاريخ التقرير: 2025/09/22</p><Button variant="outline" className="mt-3"><Download/>تحميل التقرير</Button></div></div></div><div className="grid grid-cols-2 gap-2 p-4 pt-0"><Button variant="outline">عرض التفاصيل</Button><Button>متابعة الإجراءات</Button></div></section>}

function HrScreen(){const actions=[["استلام نتيجة الفحص الطبي","2025/09/22","done"],["إصدار قرار التوظيف النهائي","2025/09/23","done"],["إعداد عقد العمل","2025/09/24","done"],["إشعار الموظف بالنتيجة","قيد التنفيذ","active"],["إضافة الموظف للأنظمة","قيد التنفيذ","active"]] as const;return <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_260px]"><section className="panel p-4"><h2 className="text-sm font-extrabold">إجراءات الموارد البشرية</h2><div className="mt-3">{actions.map(([title,date,state])=><div key={title} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border py-3"><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full ${state==="done"?"bg-success":"bg-primary"} text-primary-foreground`}>{state==="done"?<Check size={13}/>:""}</span><b className="truncate text-[10px]">{title}</b><small className="shrink-0 text-muted-foreground">{date}</small></div>)}</div></section><aside className="panel p-4"><EmployeeCard/><p className="mt-4 text-[9px] text-muted-foreground">حالة الفحص الطبي</p><Status text="مطابق"/><Button variant="outline" className="mt-4 w-full"><FileText/>عرض التقرير الطبي</Button></aside></div>}

function EmployeeScreen(){return <section className="panel mx-auto max-w-2xl p-5"><h2 className="text-sm font-extrabold">نتيجة الفحص الطبي</h2><div className="mt-4 grid place-items-center rounded-md border border-border bg-search p-8 text-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-success text-primary-foreground"><Check size={30}/></span><Status text="مطابق"/><p className="mt-3 max-w-md text-[10px] text-muted-foreground">تم اعتماد نتيجة الفحص الطبي من المركز الطبي المعتمد.</p><InfoRows items={[["تاريخ الفحص","2025/09/22"],["تاريخ اعتماد النتيجة","2025/09/22"]]}/><Button className="mt-4"><Download/>تحميل التقرير الطبي</Button></div></section>}

function TrackingScreen(){return <section className="panel overflow-hidden"><div className="grid gap-3 border-b border-border p-4 sm:grid-cols-[minmax(0,1fr)_auto]"><h2 className="truncate text-sm font-extrabold">متابعة الفحوصات الطبية</h2><select className="h-8 rounded-md border border-input bg-background px-3 text-[10px]"><option>الكل</option><option>مطابق</option><option>غير مطابق</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-right text-[9px]"><thead className="bg-search"><tr>{["الموظف","حالة الفحص","المركز الطبي","تاريخ الفحص","النتيجة","الإجراء"].map(x=><th key={x} className="border-b border-border p-3">{x}</th>)}</tr></thead><tbody>{medicalTrackingRows.map((r,i)=><tr key={r[0]}>{r.map((c,j)=><td key={c} className="border-b border-border p-3">{j===1?<Status text={c}/>:c}</td>)}<td className="border-b border-border p-3"><Button variant="ghost" size="sm">•••</Button></td></tr>)}</tbody></table></div></section>}

function MedicalJourney({active}:{active:number}){return <section className="mt-7"><h2 className="mb-3 text-xs font-extrabold">رحلة الفحص الطبي (من البداية إلى النهاية)</h2><div className="overflow-x-auto rounded-md border border-border bg-card"><div className="flex min-w-[860px] px-5 py-4">{medicalFlowSteps.slice(0,7).map((item,index)=><div key={item.id} className="relative flex flex-1 flex-col items-center text-center after:absolute after:right-[58%] after:top-6 after:h-px after:w-[84%] after:bg-border last:after:hidden"><Link to={medicalPaths[item.id]} className="z-10"><span className={`grid h-12 w-12 place-items-center rounded-full border ${item.number<=active?"border-primary bg-search text-primary":"border-border bg-card text-muted-foreground"}`}><JourneyIcon step={item.id}/></span></Link><b className={`mt-2 text-[9px] ${item.number<=active?"text-primary":"text-muted-foreground"}`}>{item.short}</b><small className="mt-1 text-[8px] text-muted-foreground">{item.subtitle}</small><span className="absolute -top-1 right-[calc(50%+15px)] grid h-4 w-4 place-items-center rounded-full bg-primary text-[7px] text-primary-foreground">{item.number}</span></div>)}</div></div></section>}
function JourneyIcon({step}:{step:string}){const icons:Record<string,typeof Stethoscope>={request:FileText,tests:FlaskConical,center:Stethoscope,result:ClipboardCheck,company:FileText,hr:UserRound,employee:Mail};const Icon=icons[step]??Stethoscope;return <Icon size={21}/>}
function MedicalNavigation({step}:{step:MedicalStepId}){const i=medicalFlowSteps.findIndex(x=>x.id===step);const prev=i>0?medicalFlowSteps[i-1]:undefined;const next=i<medicalFlowSteps.length-1?medicalFlowSteps[i+1]:undefined;return <div className="mt-3 flex justify-between"><div>{prev&&<Button variant="outline" asChild><Link to={medicalPaths[prev.id]}><ArrowRight/>السابق</Link></Button>}</div><div>{next&&<Button asChild><Link to={medicalPaths[next.id]}>التالي<ArrowLeft/></Link></Button>}</div></div>}
function SectionTitle({title}:{title:string}){return <div className="border-b border-border p-4"><h2 className="text-sm font-extrabold">{title}</h2></div>}
function EmployeeCard(){return <div className="rounded-md border border-border bg-search p-3"><div className="flex items-center gap-3"><span className="avatar h-12 w-12 shrink-0">أع</span><div className="min-w-0"><b className="block truncate text-xs">أحمد محمد العتيبي</b><p className="text-[9px] text-muted-foreground">رقم الموظف: #1025</p><p className="text-[9px] text-muted-foreground">الوظيفة: محاسب</p></div></div></div>}
function Field({label,value,icon}:{label:string;value:string;icon?:ReactNode}){return <label className="block text-[10px] font-bold">{label}<div className="mt-1 grid h-9 grid-cols-[minmax(0,1fr)_auto] items-center rounded-md border border-input bg-background px-3 font-normal"><span className="truncate">{value}</span><span className="shrink-0 text-primary">{icon}</span></div></label>}
function InfoRows({items}:{items:readonly (readonly [string,string])[]}){return <div className="mt-3 w-full">{items.map(([k,v])=><div key={k} className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 border-b border-border py-2 text-[9px]"><span className="text-muted-foreground">{k}</span><b>{v}</b></div>)}</div>}
function SuccessLine({children}:{children:ReactNode}){return <div className="flex items-center justify-center gap-2 rounded-md bg-success-soft p-3 text-[9px] font-bold text-success"><CheckCircle2 size={16}/>{children}</div>}
function Status({text}:{text:string}){const danger=text.includes("غير")||text.includes("لم");const waiting=text.includes("قيد");return <span className={`inline-flex rounded-full px-3 py-1 text-[8px] font-bold ${danger?"bg-destructive/10 text-destructive":waiting?"bg-warning-soft text-warning":"bg-success-soft text-success"}`}>{text}</span>}
function ResultSeal(){return <div className="grid place-items-center rounded-md border border-border bg-search p-5 text-center"><div className="medical-seal"><Check size={30}/><b>مطابق</b></div><b className="mt-4 text-xs">ME-2025-4587</b><p className="mt-2 text-[9px] text-muted-foreground">تاريخ الإصدار 2025/09/22</p><p className="text-[9px] text-muted-foreground">صالح حتى 2026/09/22</p></div>}