import { useMemo, useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { committeeApplicants, committeeMembers, recruitmentCommittees } from "@/data/mockData";
import { BriefcaseBusiness, CalendarDays, CheckCircle2, CircleX, ClipboardCheck, Ellipsis, Eye, FileText, Pencil, Plus, Search, Trash2, Users, X } from "lucide-react";

type Committee = (typeof recruitmentCommittees)[number];
type Member = (typeof committeeMembers)[number];
const field = "h-9 w-full min-w-0 rounded border border-input bg-card px-2 text-xs outline-none focus:border-primary";
const statusTone: Record<string,string> = { "نشطة": "bg-success-soft text-success", "مكتملة": "bg-primary-soft text-primary", "مغلقة": "bg-warning-soft text-warning", "قيد المراجعة": "bg-warning-soft text-warning", "مقابلة مجدولة": "bg-primary-soft text-primary", "مرفوض": "bg-destructive/10 text-destructive", "تم الترشيح": "bg-success-soft text-success" };
const stats = [
  { title: "إجمالي اللجان", count: 8, unit: "لجنة توظيف", icon: Users, color: "text-buy-violet", bg: "bg-buy-violet-soft" },
  { title: "الوظائف تحت التوظيف", count: 24, unit: "وظيفة", icon: FileText, color: "text-success", bg: "bg-success-soft" },
  { title: "إجمالي المتقدمين", count: 312, unit: "متقدم", icon: Users, color: "text-primary", bg: "bg-primary-soft" },
  { title: "قيد المراجعة", count: 86, unit: "متقدم", icon: ClipboardCheck, color: "text-warning", bg: "bg-warning-soft" },
  { title: "تم الترشيح", count: 48, unit: "متقدم", icon: CheckCircle2, color: "text-success", bg: "bg-success-soft" },
  { title: "مرفوض", count: 178, unit: "متقدم", icon: CircleX, color: "text-destructive", bg: "bg-destructive/10" },
];
const stages = [["تشكيل اللجنة","2026/10/01"],["فرز الطلبات","2026/10/03"],["المقابلات الشخصية","2026/10/10"],["التقييم وإصدار التوصية",""],["الاعتماد النهائي",""]];
export function RecruitmentCommitteesPage() {
  const [rows, setRows] = useState<Committee[]>(recruitmentCommittees);
  const [selectedId, setSelectedId] = useState(1);
  const [members, setMembers] = useState<Record<number,Member[]>>({ 1: committeeMembers });
  const [query, setQuery] = useState("");
  const [department, setDepartment] = useState("");
  const [status, setStatus] = useState("");
  const [appFilter, setAppFilter] = useState("");
  const [editor, setEditor] = useState<Committee | null>(null);
  const [editing, setEditing] = useState(false);
  const [memberEditor, setMemberEditor] = useState<Member | null>(null);
  const [memberIndex, setMemberIndex] = useState<number | null>(null);
  const [notice, setNotice] = useState("");
  const [applicant, setApplicant] = useState<(typeof committeeApplicants)[number] | null>(null);
  const selected = rows.find(r => r.id === selectedId);
  const visible = useMemo(() => rows.filter(r => (!query || `${r.name} ${r.job}`.includes(query)) && (!department || r.department === department) && (!status || r.status === status)), [rows,query,department,status]);
  const currentMembers = members[selectedId] ?? [];
  const applicants = selectedId === 1 ? committeeApplicants.filter(r => !appFilter || r.status === appFilter) : [];
  function save(e: FormEvent) { e.preventDefault(); if (!editor?.name.trim() || !editor.job.trim() || !editor.department.trim()) return; if (editing) setRows(rows.map(r => r.id === editor.id ? editor : r)); else setRows([editor,...rows]); setSelectedId(editor.id); setNotice(editing ? "تم تعديل اللجنة في هذه الجلسة" : "تمت إضافة اللجنة في هذه الجلسة"); setEditor(null); }
  function saveMember(e: FormEvent) { e.preventDefault(); if (!memberEditor?.name.trim()) return; setMembers(prev => { const list = [...(prev[selectedId] ?? [])]; if (memberIndex === null) list.push(memberEditor); else list[memberIndex] = memberEditor; return {...prev,[selectedId]:list}; }); setMemberEditor(null); setNotice("تم تحديث أعضاء اللجنة في هذه الجلسة"); }
  function closeCommittee() { if (!selected || !window.confirm(`إغلاق «${selected.name}» في هذه الجلسة؟`)) return; setRows(rows.map(r => r.id === selected.id ? {...r,status:"مغلقة"} : r)); setNotice("تم إغلاق اللجنة في هذه الجلسة"); }
  const openNew = () => { setEditing(false); setEditor({ id: Math.max(0,...rows.map(r => r.id))+1, name:"", job:"", department:"", date:new Date().toISOString().slice(0,10).replaceAll("-","/"), status:"نشطة", count:0, description:"" }); };
  return <AppShell><main dir="rtl" className="min-w-0 space-y-3 px-3 py-3 md:px-5"><header><h1 className="text-xl font-extrabold text-buy-navy">لجان التوظيف</h1><p className="text-[11px] text-primary"><Link to="/">الرئيسية</Link> / الموارد البشرية / لجان التوظيف</p></header>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{stats.map((s,i) => <div key={s.title} className="flex min-w-0 items-center justify-between gap-1 rounded border border-border bg-card px-2.5 py-2 shadow-sm"><div className="min-w-0"><p className="text-[10px] font-bold leading-4">{s.title}</p><p className={`text-xl font-extrabold ${s.color}`}>{s.count+(i === 0 ? rows.length-recruitmentCommittees.length : 0)}</p><span className="text-[9px] text-muted-foreground">{s.unit}</span></div><span className={`grid size-10 shrink-0 place-items-center rounded-full ${s.bg} ${s.color}`}><s.icon size={20}/></span></div>)}</div>
    <div className="grid min-w-0 gap-2 xl:grid-cols-[minmax(260px,.7fr)_minmax(0,1.8fr)]"><section className="min-w-0 rounded border border-border bg-card p-3 shadow-sm xl:order-1"><h2 className="mb-3 flex items-center gap-1.5 border-b border-border pb-2 text-sm font-bold"><FileText size={15}/> تفاصيل اللجنة</h2>{selected ? <><dl className="text-xs">{[["اسم اللجنة",selected.name],["الوظيفة المستهدفة",selected.job],["القسم",selected.department],["تاريخ التشكيل",selected.date],["حالة اللجنة",selected.status],["الوصف",selected.description]].map(([key,value]) => <div key={key} className="grid grid-cols-[100px_minmax(0,1fr)] gap-1 border-b border-border py-2"><dt className="text-muted-foreground">{key}</dt><dd className="min-w-0 break-words font-semibold">{value}</dd></div>)}</dl><div className="mt-4 grid grid-cols-2 gap-2"><Button size="sm" className="bg-buy-navy text-primary-foreground" onClick={() => { setEditor({...selected}); setEditing(true); }}><Pencil/> تعديل اللجنة</Button><Button size="sm" variant="outline" className="text-destructive" disabled={selected.status === "مغلقة"} onClick={closeCommittee}><Trash2/> إغلاق اللجنة</Button></div></> : <p className="py-12 text-center text-muted-foreground">اختر لجنة لعرض التفاصيل</p>}</section>
    <section className="min-w-0 xl:order-2"><div className="mb-2 grid gap-1.5 sm:grid-cols-[minmax(0,1fr)_135px_135px_auto]"><label className="relative"><Search size={15} className="absolute right-2 top-2.5 text-primary"/><input className={`${field} pr-8`} aria-label="البحث في لجان التوظيف" placeholder="البحث في لجان التوظيف ..." value={query} onChange={e => setQuery(e.target.value)}/></label><select className={field} aria-label="القسم" value={department} onChange={e => setDepartment(e.target.value)}><option value="">جميع الأقسام</option>{[...new Set(rows.map(r => r.department))].filter(Boolean).map(d => <option key={d}>{d}</option>)}</select><select className={field} aria-label="الحالة" value={status} onChange={e => setStatus(e.target.value)}><option value="">جميع الحالات</option><option>نشطة</option><option>مكتملة</option><option>مغلقة</option></select><Button onClick={openNew} className="bg-buy-navy text-primary-foreground"><Plus/> إضافة لجنة توظيف جديدة</Button></div><div className="max-w-full overflow-x-auto rounded border border-border bg-card shadow-sm"><table className="w-full min-w-[660px] text-right text-[10px]"><thead className="bg-primary-soft/70"><tr>{["م","اسم اللجنة","الوظيفة المستهدفة","القسم","تاريخ التشكيل","حالة اللجنة","عدد المتقدمين","الإجراءات"].map(h => <th key={h} className="whitespace-nowrap px-2 py-2 font-bold">{h}</th>)}</tr></thead><tbody>{visible.map(r => <tr key={r.id} onClick={() => { setSelectedId(r.id); setAppFilter(""); }} className={`cursor-pointer border-t border-border ${selectedId === r.id ? "bg-primary-soft/25" : ""}`}><td className="px-2 py-2">{r.id}</td><td className="whitespace-nowrap px-2 py-2 font-semibold">{r.name}</td><td className="whitespace-nowrap px-2 py-2">{r.job}</td><td className="whitespace-nowrap px-2 py-2">{r.department}</td><td className="whitespace-nowrap px-2 py-2" dir="ltr">{r.date}</td><td className="px-2 py-2"><span className={`rounded px-2 py-0.5 ${statusTone[r.status]}`}>{r.status}</span></td><td className="px-2 py-2">{r.count}</td><td className="px-1"><div className="flex"><Button variant="ghost" size="icon" className="size-6" title="عرض" aria-label={`عرض ${r.name}`} onClick={e => { e.stopPropagation(); setSelectedId(r.id); }}><Eye/></Button><Button variant="ghost" size="icon" className="size-6" title="تعديل" aria-label={`تعديل ${r.name}`} onClick={e => { e.stopPropagation(); setEditor({...r}); setEditing(true); }}><Pencil/></Button><Button variant="ghost" size="icon" className="size-6" title="المزيد" aria-label={`المزيد ${r.name}`} onClick={e => { e.stopPropagation(); setSelectedId(r.id); }}><Ellipsis/></Button></div></td></tr>)}{visible.length === 0 && <tr><td colSpan={8} className="py-10 text-center text-muted-foreground">لا توجد لجان مطابقة</td></tr>}</tbody></table></div></section></div>
    <div className="grid min-w-0 gap-2 xl:grid-cols-[minmax(240px,.8fr)_minmax(0,1.5fr)_minmax(220px,.48fr)]"><section className="min-w-0 rounded border border-border bg-card p-3 shadow-sm xl:order-1"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-1 text-sm font-bold"><Users size={16}/> أعضاء اللجنة</h2><Button variant="outline" size="sm" onClick={() => { setMemberIndex(null); setMemberEditor({name:"",role:"عضو",job:""}); }}><Plus/> إضافة عضو</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[290px] text-right text-[10px]"><thead className="bg-primary-soft/70"><tr>{["م","الاسم","الصفة","المنصب","الإجراءات"].map(h => <th key={h} className="px-1 py-2">{h}</th>)}</tr></thead><tbody>{currentMembers.map((m,i) => <tr key={`${m.name}-${i}`} className="border-t border-border"><td className="px-1 py-2">{i+1}</td><td className="whitespace-nowrap px-1 py-2">{m.name}</td><td className="px-1 py-2">{m.role}</td><td className="whitespace-nowrap px-1 py-2">{m.job}</td><td><div className="flex"><Button variant="ghost" size="icon" className="size-6" title="تعديل" aria-label={`تعديل العضو ${m.name}`} onClick={() => { setMemberIndex(i); setMemberEditor({...m}); }}><Pencil/></Button><Button variant="ghost" size="icon" className="size-6 text-destructive" title="حذف" aria-label={`حذف العضو ${m.name}`} onClick={() => { if (!window.confirm(`حذف ${m.name}؟`)) return; setMembers({...members,[selectedId]:currentMembers.filter((_,j) => i!==j)}); }}><Trash2/></Button></div></td></tr>)}{currentMembers.length === 0 && <tr><td colSpan={5} className="py-10 text-center text-muted-foreground">لا يوجد أعضاء مسجلون لهذه اللجنة</td></tr>}</tbody></table></div></section>
    <section className="min-w-0 rounded border border-border bg-card p-3 shadow-sm xl:order-2"><h2 className="mb-2 flex items-center gap-1 text-sm font-bold"><Users size={16}/> المتقدمون على الوظيفة</h2><div className="mb-2 flex max-w-full gap-1 overflow-x-auto whitespace-nowrap border-b border-border pb-1">{[["","جميع المتقدمين"],["قيد المراجعة","قيد المراجعة"],["مقابلة مجدولة","مقابلة مجدولة"],["تم الترشيح","تم الترشيح"],["مرفوض","مرفوض"]].map(([value,label]) => <Button key={label} variant="ghost" size="sm" className={`shrink-0 text-[10px] ${appFilter === value ? "border-b-2 border-warning text-buy-navy" : "text-muted-foreground"}`} onClick={() => setAppFilter(value)}>{label} ({selectedId === 1 ? value ? committeeApplicants.filter(a => a.status === value).length : selected?.count ?? 0 : 0})</Button>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[450px] text-right text-[10px]"><thead className="bg-primary-soft/70"><tr>{["م","اسم المتقدم","المؤهل","الخبرة","الحالة","تاريخ التقديم","الإجراءات"].map(h => <th key={h} className="whitespace-nowrap px-1 py-2">{h}</th>)}</tr></thead><tbody>{applicants.map((a,i) => <tr key={a.name} className="border-t border-border"><td className="px-1 py-2">{i+1}</td><td className="whitespace-nowrap px-1 py-2">{a.name}</td><td className="px-1 py-2">{a.qualification}</td><td className="whitespace-nowrap px-1 py-2">{a.experience}</td><td className="px-1 py-2"><span className={`whitespace-nowrap rounded px-1.5 py-0.5 ${statusTone[a.status]}`}>{a.status}</span></td><td className="whitespace-nowrap px-1 py-2" dir="ltr">{a.date}</td><td><Button variant="ghost" size="icon" className="size-6" title="عرض التفاصيل" aria-label={`عرض ${a.name}`} onClick={() => setApplicant(a)}><Eye/></Button></td></tr>)}{!applicants.length && <tr><td colSpan={7} className="py-10 text-center text-muted-foreground">لا يوجد متقدمون في هذا العرض</td></tr>}</tbody></table></div></section>
    <section className="min-w-0 rounded border border-border bg-card p-3 shadow-sm xl:order-3"><h2 className="mb-3 flex items-center gap-1 text-sm font-bold"><BriefcaseBusiness size={15}/> مراحل التوظيف</h2><div className="space-y-0">{stages.map(([name,date],i) => <div key={name} className="flex gap-2"><div className="flex flex-col items-center"><span className={`grid size-6 shrink-0 place-items-center rounded-full text-[10px] font-bold text-primary-foreground ${i < 2 ? "bg-primary" : "bg-muted-foreground"}`}>{i < 2 ? "✓" : i+1}</span>{i < stages.length-1 && <span className="h-7 w-px bg-border"/>}</div><div className="text-[10px] font-semibold">{name}<p className="text-[9px] text-muted-foreground">{date}</p></div></div>)}</div></section></div>
    {notice && <p role="status" className="text-xs text-success">{notice}</p>}
    {editor && <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-3" onClick={() => setEditor(null)}><form onClick={e => e.stopPropagation()} onSubmit={save} className="w-full max-w-md space-y-3 rounded border border-border bg-card p-5 shadow-xl"><div className="flex justify-between"><h2 className="font-bold">{editing ? "تعديل اللجنة" : "إضافة لجنة توظيف جديدة"}</h2><Button type="button" variant="ghost" size="icon" aria-label="إغلاق" onClick={() => setEditor(null)}><X/></Button></div>{([ ["name","اسم اللجنة"],["job","الوظيفة المستهدفة"],["department","القسم"] ] as const).map(([key,label]) => <label key={key} className="block text-xs">{label}<input required className={`${field} mt-1`} value={editor[key]} onChange={e => setEditor({...editor,[key]:e.target.value})}/></label>)}<label className="block text-xs">الوصف<textarea className={`${field} mt-1 h-16 p-2`} value={editor.description} onChange={e => setEditor({...editor,description:e.target.value})}/></label><label className="block text-xs">الحالة<select className={`${field} mt-1`} value={editor.status} onChange={e => setEditor({...editor,status:e.target.value})}><option>نشطة</option><option>مكتملة</option><option>مغلقة</option></select></label><Button type="submit" className="w-full">حفظ اللجنة</Button></form></div>}
    {memberEditor && <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-3" onClick={() => setMemberEditor(null)}><form onClick={e => e.stopPropagation()} onSubmit={saveMember} className="w-full max-w-sm space-y-3 rounded border border-border bg-card p-5 shadow-xl"><div className="flex justify-between"><h2 className="font-bold">{memberIndex === null ? "إضافة عضو" : "تعديل عضو"}</h2><Button type="button" variant="ghost" size="icon" aria-label="إغلاق" onClick={() => setMemberEditor(null)}><X/></Button></div>{([ ["name","الاسم"],["role","الصفة"],["job","المنصب"] ] as const).map(([key,label]) => <label key={key} className="block text-xs">{label}<input required className={`${field} mt-1`} value={memberEditor[key]} onChange={e => setMemberEditor({...memberEditor,[key]:e.target.value})}/></label>)}<Button type="submit" className="w-full">حفظ العضو</Button></form></div>}
    {applicant && <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-3" onClick={() => setApplicant(null)}><section onClick={e => e.stopPropagation()} className="w-full max-w-sm space-y-3 rounded border border-border bg-card p-5 shadow-xl"><div className="flex justify-between"><h2 className="font-bold">{applicant.name}</h2><Button variant="ghost" size="icon" aria-label="إغلاق" onClick={() => setApplicant(null)}><X/></Button></div><p>المؤهل: {applicant.qualification}</p><p>الخبرة: {applicant.experience}</p><p>الحالة: {applicant.status}</p><p>تاريخ التقديم: {applicant.date}</p></section></div>}
  </main></AppShell>;
}
