import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Award, Building2, CalendarDays, CheckCircle2, ClipboardList, Clock3, FileText, GraduationCap, History, IdCard, Mail, MapPin, MessageSquareText, Pencil, Phone, RotateCcw, Stethoscope, UserRound, UsersRound, XCircle } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { getRegistrationRequest } from "@/components/registration-requests";
import { Route } from "@/routes/recruitment.requests.$requestId";
import doctorImage from "@/assets/registration-doctor.jpg";
import idCardImage from "@/assets/registration-id-card.jpg";
const tabs = [{label:"البيانات الأساسية",icon:UserRound},{label:"المستندات",icon:FileText},{label:"المؤهلات والخبرات",icon:GraduationCap},{label:"الطلبات السابقة",icon:ClipboardList},{label:"سجل الطلب",icon:History}];
export function RegistrationRequestDetailsPage() {
 const {requestId}=Route.useParams(); const row=getRegistrationRequest(requestId);
 const [tab,setTab]=useState(0); const [action,setAction]=useState(""); const [imageOpen,setImageOpen]=useState(false);
 if (!row) return <AppShell><main dir="rtl" className="p-5"><h1>الطلب غير موجود</h1><Link to="/recruitment/requests">العودة للطلبات</Link></main></AppShell>;
 const contact=[[CalendarDays,"تاريخ الميلاد",row.birth],[UsersRound,"الجنسية",row.nationality],[IdCard,"رقم الهوية",row.identity],[Mail,"البريد الإلكتروني",row.email],[Phone,"رقم الجوال",row.phone]] as const;
 const info=[[UserRound,"الاسم الكامل",row.name],[IdCard,"نوع الحساب المطلوب",row.account],[Stethoscope,"التخصص",row.job.replace("استشاري ","")],[Building2,"الجهة الحالية",row.employer],[Award,"رقم التصنيف المهني",row.classification],[MapPin,"العنوان",row.address]] as const;
 return <AppShell><main dir="rtl" className="registration-details"><div className="registration-details-heading"><div><h1>تفاصيل طلب التسجيل</h1><p>عرض جميع بيانات المستخدم والمستندات المرفقة واتخاذ الإجراء المناسب</p></div><Button asChild variant="secondary" size="sm"><Link to="/recruitment/requests"><ArrowRight className="size-4"/>العودة</Link></Button></div>
 <section className="registration-profile"><div className="registration-profile-top"><div className="registration-profile-status"><span className="inline-flex items-center gap-2 rounded-md bg-warning-soft px-3 py-2 text-warning"><Clock3 className="size-4"/>{action || row.status}</span><p>رقم الطلب: <bdi>#{row.id}</bdi></p><p>تاريخ التسجيل: <bdi>{row.registered}</bdi></p></div><div className="registration-person"><img src={doctorImage} width={512} height={512} alt={row.name}/><div><h2>{row.name}</h2><p>{row.job}</p><div className="mt-3 flex gap-3"><span className="rounded-full bg-primary-soft px-3 py-1 text-primary"><Stethoscope className="inline size-4 ml-2"/>{row.type}</span><span className="rounded-full bg-success-soft px-3 py-1 text-success">{row.nationality} ▪</span></div></div></div></div><div className="registration-contact">{contact.map(([Icon,label,value])=><div key={label}><span><Icon className="size-4"/>{label}</span><bdi>{value}</bdi></div>)}</div></section>
 <nav className="registration-detail-tabs" aria-label="تفاصيل الطلب">{tabs.map(({label,icon:Icon},i)=><Button key={label} variant="ghost" onClick={()=>setTab(i)} className={tab===i?"registration-tab-active":""}><Icon className="size-5"/>{label}</Button>)}</nav>
 <section className="registration-detail-body">{tab===0?<div className="registration-detail-columns"><div className="registration-notes"><section><h2><MessageSquareText className="size-5"/>ملاحظات المستخدم</h2><p>{row.note}</p></section><section><h2><Pencil className="size-5"/>ملاحظات الإدارة</h2><textarea aria-label="ملاحظات الإدارة" placeholder="إضافة ملاحظة داخلية..."/></section></div><dl className="registration-basic-info">{info.map(([Icon,label,value])=><div key={label}><dt><Icon className="size-4"/>{label}</dt><dd>{value}</dd></div>)}</dl><div className="registration-identity"><h2>صورة من الهوية</h2><img src={idCardImage} width={1200} height={760} alt="صورة هوية توضيحية"/><Button variant="outline" size="sm" onClick={()=>setImageOpen(true)}>عرض الصورة</Button></div></div>:tab===1?<div className="p-5"><h2 className="font-bold">المستندات المرفقة</h2><Button variant="outline" className="mt-3" onClick={()=>setImageOpen(true)}><FileText/>صورة الهوية الوطنية</Button></div>:tab===2?<div className="p-5"><h2 className="font-bold">المؤهلات والخبرات</h2><p className="mt-3">{row.job} — {row.employer}</p><p className="mt-2">التصنيف المهني: <bdi>{row.classification}</bdi></p></div>:<div className="p-5"><h2 className="font-bold">{tabs[tab]?.label}</h2><p className="mt-3">{tab===3?"لا توجد طلبات سابقة ضمن البيانات التوضيحية":"تم تقديم طلب التسجيل بتاريخ " + row.registered}</p></div>}</section>
 <div className="registration-detail-actions"><Button variant="secondary" onClick={()=>setAction("إرجاع للتعديل")}><RotateCcw/>إرجاع للتعديل</Button><Button className="bg-success" onClick={()=>setAction("معتمد")}><CheckCircle2/>الموافقة على الطلب</Button><Button variant="destructive" onClick={()=>setAction("مرفوض")}><XCircle/>رفض الطلب</Button></div>{action&&<p role="status" className="mt-2 text-center text-xs text-muted-foreground">{action} — إجراء توضيحي غير محفوظ.</p>}
 {imageOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4" onClick={()=>setImageOpen(false)}><div role="dialog" aria-label="صورة الهوية" className="w-full max-w-2xl rounded-md bg-card p-4" onClick={e=>e.stopPropagation()}><img src={idCardImage} width={1200} height={760} alt="هوية توضيحية وليست مستندًا حقيقيًا" className="w-full"/><Button className="mt-3" onClick={()=>setImageOpen(false)}>إغلاق</Button><p className="mt-2 text-xs text-muted-foreground">مستند توضيحي غير حقيقي</p></div></div>}
 </main></AppShell>;
}
