import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Banknote, CalendarDays, ChevronLeft, ChevronRight, CirclePercent, ClipboardCheck, Download, Ellipsis, Eye, FileSpreadsheet, HandCoins, Plus, Printer, Search, Users, Wallet, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { salaryRunEmployees } from "@/data/mockData";
import employeePhoto from "@/assets/candidate-ahmed.jpg";

const format = (value: number) => value.toLocaleString("en-US");
const months = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"];
const tabs = ["قائمة الموظفين", "تفاصيل المسير", "البدلات", "الخصومات", "الاستقطاعات", "الاعتمادات والموافقات"] as const;
type Tab = typeof tabs[number];
type Employee = (typeof salaryRunEmployees)[number];
const control = "h-9 min-w-0 rounded border border-input bg-card px-3 text-[11px] font-semibold text-buy-navy outline-none focus:border-primary";
const panel = "min-w-0 rounded border border-border bg-card shadow-sm";
const cards = [
  { label: "صافي الرواتب", number: "1,990,000", color: "text-primary", bg: "bg-primary-soft", Icon: Wallet },
  { label: "إجمالي الخصومات", number: "180,000", color: "text-destructive", bg: "bg-destructive/10", Icon: CirclePercent },
  { label: "إجمالي البدلات", number: "320,000", color: "text-warning", bg: "bg-warning-soft", Icon: HandCoins },
  { label: "إجمالي الرواتب الأساسية", number: "1,850,000", color: "text-success", bg: "bg-success-soft", Icon: Banknote },
  { label: "إجمالي الموظفين", number: "312", color: "text-primary", bg: "bg-primary-soft", Icon: Users },
];
const departmentShares = [
  { name: "الخدمات الطبية", value: 28, color: "var(--primary)" },
  { name: "الإدارة", value: 18, color: "var(--success)" },
  { name: "المالية", value: 14, color: "var(--chart-4)" },
  { name: "تقنية المعلومات", value: 12, color: "var(--destructive)" },
  { name: "خدمة العملاء", value: 10, color: "var(--buy-violet)" },
  { name: "أخرى", value: 18, color: "var(--muted-foreground)" },
];
const yearly = [350, 620, 550, 1020, 890, 1400, 1580, 1400, 1640, 1620, 1840, 2140];
function Donut() {
  let running = 0;
  const colors = departmentShares.map(s => {const start=running; running+=s.value; return `${s.color} ${start}% ${running}%`;}).join(", ");
  return <div className="relative size-32 shrink-0 rounded-full" style={{background: `conic-gradient(${colors})`}}><div className="absolute inset-6 flex flex-col items-center justify-center rounded-full bg-card text-center text-buy-navy"><strong className="text-sm">1,990,000</strong><span className="text-[10px]">ريال</span></div></div>;
}
function AnnualChart({year}: {year:number}) {
  const values = yearly.map(v => year === 2026 ? v : Math.round(v * .87));
  const coords = values.map((v,i) => `${40+i*36},${152-v/2500*128}`).join(" ");
  return <div dir="ltr" className="h-36 w-full"><svg viewBox="0 0 456 183" preserveAspectRatio="none" className="h-full w-full" role="img" aria-label={`مجموع الرواتب خلال سنة ${year}`}><defs><linearGradient id="salaryRunFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="var(--primary)" stopOpacity=".26"/><stop offset="1" stopColor="var(--primary)" stopOpacity=".02"/></linearGradient></defs>{[0,500,1000,1500,2000,2500].map(v => <g key={v}><line x1="40" x2="444" y1={152-v/2500*128} y2={152-v/2500*128} stroke="var(--border)" strokeWidth=".8"/><text x="36" y={155-v/2500*128} textAnchor="end" fill="var(--muted-foreground)" fontSize="8">{v===0?"0":`${(v/1000).toFixed(1)}M`}</text></g>)}<polygon points={`40,152 ${coords} 436,152`} fill="url(#salaryRunFill)"/><polyline points={coords} fill="none" stroke="var(--primary)" strokeWidth="2"/>{values.map((v,i)=><circle key={i} cx={40+i*36} cy={152-v/2500*128} r="3" fill="var(--primary)"/>)}{months.map((m,i)=><text key={m} x={40+i*36} y="175" textAnchor="middle" fill="var(--foreground)" fontSize="8">{m.slice(0,4)}</text>)}</svg></div>;
}
function Badge({status}: {status:string}) {return <span className={`inline-block min-w-14 rounded px-2 py-1 text-center text-[10px] font-bold ${status === "مكتمل" ? "bg-success-soft text-success" : status === "معلق" ? "bg-destructive/10 text-destructive" : "bg-warning-soft text-warning"}`}>{status}</span>}

export function SalaryRuns() {
  const [kind,setKind] = useState(""); const [department,setDepartment] = useState("");
  const [month,setMonth] = useState(9); const [year,setYear] = useState(2026); const [chartYear,setChartYear] = useState(2026);
  const [search,setSearch] = useState(""); const [page,setPage] = useState(1); const [limit,setLimit] = useState(10);
  const [selectedId,setSelectedId] = useState("EMP-001"); const [activeTab,setActiveTab] = useState<Tab>(tabs[0]);
  const [statuses,setStatuses] = useState<Record<string,string>>({}); const [menu,setMenu] = useState<string | null>(null);
  const [createOpen,setCreateOpen] = useState(false); const [created,setCreated] = useState(false); const [message,setMessage] = useState("");
  const selected = salaryRunEmployees.find(e=>e.id===selectedId) ?? salaryRunEmployees[0];
  const depts = [...new Set(salaryRunEmployees.map(e=>e.department))];
  const filtered = useMemo(()=>salaryRunEmployees.filter(e=>(!kind||kind===e.kind)&&(!department||department===e.department)&&(!search||`${e.id} ${e.name} ${e.job}`.toLowerCase().includes(search.trim().toLowerCase()))),[kind,department,search]);
  const pages=Math.max(1,Math.ceil(filtered.length/limit)); const safePage=Math.min(page,pages); const visible=filtered.slice((safePage-1)*limit,safePage*limit);
  const choose=(setter:(value:string)=>void,value:string)=>{setter(value);setPage(1)};
  const csv=()=>{const data=[["رقم الموظف","اسم الموظف","القسم","الوظيفة","الراتب الأساسي","البدلات","الخصومات","صافي الراتب","الحالة"],...filtered.map(e=>[e.id,e.name,e.department,e.job,e.base,e.allowances,e.deductions,e.base+e.allowances-e.deductions,statuses[e.id]??e.status])]; const text="\uFEFF"+data.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\r\n"); const url=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`مسير-الرواتب-${year}-${month+1}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const showTab=()=>{
    if(activeTab==="قائمة الموظفين") return <div className="overflow-x-auto"><table className="w-full min-w-[765px] border-collapse text-right text-[10px] text-buy-navy"><thead className="bg-primary-soft"><tr>{["م","رقم الموظف","اسم الموظف","القسم","القسم","الوظيفة","الراتب الأساسي","البدلات","الخصومات","صافي الراتب","الحالة","إجراء"].map((h,i)=><th key={i} className="whitespace-nowrap border border-border px-1.5 py-2 font-bold">{h}</th>)}</tr></thead><tbody>{visible.map((e,i)=><tr key={e.id} onClick={()=>setSelectedId(e.id)} className={`cursor-pointer hover:bg-primary-soft/50 ${selectedId===e.id?"bg-primary-soft/25":""}`}><td className="border border-border px-1.5 py-1.5">{(safePage-1)*limit+i+1}</td><td dir="ltr" className="border border-border px-1.5 py-1.5">{e.id}</td><td className="whitespace-nowrap border border-border px-1.5 py-1.5 font-bold">{e.name}</td><td className="whitespace-nowrap border border-border px-1.5 py-1.5">{e.department}</td><td className="whitespace-nowrap border border-border px-1.5 py-1.5">{e.section}</td><td className="whitespace-nowrap border border-border px-1.5 py-1.5">{e.job}</td><td className="border border-border px-1.5 py-1.5">{format(e.base)}</td><td className="border border-border px-1.5 py-1.5">{format(e.allowances)}</td><td className="border border-border px-1.5 py-1.5">{format(e.deductions)}</td><td className="border border-border px-1.5 py-1.5 font-bold text-success">{format(e.base+e.allowances-e.deductions)}</td><td className="border border-border px-1.5 py-1.5"><Badge status={statuses[e.id]??e.status}/></td><td className="border border-border px-1 py-1"><div className="flex items-center gap-0.5"><Button size="icon" variant="ghost" className="size-6" title="عرض التفاصيل" aria-label={`عرض ${e.name}`} onClick={event=>{event.stopPropagation();setSelectedId(e.id);setActiveTab("تفاصيل المسير")}}><Eye size={13}/></Button><div className="relative"><Button size="icon" variant="ghost" className="size-6" title="إجراءات" aria-label={`إجراءات ${e.name}`} onClick={event=>{event.stopPropagation();setMenu(menu===e.id?null:e.id)}}><Ellipsis size={13}/></Button>{menu===e.id&&<div className="absolute left-0 top-7 z-20 w-28 rounded border border-border bg-card p-1 shadow-lg">{["مكتمل","مراجعة","معلق"].map(s=><Button key={s} variant="ghost" className="h-7 w-full justify-start text-[10px]" onClick={event=>{event.stopPropagation();setStatuses(old=>({...old,[e.id]:s}));setMessage("تم تغيير الحالة في العرض التجريبي فقط، ولم يحدث صرف أو اعتماد فعلي.");setMenu(null)}}>{s}</Button>)}</div>}</div></div></td></tr>)}</tbody></table>{!visible.length&&<p className="p-8 text-center text-xs text-muted-foreground">لا توجد نتائج تطابق البحث.</p>}</div>;
    if(activeTab==="تفاصيل المسير") return <div className="grid gap-3 p-4 sm:grid-cols-2">{[["الموظف",selected.name],["الشهر",`${months[month]} ${year}`],["القسم",selected.department],["الراتب الأساسي",`${format(selected.base)} ريال`],["إجمالي البدلات",`${format(selected.allowances)} ريال`],["إجمالي الخصومات",`${format(selected.deductions)} ريال`],["صافي الراتب",`${format(selected.base+selected.allowances-selected.deductions)} ريال`],["الحالة",statuses[selected.id]??selected.status]].map(([k,v])=><div key={k} className="flex justify-between gap-2 border-b border-border py-2 text-xs"><span className="text-muted-foreground">{k}</span><b>{v}</b></div>)}</div>;
    if(activeTab==="البدلات"||activeTab==="الخصومات"||activeTab==="الاستقطاعات") return <div className="p-4 text-xs"><h3 className="mb-3 font-bold">{activeTab} — {selected.name}</h3>{(activeTab==="البدلات" ? [["بدل سكن",Math.round(selected.allowances*.6)],["بدل نقل",Math.round(selected.allowances*.2)],["بدل طبي",Math.round(selected.allowances*.2)]] : activeTab==="الخصومات" ? [["التأمينات الاجتماعية",Math.round(selected.deductions*.57)],["ضريبة الدخل",Math.round(selected.deductions*.29)],["أخرى",selected.deductions-Math.round(selected.deductions*.57)-Math.round(selected.deductions*.29)]] : [["إجمالي الاستقطاعات",selected.deductions]]).map(([k,v])=><div key={k} className="flex justify-between border-b border-border py-2"><span>{k}</span><b>{format(Number(v))} ريال</b></div>)}</div>;
    return <div className="p-4 text-xs"><h3 className="font-bold">الاعتمادات والموافقات</h3><p className="mt-2 text-muted-foreground">حالة المسير للموظف {selected.name}: <Badge status={statuses[selected.id]??selected.status}/></p><p className="mt-3 text-muted-foreground">هذه الموافقات للعرض التجريبي فقط؛ لا يتم اعتماد أو صرف أي رواتب.</p></div>;
  };
  return <AppShell><main dir="rtl" className="min-w-0 space-y-2 bg-background p-3 text-buy-navy md:p-4" id="salary-runs">
    <div className="grid grid-cols-[minmax(0,1fr)] gap-2 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div className="min-w-0"><h1 className="text-xl font-black">مسيرات الرواتب</h1><nav aria-label="مسار الصفحة" className="flex gap-1 text-[10px] text-muted-foreground"><Link to="/">الرئيسية</Link><span>/</span><Link to="/hr">الموارد البشرية</Link><span>/</span>مسيرات الرواتب</nav></div><div className="flex min-w-0 flex-wrap items-center gap-2 lg:row-start-1 lg:col-start-1"><select aria-label="نوع الموظف" value={kind} onChange={e=>choose(setKind,e.target.value)} className={`${control} flex-1 lg:w-36 lg:flex-none`}><option value="">جميع أنواع الموظفين</option><option>سعودي</option><option>غير سعودي</option></select><select aria-label="القسم" value={department} onChange={e=>choose(setDepartment,e.target.value)} className={`${control} flex-1 lg:w-36 lg:flex-none`}><option value="">جميع الأقسام</option>{depts.map(d=><option key={d}>{d}</option>)}</select><select aria-label="الشهر" value={month} onChange={e=>setMonth(Number(e.target.value))} className={`${control} flex-1 lg:w-28 lg:flex-none`}>{months.map((m,i)=><option value={i} key={m}>{m}</option>)}</select><select aria-label="السنة" value={year} onChange={e=>setYear(Number(e.target.value))} className={`${control} flex-1 lg:w-24 lg:flex-none`}><option>2026</option><option>2025</option></select><Button className="h-9 bg-buy-navy text-buy-gold hover:bg-buy-navy/90" onClick={()=>setCreateOpen(true)}><Plus size={14}/>إنشاء مسير راتب</Button></div></div>
    {message&&<p role="status" className="rounded border border-success bg-success-soft p-2 text-xs text-success">{message}</p>}
    <section aria-label="مؤشرات مسير الرواتب" className="grid grid-cols-2 gap-2 lg:grid-cols-3 xl:grid-cols-5">{cards.map(({label,number,color,bg,Icon})=><div key={label} className={`${panel} flex min-h-18 items-center justify-between gap-2 px-3 py-2`}><div className="min-w-0"><h2 className="text-[10px] font-bold">{label}</h2><strong className={`block text-lg leading-snug font-black ${color}`}>{number}</strong><span className="text-[10px]">{label==="إجمالي الموظفين"?"موظف":"ريال"}</span></div><span className={`grid size-11 shrink-0 place-items-center rounded-full ${bg} ${color}`}><Icon size={22}/></span></div>)}</section>
    <section aria-label="تحليلات الرواتب" className="grid min-w-0 gap-2 xl:grid-cols-[1fr_1.13fr_1.55fr]"><div className={`${panel} p-3`}><h2 className="mb-2 text-sm font-extrabold">نسبة الاستقطاع</h2><div className="relative mx-auto mt-1 h-31 w-36 overflow-hidden"><div className="absolute left-1/2 top-1 size-30 -translate-x-1/2 rounded-full" style={{background:"conic-gradient(var(--buy-navy) 0 8.3%, var(--primary-soft) 8.3% 100%)"}}/><div className="absolute left-1/2 top-5 size-22 -translate-x-1/2 rounded-full bg-card"/><div className="absolute bottom-0 h-1/2 w-full bg-card"/><div className="absolute inset-x-0 bottom-3 text-center"><strong className="block text-lg font-black">8.3%</strong><span className="text-[10px]">من إجمالي الرواتب</span></div></div><div className="grid grid-cols-2 gap-1 text-center text-[10px]"><div className="rounded bg-success-soft p-2 text-success"><b className="block text-sm">1,990,000</b>صافي الرواتب</div><div className="rounded bg-destructive/10 p-2 text-destructive"><b className="block text-sm">180,000</b>إجمالي الخصومات</div></div></div>
      <div className={`${panel} p-3`}><h2 className="mb-3 text-sm font-extrabold">توزيع الرواتب حسب الأقسام</h2><div className="flex flex-wrap items-center justify-center gap-3"><ul className="min-w-35 flex-1 space-y-1 text-[10px]">{departmentShares.map(s=><li key={s.name} className="flex items-center gap-2"><span className="size-2 shrink-0 rounded-full" style={{background:s.color}}/>{s.name}<b className="mr-auto">{s.value}%</b></li>)}</ul><Donut/></div></div>
      <div className={`${panel} p-3`}><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2"><h2 className="min-w-0 text-sm font-extrabold">مجموع الرواتب خلال السنة</h2><select aria-label="سنة الرسم البياني" value={chartYear} onChange={e=>setChartYear(Number(e.target.value))} className={`${control} w-21`}><option>2026</option><option>2025</option></select></div><div className="mt-3"><AnnualChart year={chartYear}/></div></div></section>
    <section className="grid min-w-0 items-start gap-2 xl:grid-cols-[185px_minmax(0,1fr)]"><aside className={`${panel} p-2.5 xl:row-start-1`}><div className="flex items-center justify-between gap-1 border-b border-border pb-2"><h2 className="text-[11px] font-extrabold">تفاصيل مسير راتب</h2><Button size="icon" variant="ghost" title="طباعة التفاصيل" aria-label="طباعة التفاصيل" className="size-7" onClick={()=>window.print()}><Printer size={14}/></Button></div><div className="flex flex-col items-center border-b border-border py-2 text-center"><img src={employeePhoto} alt="صورة توضيحية للموظف" className="size-13 rounded-full object-cover"/><strong className="text-[11px]">{selected.name}</strong><span className="text-[9px]">{selected.job}</span><span className="text-[9px]">{selected.department}</span><span className="rounded bg-primary-soft px-2 text-[9px]" dir="ltr">{selected.id}</span></div><div className="flex items-center justify-between border-b border-border py-1 text-[10px]"><b>تفاصيل الراتب</b><span className="inline-flex items-center gap-1"><CalendarDays size={11}/>{months[month]} {year}</span></div><dl className="text-[10px]">{[["الراتب الأساسي",selected.base],["بدل سكن",Math.round(selected.allowances*.6)],["بدل نقل",Math.round(selected.allowances*.2)],["بدل تخصص",Math.round(selected.allowances*.2)],["إجمالي البدلات",selected.allowances],["إجمالي الراتب المستحق",selected.base+selected.allowances],["التأمينات الاجتماعية",Math.round(selected.deductions*.57)],["ضريبة الدخل",Math.round(selected.deductions*.29)],["أخرى",selected.deductions-Math.round(selected.deductions*.57)-Math.round(selected.deductions*.29)],["إجمالي الخصومات",selected.deductions]].map(([k,v],i)=><div key={k} className={`flex justify-between gap-2 px-1 py-1 ${i===4||i===5||i===9?"bg-primary-soft font-bold":""}`}><dt>{k}</dt><dd>{format(Number(v))}</dd></div>)}<div className="flex justify-between rounded bg-warning-soft px-2 py-2 font-extrabold"><dt>صافي الراتب</dt><dd>{format(selected.base+selected.allowances-selected.deductions)}</dd></div></dl></aside>
    <div className={`${panel} min-w-0 overflow-hidden xl:col-start-2 xl:row-start-1`}><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-2 pt-1"><div role="tablist" aria-label="بيانات مسير الرواتب" className="flex min-w-0 max-w-full overflow-x-auto">{tabs.map(t=><Button key={t} role="tab" aria-selected={activeTab===t} variant="ghost" onClick={()=>setActiveTab(t)} className={`h-8 shrink-0 rounded-none px-2 text-[10px] ${activeTab===t?"border-b-2 border-warning font-bold text-buy-navy":"text-muted-foreground"}`}>{t}</Button>)}</div><div className="flex items-center gap-1 pb-1"><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>window.print()}><Printer size={12}/>طباعة</Button><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={csv}><FileSpreadsheet size={12}/>تصدير</Button><Button variant="outline" size="icon" className="size-7" title="المزيد" aria-label="خيارات إضافية" onClick={()=>setMessage("التصدير والطباعة متاحان من الأزرار المجاورة؛ لا يوجد صرف فعلي.")}><Ellipsis size={14}/></Button></div></div>{showTab()}
      <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border px-2 py-2 text-[10px]"><p>عرض {filtered.length?(safePage-1)*limit+1:0} إلى {Math.min(safePage*limit,filtered.length)} من {filtered.length} نتيجة تجريبية</p><div className="flex items-center gap-1"><Button variant="outline" size="icon" className="size-7" aria-label="الصفحة السابقة" disabled={safePage===1} onClick={()=>setPage(safePage-1)}><ChevronRight size={12}/></Button>{Array.from({length:pages},(_,i)=><Button key={i} variant={safePage===i+1?"default":"outline"} size="icon" className="size-7" aria-label={`صفحة ${i+1}`} onClick={()=>setPage(i+1)}>{i+1}</Button>)}<Button variant="outline" size="icon" className="size-7" aria-label="الصفحة التالية" disabled={safePage===pages} onClick={()=>setPage(safePage+1)}><ChevronLeft size={12}/></Button></div><label className="flex items-center gap-1">إظهار <select aria-label="عدد النتائج" className={`${control} h-7 w-15`} value={limit} onChange={e=>{setLimit(Number(e.target.value));setPage(1)}}><option>10</option><option>20</option></select></label></div>
      <div className="border-t border-border p-2"><label className="relative block max-w-70"><span className="sr-only">البحث في المسير</span><Search size={13} className="absolute right-2 top-2.5 text-primary"/><input aria-label="البحث في المسير" value={search} onChange={e=>choose(setSearch,e.target.value)} placeholder="البحث عن موظف في المسير..." className={`${control} w-full pr-7`}/></label></div></div></section>
    <p className="text-[10px] text-muted-foreground">الأرقام الإجمالية في المؤشرات مرجعية، وسجلات الموظفين المعروضة بيانات تجريبية. لا يوجد صرف أو اعتماد فعلي.</p>
    {createOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4" onClick={()=>setCreateOpen(false)}><div role="dialog" aria-modal="true" aria-label="إنشاء مسير راتب" className="w-full max-w-md rounded border border-border bg-card p-4 shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-bold">إنشاء مسير راتب — {months[month]} {year}</h2><Button variant="ghost" size="icon" aria-label="إغلاق" onClick={()=>setCreateOpen(false)}><X size={16}/></Button></div><p className="my-3 text-xs text-muted-foreground">هذه معاينة تجريبية لـ {filtered.length} موظفًا. لن يتم صرف أو اعتماد أي راتب، ولن تُحفظ البيانات بعد تحديث الصفحة.</p><div className="flex justify-between border-y border-border py-2 text-sm"><span>صافي رواتب الموظفين المعروضين</span><b>{format(filtered.reduce((sum,e)=>sum+e.base+e.allowances-e.deductions,0))} ريال</b></div>{created&&<p className="mt-2 text-xs text-success">تم إعداد المسير التجريبي في هذه الجلسة.</p>}<Button className="mt-4 w-full" onClick={()=>{setCreated(true);setCreateOpen(false);setMessage("تم إعداد مسير تجريبي محليًا دون حفظ أو صرف فعلي.")}}><ClipboardCheck size={14}/>إنشاء مسير تجريبي</Button></div></div>}
  </main></AppShell>;
}
