/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SelfServiceRouteImport } from './routes/self-service'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as AttendanceCheckInRouteImport } from './routes/attendance.check-in'
import { Route as AttendancePenaltiesRouteImport } from './routes/attendance.penalties'
import { Route as AttendancePermissionRouteImport } from './routes/attendance.permission'
import { Route as CustomerServiceIndexRouteImport } from './routes/customer-service.index'
import { Route as CustomerServiceInboxRouteImport } from './routes/customer-service.inbox'
import { Route as EmployeesAdminLetterRouteImport } from './routes/employees.admin-letter'
import { Route as EmployeesCustodyRouteImport } from './routes/employees.custody'
import { Route as EmployeesDepartmentRouteImport } from './routes/employees.department'
import { Route as EmployeesDocumentsRouteImport } from './routes/employees.documents'
import { Route as EmployeesEndOfServiceRouteImport } from './routes/employees.end-of-service'
import { Route as EmployeesFinancialLetterRouteImport } from './routes/employees.financial-letter'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as EmployeesProfileRouteImport } from './routes/employees.profile'
import { Route as EmployeesPromotionRouteImport } from './routes/employees.promotion'
import { Route as EmployeesTransferRouteImport } from './routes/employees.transfer'
import { Route as FinanceBankMovementsRouteImport } from './routes/finance_.bank-movements'
import { Route as FinanceBanksRouteImport } from './routes/finance_.banks'
import { Route as FinanceCashFlowRouteImport } from './routes/finance_.cash-flow'
import { Route as FinanceInvoiceInputsRouteImport } from './routes/finance_.invoice-inputs'
import { Route as FinanceMoneyFlowRouteImport } from './routes/finance_.money-flow'
import { Route as FinanceMonthCloseRouteImport } from './routes/finance_.month-close'
import { Route as FinancePaymentOrdersRouteImport } from './routes/finance_.payment-orders'
import { Route as FinanceReceiptsRouteImport } from './routes/finance_.receipts'
import { Route as FinanceRecurringRouteImport } from './routes/finance_.recurring'
import { Route as LeavesNewRouteImport } from './routes/leaves.new'
import { Route as MedicalExamCenterRouteImport } from './routes/medical-exam.center'
import { Route as MedicalExamCompanyRouteImport } from './routes/medical-exam.company'
import { Route as MedicalExamDashboardRouteImport } from './routes/medical-exam.dashboard'
import { Route as MedicalExamEmployeeRouteImport } from './routes/medical-exam.employee'
import { Route as MedicalExamHrRouteImport } from './routes/medical-exam.hr'
import { Route as MedicalExamRequestRouteImport } from './routes/medical-exam.request'
import { Route as MedicalExamResultRouteImport } from './routes/medical-exam.result'
import { Route as MedicalExamTestsRouteImport } from './routes/medical-exam.tests'
import { Route as MedicalExamTrackingRouteImport } from './routes/medical-exam.tracking'
import { Route as PerformanceCommitteeRouteImport } from './routes/performance.committee'
import { Route as PerformanceCriteriaRouteImport } from './routes/performance.criteria'
import { Route as PerformanceEvaluationRouteImport } from './routes/performance.evaluation'
import { Route as PerformanceResultsRouteImport } from './routes/performance.results'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as RecruitmentAppointmentRouteImport } from './routes/recruitment.appointment'
import { Route as RecruitmentDecisionRouteImport } from './routes/recruitment.decision'
import { Route as RecruitmentEvaluationRouteImport } from './routes/recruitment.evaluation'
import { Route as RecruitmentJobPostingRouteImport } from './routes/recruitment.job-posting'
import { Route as RecruitmentMedicalRouteImport } from './routes/recruitment.medical'
import { Route as RecruitmentOfferRouteImport } from './routes/recruitment.offer'
import { Route as RecruitmentRegistrationRouteImport } from './routes/recruitment.registration'
import { Route as RecruitmentReportsRouteImport } from './routes/recruitment.reports'
import { Route as RecruitmentRequestsRouteImport } from './routes/recruitment.requests'
import { Route as RecruitmentScreeningRouteImport } from './routes/recruitment.screening'
import { Route as RecruitmentTrackingRouteImport } from './routes/recruitment.tracking'
import { Route as ReportsFinancialRouteImport } from './routes/reports.financial'
import { Route as RequestsTrackingRouteImport } from './routes/requests.tracking'
import { Route as RewardsIssueRouteImport } from './routes/rewards.issue'
import { Route as SalariesAdvancesRouteImport } from './routes/salaries.advances'
import { Route as SalaryPlacementConfirmRouteImport } from './routes/salary-placement.confirm'
import { Route as SalaryPlacementDecisionRouteImport } from './routes/salary-placement.decision'
import { Route as SalaryPlacementMatchRouteImport } from './routes/salary-placement.match'
import { Route as SalaryPlacementProfileRouteImport } from './routes/salary-placement.profile'
import { Route as SalaryPlacementPullRouteImport } from './routes/salary-placement.pull'
import { Route as SalaryPlacementSelectRouteImport } from './routes/salary-placement.select'
import { Route as SalesInvoiceRouteImport } from './routes/sales_.invoice'
import { Route as SalesNewRouteImport } from './routes/sales_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfServiceRoute = SelfServiceRouteImport.update({
  id: '/self-service',
  path: '/self-service',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceCheckInRoute = AttendanceCheckInRouteImport.update({
  id: '/attendance/check-in',
  path: '/attendance/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendancePenaltiesRoute = AttendancePenaltiesRouteImport.update({
  id: '/attendance/penalties',
  path: '/attendance/penalties',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendancePermissionRoute = AttendancePermissionRouteImport.update({
  id: '/attendance/permission',
  path: '/attendance/permission',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceIndexRoute = CustomerServiceIndexRouteImport.update({
  id: '/customer-service/',
  path: '/customer-service/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceInboxRoute = CustomerServiceInboxRouteImport.update({
  id: '/customer-service/inbox',
  path: '/customer-service/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesAdminLetterRoute = EmployeesAdminLetterRouteImport.update({
  id: '/employees/admin-letter',
  path: '/employees/admin-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesCustodyRoute = EmployeesCustodyRouteImport.update({
  id: '/employees/custody',
  path: '/employees/custody',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesDepartmentRoute = EmployeesDepartmentRouteImport.update({
  id: '/employees/department',
  path: '/employees/department',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesDocumentsRoute = EmployeesDocumentsRouteImport.update({
  id: '/employees/documents',
  path: '/employees/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEndOfServiceRoute = EmployeesEndOfServiceRouteImport.update({
  id: '/employees/end-of-service',
  path: '/employees/end-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesFinancialLetterRoute =
  EmployeesFinancialLetterRouteImport.update({
    id: '/employees/financial-letter',
    path: '/employees/financial-letter',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesProfileRoute = EmployeesProfileRouteImport.update({
  id: '/employees/profile',
  path: '/employees/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesPromotionRoute = EmployeesPromotionRouteImport.update({
  id: '/employees/promotion',
  path: '/employees/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesTransferRoute = EmployeesTransferRouteImport.update({
  id: '/employees/transfer',
  path: '/employees/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBankMovementsRoute = FinanceBankMovementsRouteImport.update({
  id: '/finance_/bank-movements',
  path: '/finance/bank-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBanksRoute = FinanceBanksRouteImport.update({
  id: '/finance_/banks',
  path: '/finance/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCashFlowRoute = FinanceCashFlowRouteImport.update({
  id: '/finance_/cash-flow',
  path: '/finance/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoiceInputsRoute = FinanceInvoiceInputsRouteImport.update({
  id: '/finance_/invoice-inputs',
  path: '/finance/invoice-inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceMoneyFlowRoute = FinanceMoneyFlowRouteImport.update({
  id: '/finance_/money-flow',
  path: '/finance/money-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceMonthCloseRoute = FinanceMonthCloseRouteImport.update({
  id: '/finance_/month-close',
  path: '/finance/month-close',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentOrdersRoute = FinancePaymentOrdersRouteImport.update({
  id: '/finance_/payment-orders',
  path: '/finance/payment-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReceiptsRoute = FinanceReceiptsRouteImport.update({
  id: '/finance_/receipts',
  path: '/finance/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRecurringRoute = FinanceRecurringRouteImport.update({
  id: '/finance_/recurring',
  path: '/finance/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesNewRoute = LeavesNewRouteImport.update({
  id: '/leaves/new',
  path: '/leaves/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamCenterRoute = MedicalExamCenterRouteImport.update({
  id: '/medical-exam/center',
  path: '/medical-exam/center',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamCompanyRoute = MedicalExamCompanyRouteImport.update({
  id: '/medical-exam/company',
  path: '/medical-exam/company',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamDashboardRoute = MedicalExamDashboardRouteImport.update({
  id: '/medical-exam/dashboard',
  path: '/medical-exam/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamEmployeeRoute = MedicalExamEmployeeRouteImport.update({
  id: '/medical-exam/employee',
  path: '/medical-exam/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamHrRoute = MedicalExamHrRouteImport.update({
  id: '/medical-exam/hr',
  path: '/medical-exam/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamRequestRoute = MedicalExamRequestRouteImport.update({
  id: '/medical-exam/request',
  path: '/medical-exam/request',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamResultRoute = MedicalExamResultRouteImport.update({
  id: '/medical-exam/result',
  path: '/medical-exam/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamTestsRoute = MedicalExamTestsRouteImport.update({
  id: '/medical-exam/tests',
  path: '/medical-exam/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamTrackingRoute = MedicalExamTrackingRouteImport.update({
  id: '/medical-exam/tracking',
  path: '/medical-exam/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceCommitteeRoute = PerformanceCommitteeRouteImport.update({
  id: '/performance/committee',
  path: '/performance/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceCriteriaRoute = PerformanceCriteriaRouteImport.update({
  id: '/performance/criteria',
  path: '/performance/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceEvaluationRoute = PerformanceEvaluationRouteImport.update({
  id: '/performance/evaluation',
  path: '/performance/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceResultsRoute = PerformanceResultsRouteImport.update({
  id: '/performance/results',
  path: '/performance/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentAppointmentRoute = RecruitmentAppointmentRouteImport.update({
  id: '/recruitment/appointment',
  path: '/recruitment/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentDecisionRoute = RecruitmentDecisionRouteImport.update({
  id: '/recruitment/decision',
  path: '/recruitment/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentEvaluationRoute = RecruitmentEvaluationRouteImport.update({
  id: '/recruitment/evaluation',
  path: '/recruitment/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentJobPostingRoute = RecruitmentJobPostingRouteImport.update({
  id: '/recruitment/job-posting',
  path: '/recruitment/job-posting',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentMedicalRoute = RecruitmentMedicalRouteImport.update({
  id: '/recruitment/medical',
  path: '/recruitment/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentOfferRoute = RecruitmentOfferRouteImport.update({
  id: '/recruitment/offer',
  path: '/recruitment/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRegistrationRoute = RecruitmentRegistrationRouteImport.update({
  id: '/recruitment/registration',
  path: '/recruitment/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentReportsRoute = RecruitmentReportsRouteImport.update({
  id: '/recruitment/reports',
  path: '/recruitment/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRequestsRoute = RecruitmentRequestsRouteImport.update({
  id: '/recruitment/requests',
  path: '/recruitment/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentScreeningRoute = RecruitmentScreeningRouteImport.update({
  id: '/recruitment/screening',
  path: '/recruitment/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentTrackingRoute = RecruitmentTrackingRouteImport.update({
  id: '/recruitment/tracking',
  path: '/recruitment/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFinancialRoute = ReportsFinancialRouteImport.update({
  id: '/reports/financial',
  path: '/reports/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsTrackingRoute = RequestsTrackingRouteImport.update({
  id: '/requests/tracking',
  path: '/requests/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsIssueRoute = RewardsIssueRouteImport.update({
  id: '/rewards/issue',
  path: '/rewards/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesAdvancesRoute = SalariesAdvancesRouteImport.update({
  id: '/salaries/advances',
  path: '/salaries/advances',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementConfirmRoute = SalaryPlacementConfirmRouteImport.update({
  id: '/salary-placement/confirm',
  path: '/salary-placement/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementDecisionRoute = SalaryPlacementDecisionRouteImport.update({
  id: '/salary-placement/decision',
  path: '/salary-placement/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementMatchRoute = SalaryPlacementMatchRouteImport.update({
  id: '/salary-placement/match',
  path: '/salary-placement/match',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementProfileRoute = SalaryPlacementProfileRouteImport.update({
  id: '/salary-placement/profile',
  path: '/salary-placement/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementPullRoute = SalaryPlacementPullRouteImport.update({
  id: '/salary-placement/pull',
  path: '/salary-placement/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementSelectRoute = SalaryPlacementSelectRouteImport.update({
  id: '/salary-placement/select',
  path: '/salary-placement/select',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoiceRoute = SalesInvoiceRouteImport.update({
  id: '/sales_/invoice',
  path: '/sales/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales_/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/finance': typeof FinanceRoute
  '/notifications': typeof NotificationsRoute
  '/sales': typeof SalesRoute
  '/self-service': typeof SelfServiceRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/attendance/check-in': typeof AttendanceCheckInRoute
  '/attendance/penalties': typeof AttendancePenaltiesRoute
  '/attendance/permission': typeof AttendancePermissionRoute
  '/customer-service/inbox': typeof CustomerServiceInboxRoute
  '/employees/admin-letter': typeof EmployeesAdminLetterRoute
  '/employees/custody': typeof EmployeesCustodyRoute
  '/employees/department': typeof EmployeesDepartmentRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/end-of-service': typeof EmployeesEndOfServiceRoute
  '/employees/financial-letter': typeof EmployeesFinancialLetterRoute
  '/employees/new': typeof EmployeesNewRoute
  '/employees/profile': typeof EmployeesProfileRoute
  '/employees/promotion': typeof EmployeesPromotionRoute
  '/employees/transfer': typeof EmployeesTransferRoute
  '/finance/bank-movements': typeof FinanceBankMovementsRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/invoice-inputs': typeof FinanceInvoiceInputsRoute
  '/finance/money-flow': typeof FinanceMoneyFlowRoute
  '/finance/month-close': typeof FinanceMonthCloseRoute
  '/finance/payment-orders': typeof FinancePaymentOrdersRoute
  '/finance/receipts': typeof FinanceReceiptsRoute
  '/finance/recurring': typeof FinanceRecurringRoute
  '/leaves/new': typeof LeavesNewRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/dashboard': typeof MedicalExamDashboardRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/performance/committee': typeof PerformanceCommitteeRoute
  '/performance/criteria': typeof PerformanceCriteriaRoute
  '/performance/evaluation': typeof PerformanceEvaluationRoute
  '/performance/results': typeof PerformanceResultsRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/job-posting': typeof RecruitmentJobPostingRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
  '/reports/financial': typeof ReportsFinancialRoute
  '/requests/tracking': typeof RequestsTrackingRoute
  '/rewards/issue': typeof RewardsIssueRoute
  '/salaries/advances': typeof SalariesAdvancesRoute
  '/salary-placement/confirm': typeof SalaryPlacementConfirmRoute
  '/salary-placement/decision': typeof SalaryPlacementDecisionRoute
  '/salary-placement/match': typeof SalaryPlacementMatchRoute
  '/salary-placement/profile': typeof SalaryPlacementProfileRoute
  '/salary-placement/pull': typeof SalaryPlacementPullRoute
  '/salary-placement/select': typeof SalaryPlacementSelectRoute
  '/sales/invoice': typeof SalesInvoiceRoute
  '/sales/new': typeof SalesNewRoute
  '/customer-service/': typeof CustomerServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/finance': typeof FinanceRoute
  '/notifications': typeof NotificationsRoute
  '/sales': typeof SalesRoute
  '/self-service': typeof SelfServiceRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/attendance/check-in': typeof AttendanceCheckInRoute
  '/attendance/penalties': typeof AttendancePenaltiesRoute
  '/attendance/permission': typeof AttendancePermissionRoute
  '/customer-service/inbox': typeof CustomerServiceInboxRoute
  '/employees/admin-letter': typeof EmployeesAdminLetterRoute
  '/employees/custody': typeof EmployeesCustodyRoute
  '/employees/department': typeof EmployeesDepartmentRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/end-of-service': typeof EmployeesEndOfServiceRoute
  '/employees/financial-letter': typeof EmployeesFinancialLetterRoute
  '/employees/new': typeof EmployeesNewRoute
  '/employees/profile': typeof EmployeesProfileRoute
  '/employees/promotion': typeof EmployeesPromotionRoute
  '/employees/transfer': typeof EmployeesTransferRoute
  '/finance/bank-movements': typeof FinanceBankMovementsRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/invoice-inputs': typeof FinanceInvoiceInputsRoute
  '/finance/money-flow': typeof FinanceMoneyFlowRoute
  '/finance/month-close': typeof FinanceMonthCloseRoute
  '/finance/payment-orders': typeof FinancePaymentOrdersRoute
  '/finance/receipts': typeof FinanceReceiptsRoute
  '/finance/recurring': typeof FinanceRecurringRoute
  '/leaves/new': typeof LeavesNewRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/dashboard': typeof MedicalExamDashboardRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/performance/committee': typeof PerformanceCommitteeRoute
  '/performance/criteria': typeof PerformanceCriteriaRoute
  '/performance/evaluation': typeof PerformanceEvaluationRoute
  '/performance/results': typeof PerformanceResultsRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/job-posting': typeof RecruitmentJobPostingRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
  '/reports/financial': typeof ReportsFinancialRoute
  '/requests/tracking': typeof RequestsTrackingRoute
  '/rewards/issue': typeof RewardsIssueRoute
  '/salaries/advances': typeof SalariesAdvancesRoute
  '/salary-placement/confirm': typeof SalaryPlacementConfirmRoute
  '/salary-placement/decision': typeof SalaryPlacementDecisionRoute
  '/salary-placement/match': typeof SalaryPlacementMatchRoute
  '/salary-placement/profile': typeof SalaryPlacementProfileRoute
  '/salary-placement/pull': typeof SalaryPlacementPullRoute
  '/salary-placement/select': typeof SalaryPlacementSelectRoute
  '/sales/invoice': typeof SalesInvoiceRoute
  '/sales/new': typeof SalesNewRoute
  '/customer-service': typeof CustomerServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/finance': typeof FinanceRoute
  '/notifications': typeof NotificationsRoute
  '/sales': typeof SalesRoute
  '/self-service': typeof SelfServiceRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/attendance/check-in': typeof AttendanceCheckInRoute
  '/attendance/penalties': typeof AttendancePenaltiesRoute
  '/attendance/permission': typeof AttendancePermissionRoute
  '/customer-service/inbox': typeof CustomerServiceInboxRoute
  '/employees/admin-letter': typeof EmployeesAdminLetterRoute
  '/employees/custody': typeof EmployeesCustodyRoute
  '/employees/department': typeof EmployeesDepartmentRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/end-of-service': typeof EmployeesEndOfServiceRoute
  '/employees/financial-letter': typeof EmployeesFinancialLetterRoute
  '/employees/new': typeof EmployeesNewRoute
  '/employees/profile': typeof EmployeesProfileRoute
  '/employees/promotion': typeof EmployeesPromotionRoute
  '/employees/transfer': typeof EmployeesTransferRoute
  '/finance_/bank-movements': typeof FinanceBankMovementsRoute
  '/finance_/banks': typeof FinanceBanksRoute
  '/finance_/cash-flow': typeof FinanceCashFlowRoute
  '/finance_/invoice-inputs': typeof FinanceInvoiceInputsRoute
  '/finance_/money-flow': typeof FinanceMoneyFlowRoute
  '/finance_/month-close': typeof FinanceMonthCloseRoute
  '/finance_/payment-orders': typeof FinancePaymentOrdersRoute
  '/finance_/receipts': typeof FinanceReceiptsRoute
  '/finance_/recurring': typeof FinanceRecurringRoute
  '/leaves/new': typeof LeavesNewRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/dashboard': typeof MedicalExamDashboardRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/performance/committee': typeof PerformanceCommitteeRoute
  '/performance/criteria': typeof PerformanceCriteriaRoute
  '/performance/evaluation': typeof PerformanceEvaluationRoute
  '/performance/results': typeof PerformanceResultsRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/job-posting': typeof RecruitmentJobPostingRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
  '/reports/financial': typeof ReportsFinancialRoute
  '/requests/tracking': typeof RequestsTrackingRoute
  '/rewards/issue': typeof RewardsIssueRoute
  '/salaries/advances': typeof SalariesAdvancesRoute
  '/salary-placement/confirm': typeof SalaryPlacementConfirmRoute
  '/salary-placement/decision': typeof SalaryPlacementDecisionRoute
  '/salary-placement/match': typeof SalaryPlacementMatchRoute
  '/salary-placement/profile': typeof SalaryPlacementProfileRoute
  '/salary-placement/pull': typeof SalaryPlacementPullRoute
  '/salary-placement/select': typeof SalaryPlacementSelectRoute
  '/sales_/invoice': typeof SalesInvoiceRoute
  '/sales_/new': typeof SalesNewRoute
  '/customer-service/': typeof CustomerServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/finance'
    | '/notifications'
    | '/sales'
    | '/self-service'
    | '/verify-certificate'
    | '/attendance/check-in'
    | '/attendance/penalties'
    | '/attendance/permission'
    | '/customer-service/inbox'
    | '/employees/admin-letter'
    | '/employees/custody'
    | '/employees/department'
    | '/employees/documents'
    | '/employees/end-of-service'
    | '/employees/financial-letter'
    | '/employees/new'
    | '/employees/profile'
    | '/employees/promotion'
    | '/employees/transfer'
    | '/finance/bank-movements'
    | '/finance/banks'
    | '/finance/cash-flow'
    | '/finance/invoice-inputs'
    | '/finance/money-flow'
    | '/finance/month-close'
    | '/finance/payment-orders'
    | '/finance/receipts'
    | '/finance/recurring'
    | '/leaves/new'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/dashboard'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/performance/committee'
    | '/performance/criteria'
    | '/performance/evaluation'
    | '/performance/results'
    | '/purchases/new'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/job-posting'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
    | '/reports/financial'
    | '/requests/tracking'
    | '/rewards/issue'
    | '/salaries/advances'
    | '/salary-placement/confirm'
    | '/salary-placement/decision'
    | '/salary-placement/match'
    | '/salary-placement/profile'
    | '/salary-placement/pull'
    | '/salary-placement/select'
    | '/sales/invoice'
    | '/sales/new'
    | '/customer-service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/finance'
    | '/notifications'
    | '/sales'
    | '/self-service'
    | '/verify-certificate'
    | '/attendance/check-in'
    | '/attendance/penalties'
    | '/attendance/permission'
    | '/customer-service/inbox'
    | '/employees/admin-letter'
    | '/employees/custody'
    | '/employees/department'
    | '/employees/documents'
    | '/employees/end-of-service'
    | '/employees/financial-letter'
    | '/employees/new'
    | '/employees/profile'
    | '/employees/promotion'
    | '/employees/transfer'
    | '/finance/bank-movements'
    | '/finance/banks'
    | '/finance/cash-flow'
    | '/finance/invoice-inputs'
    | '/finance/money-flow'
    | '/finance/month-close'
    | '/finance/payment-orders'
    | '/finance/receipts'
    | '/finance/recurring'
    | '/leaves/new'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/dashboard'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/performance/committee'
    | '/performance/criteria'
    | '/performance/evaluation'
    | '/performance/results'
    | '/purchases/new'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/job-posting'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
    | '/reports/financial'
    | '/requests/tracking'
    | '/rewards/issue'
    | '/salaries/advances'
    | '/salary-placement/confirm'
    | '/salary-placement/decision'
    | '/salary-placement/match'
    | '/salary-placement/profile'
    | '/salary-placement/pull'
    | '/salary-placement/select'
    | '/sales/invoice'
    | '/sales/new'
    | '/customer-service'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/finance'
    | '/notifications'
    | '/sales'
    | '/self-service'
    | '/verify-certificate'
    | '/attendance/check-in'
    | '/attendance/penalties'
    | '/attendance/permission'
    | '/customer-service/inbox'
    | '/employees/admin-letter'
    | '/employees/custody'
    | '/employees/department'
    | '/employees/documents'
    | '/employees/end-of-service'
    | '/employees/financial-letter'
    | '/employees/new'
    | '/employees/profile'
    | '/employees/promotion'
    | '/employees/transfer'
    | '/finance_/bank-movements'
    | '/finance_/banks'
    | '/finance_/cash-flow'
    | '/finance_/invoice-inputs'
    | '/finance_/money-flow'
    | '/finance_/month-close'
    | '/finance_/payment-orders'
    | '/finance_/receipts'
    | '/finance_/recurring'
    | '/leaves/new'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/dashboard'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/performance/committee'
    | '/performance/criteria'
    | '/performance/evaluation'
    | '/performance/results'
    | '/purchases/new'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/job-posting'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
    | '/reports/financial'
    | '/requests/tracking'
    | '/rewards/issue'
    | '/salaries/advances'
    | '/salary-placement/confirm'
    | '/salary-placement/decision'
    | '/salary-placement/match'
    | '/salary-placement/profile'
    | '/salary-placement/pull'
    | '/salary-placement/select'
    | '/sales_/invoice'
    | '/sales_/new'
    | '/customer-service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  FinanceRoute: typeof FinanceRoute
  NotificationsRoute: typeof NotificationsRoute
  SalesRoute: typeof SalesRoute
  SelfServiceRoute: typeof SelfServiceRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  AttendanceCheckInRoute: typeof AttendanceCheckInRoute
  AttendancePenaltiesRoute: typeof AttendancePenaltiesRoute
  AttendancePermissionRoute: typeof AttendancePermissionRoute
  CustomerServiceInboxRoute: typeof CustomerServiceInboxRoute
  EmployeesAdminLetterRoute: typeof EmployeesAdminLetterRoute
  EmployeesCustodyRoute: typeof EmployeesCustodyRoute
  EmployeesDepartmentRoute: typeof EmployeesDepartmentRoute
  EmployeesDocumentsRoute: typeof EmployeesDocumentsRoute
  EmployeesEndOfServiceRoute: typeof EmployeesEndOfServiceRoute
  EmployeesFinancialLetterRoute: typeof EmployeesFinancialLetterRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  EmployeesProfileRoute: typeof EmployeesProfileRoute
  EmployeesPromotionRoute: typeof EmployeesPromotionRoute
  EmployeesTransferRoute: typeof EmployeesTransferRoute
  FinanceBankMovementsRoute: typeof FinanceBankMovementsRoute
  FinanceBanksRoute: typeof FinanceBanksRoute
  FinanceCashFlowRoute: typeof FinanceCashFlowRoute
  FinanceInvoiceInputsRoute: typeof FinanceInvoiceInputsRoute
  FinanceMoneyFlowRoute: typeof FinanceMoneyFlowRoute
  FinanceMonthCloseRoute: typeof FinanceMonthCloseRoute
  FinancePaymentOrdersRoute: typeof FinancePaymentOrdersRoute
  FinanceReceiptsRoute: typeof FinanceReceiptsRoute
  FinanceRecurringRoute: typeof FinanceRecurringRoute
  LeavesNewRoute: typeof LeavesNewRoute
  MedicalExamCenterRoute: typeof MedicalExamCenterRoute
  MedicalExamCompanyRoute: typeof MedicalExamCompanyRoute
  MedicalExamDashboardRoute: typeof MedicalExamDashboardRoute
  MedicalExamEmployeeRoute: typeof MedicalExamEmployeeRoute
  MedicalExamHrRoute: typeof MedicalExamHrRoute
  MedicalExamRequestRoute: typeof MedicalExamRequestRoute
  MedicalExamResultRoute: typeof MedicalExamResultRoute
  MedicalExamTestsRoute: typeof MedicalExamTestsRoute
  MedicalExamTrackingRoute: typeof MedicalExamTrackingRoute
  PerformanceCommitteeRoute: typeof PerformanceCommitteeRoute
  PerformanceCriteriaRoute: typeof PerformanceCriteriaRoute
  PerformanceEvaluationRoute: typeof PerformanceEvaluationRoute
  PerformanceResultsRoute: typeof PerformanceResultsRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  RecruitmentAppointmentRoute: typeof RecruitmentAppointmentRoute
  RecruitmentDecisionRoute: typeof RecruitmentDecisionRoute
  RecruitmentEvaluationRoute: typeof RecruitmentEvaluationRoute
  RecruitmentJobPostingRoute: typeof RecruitmentJobPostingRoute
  RecruitmentMedicalRoute: typeof RecruitmentMedicalRoute
  RecruitmentOfferRoute: typeof RecruitmentOfferRoute
  RecruitmentRegistrationRoute: typeof RecruitmentRegistrationRoute
  RecruitmentReportsRoute: typeof RecruitmentReportsRoute
  RecruitmentRequestsRoute: typeof RecruitmentRequestsRoute
  RecruitmentScreeningRoute: typeof RecruitmentScreeningRoute
  RecruitmentTrackingRoute: typeof RecruitmentTrackingRoute
  ReportsFinancialRoute: typeof ReportsFinancialRoute
  RequestsTrackingRoute: typeof RequestsTrackingRoute
  RewardsIssueRoute: typeof RewardsIssueRoute
  SalariesAdvancesRoute: typeof SalariesAdvancesRoute
  SalaryPlacementConfirmRoute: typeof SalaryPlacementConfirmRoute
  SalaryPlacementDecisionRoute: typeof SalaryPlacementDecisionRoute
  SalaryPlacementMatchRoute: typeof SalaryPlacementMatchRoute
  SalaryPlacementProfileRoute: typeof SalaryPlacementProfileRoute
  SalaryPlacementPullRoute: typeof SalaryPlacementPullRoute
  SalaryPlacementSelectRoute: typeof SalaryPlacementSelectRoute
  SalesInvoiceRoute: typeof SalesInvoiceRoute
  SalesNewRoute: typeof SalesNewRoute
  CustomerServiceIndexRoute: typeof CustomerServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-service': {
      id: '/self-service'
      path: '/self-service'
      fullPath: '/self-service'
      preLoaderRoute: typeof SelfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/check-in': {
      id: '/attendance/check-in'
      path: '/attendance/check-in'
      fullPath: '/attendance/check-in'
      preLoaderRoute: typeof AttendanceCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/penalties': {
      id: '/attendance/penalties'
      path: '/attendance/penalties'
      fullPath: '/attendance/penalties'
      preLoaderRoute: typeof AttendancePenaltiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/permission': {
      id: '/attendance/permission'
      path: '/attendance/permission'
      fullPath: '/attendance/permission'
      preLoaderRoute: typeof AttendancePermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service/': {
      id: '/customer-service/'
      path: '/customer-service'
      fullPath: '/customer-service/'
      preLoaderRoute: typeof CustomerServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service/inbox': {
      id: '/customer-service/inbox'
      path: '/customer-service/inbox'
      fullPath: '/customer-service/inbox'
      preLoaderRoute: typeof CustomerServiceInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/admin-letter': {
      id: '/employees/admin-letter'
      path: '/employees/admin-letter'
      fullPath: '/employees/admin-letter'
      preLoaderRoute: typeof EmployeesAdminLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/custody': {
      id: '/employees/custody'
      path: '/employees/custody'
      fullPath: '/employees/custody'
      preLoaderRoute: typeof EmployeesCustodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/department': {
      id: '/employees/department'
      path: '/employees/department'
      fullPath: '/employees/department'
      preLoaderRoute: typeof EmployeesDepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/documents': {
      id: '/employees/documents'
      path: '/employees/documents'
      fullPath: '/employees/documents'
      preLoaderRoute: typeof EmployeesDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/end-of-service': {
      id: '/employees/end-of-service'
      path: '/employees/end-of-service'
      fullPath: '/employees/end-of-service'
      preLoaderRoute: typeof EmployeesEndOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/financial-letter': {
      id: '/employees/financial-letter'
      path: '/employees/financial-letter'
      fullPath: '/employees/financial-letter'
      preLoaderRoute: typeof EmployeesFinancialLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/profile': {
      id: '/employees/profile'
      path: '/employees/profile'
      fullPath: '/employees/profile'
      preLoaderRoute: typeof EmployeesProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/promotion': {
      id: '/employees/promotion'
      path: '/employees/promotion'
      fullPath: '/employees/promotion'
      preLoaderRoute: typeof EmployeesPromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/transfer': {
      id: '/employees/transfer'
      path: '/employees/transfer'
      fullPath: '/employees/transfer'
      preLoaderRoute: typeof EmployeesTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/bank-movements': {
      id: '/finance_/bank-movements'
      path: '/finance/bank-movements'
      fullPath: '/finance/bank-movements'
      preLoaderRoute: typeof FinanceBankMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/banks': {
      id: '/finance_/banks'
      path: '/finance/banks'
      fullPath: '/finance/banks'
      preLoaderRoute: typeof FinanceBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/cash-flow': {
      id: '/finance_/cash-flow'
      path: '/finance/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof FinanceCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/invoice-inputs': {
      id: '/finance_/invoice-inputs'
      path: '/finance/invoice-inputs'
      fullPath: '/finance/invoice-inputs'
      preLoaderRoute: typeof FinanceInvoiceInputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/money-flow': {
      id: '/finance_/money-flow'
      path: '/finance/money-flow'
      fullPath: '/finance/money-flow'
      preLoaderRoute: typeof FinanceMoneyFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/month-close': {
      id: '/finance_/month-close'
      path: '/finance/month-close'
      fullPath: '/finance/month-close'
      preLoaderRoute: typeof FinanceMonthCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/payment-orders': {
      id: '/finance_/payment-orders'
      path: '/finance/payment-orders'
      fullPath: '/finance/payment-orders'
      preLoaderRoute: typeof FinancePaymentOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/receipts': {
      id: '/finance_/receipts'
      path: '/finance/receipts'
      fullPath: '/finance/receipts'
      preLoaderRoute: typeof FinanceReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/recurring': {
      id: '/finance_/recurring'
      path: '/finance/recurring'
      fullPath: '/finance/recurring'
      preLoaderRoute: typeof FinanceRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves/new': {
      id: '/leaves/new'
      path: '/leaves/new'
      fullPath: '/leaves/new'
      preLoaderRoute: typeof LeavesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/center': {
      id: '/medical-exam/center'
      path: '/medical-exam/center'
      fullPath: '/medical-exam/center'
      preLoaderRoute: typeof MedicalExamCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/company': {
      id: '/medical-exam/company'
      path: '/medical-exam/company'
      fullPath: '/medical-exam/company'
      preLoaderRoute: typeof MedicalExamCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/dashboard': {
      id: '/medical-exam/dashboard'
      path: '/medical-exam/dashboard'
      fullPath: '/medical-exam/dashboard'
      preLoaderRoute: typeof MedicalExamDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/employee': {
      id: '/medical-exam/employee'
      path: '/medical-exam/employee'
      fullPath: '/medical-exam/employee'
      preLoaderRoute: typeof MedicalExamEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/hr': {
      id: '/medical-exam/hr'
      path: '/medical-exam/hr'
      fullPath: '/medical-exam/hr'
      preLoaderRoute: typeof MedicalExamHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/request': {
      id: '/medical-exam/request'
      path: '/medical-exam/request'
      fullPath: '/medical-exam/request'
      preLoaderRoute: typeof MedicalExamRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/result': {
      id: '/medical-exam/result'
      path: '/medical-exam/result'
      fullPath: '/medical-exam/result'
      preLoaderRoute: typeof MedicalExamResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/tests': {
      id: '/medical-exam/tests'
      path: '/medical-exam/tests'
      fullPath: '/medical-exam/tests'
      preLoaderRoute: typeof MedicalExamTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/tracking': {
      id: '/medical-exam/tracking'
      path: '/medical-exam/tracking'
      fullPath: '/medical-exam/tracking'
      preLoaderRoute: typeof MedicalExamTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/committee': {
      id: '/performance/committee'
      path: '/performance/committee'
      fullPath: '/performance/committee'
      preLoaderRoute: typeof PerformanceCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/criteria': {
      id: '/performance/criteria'
      path: '/performance/criteria'
      fullPath: '/performance/criteria'
      preLoaderRoute: typeof PerformanceCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/evaluation': {
      id: '/performance/evaluation'
      path: '/performance/evaluation'
      fullPath: '/performance/evaluation'
      preLoaderRoute: typeof PerformanceEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/results': {
      id: '/performance/results'
      path: '/performance/results'
      fullPath: '/performance/results'
      preLoaderRoute: typeof PerformanceResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/appointment': {
      id: '/recruitment/appointment'
      path: '/recruitment/appointment'
      fullPath: '/recruitment/appointment'
      preLoaderRoute: typeof RecruitmentAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/decision': {
      id: '/recruitment/decision'
      path: '/recruitment/decision'
      fullPath: '/recruitment/decision'
      preLoaderRoute: typeof RecruitmentDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/evaluation': {
      id: '/recruitment/evaluation'
      path: '/recruitment/evaluation'
      fullPath: '/recruitment/evaluation'
      preLoaderRoute: typeof RecruitmentEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/job-posting': {
      id: '/recruitment/job-posting'
      path: '/recruitment/job-posting'
      fullPath: '/recruitment/job-posting'
      preLoaderRoute: typeof RecruitmentJobPostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/medical': {
      id: '/recruitment/medical'
      path: '/recruitment/medical'
      fullPath: '/recruitment/medical'
      preLoaderRoute: typeof RecruitmentMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/offer': {
      id: '/recruitment/offer'
      path: '/recruitment/offer'
      fullPath: '/recruitment/offer'
      preLoaderRoute: typeof RecruitmentOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/registration': {
      id: '/recruitment/registration'
      path: '/recruitment/registration'
      fullPath: '/recruitment/registration'
      preLoaderRoute: typeof RecruitmentRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/reports': {
      id: '/recruitment/reports'
      path: '/recruitment/reports'
      fullPath: '/recruitment/reports'
      preLoaderRoute: typeof RecruitmentReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/requests': {
      id: '/recruitment/requests'
      path: '/recruitment/requests'
      fullPath: '/recruitment/requests'
      preLoaderRoute: typeof RecruitmentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/screening': {
      id: '/recruitment/screening'
      path: '/recruitment/screening'
      fullPath: '/recruitment/screening'
      preLoaderRoute: typeof RecruitmentScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/tracking': {
      id: '/recruitment/tracking'
      path: '/recruitment/tracking'
      fullPath: '/recruitment/tracking'
      preLoaderRoute: typeof RecruitmentTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/financial': {
      id: '/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof ReportsFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/tracking': {
      id: '/requests/tracking'
      path: '/requests/tracking'
      fullPath: '/requests/tracking'
      preLoaderRoute: typeof RequestsTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/issue': {
      id: '/rewards/issue'
      path: '/rewards/issue'
      fullPath: '/rewards/issue'
      preLoaderRoute: typeof RewardsIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/advances': {
      id: '/salaries/advances'
      path: '/salaries/advances'
      fullPath: '/salaries/advances'
      preLoaderRoute: typeof SalariesAdvancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/confirm': {
      id: '/salary-placement/confirm'
      path: '/salary-placement/confirm'
      fullPath: '/salary-placement/confirm'
      preLoaderRoute: typeof SalaryPlacementConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/decision': {
      id: '/salary-placement/decision'
      path: '/salary-placement/decision'
      fullPath: '/salary-placement/decision'
      preLoaderRoute: typeof SalaryPlacementDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/match': {
      id: '/salary-placement/match'
      path: '/salary-placement/match'
      fullPath: '/salary-placement/match'
      preLoaderRoute: typeof SalaryPlacementMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/profile': {
      id: '/salary-placement/profile'
      path: '/salary-placement/profile'
      fullPath: '/salary-placement/profile'
      preLoaderRoute: typeof SalaryPlacementProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/pull': {
      id: '/salary-placement/pull'
      path: '/salary-placement/pull'
      fullPath: '/salary-placement/pull'
      preLoaderRoute: typeof SalaryPlacementPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/select': {
      id: '/salary-placement/select'
      path: '/salary-placement/select'
      fullPath: '/salary-placement/select'
      preLoaderRoute: typeof SalaryPlacementSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales_/invoice': {
      id: '/sales_/invoice'
      path: '/sales/invoice'
      fullPath: '/sales/invoice'
      preLoaderRoute: typeof SalesInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales_/new': {
      id: '/sales_/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  FinanceRoute: FinanceRoute,
  NotificationsRoute: NotificationsRoute,
  SalesRoute: SalesRoute,
  SelfServiceRoute: SelfServiceRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  AttendanceCheckInRoute: AttendanceCheckInRoute,
  AttendancePenaltiesRoute: AttendancePenaltiesRoute,
  AttendancePermissionRoute: AttendancePermissionRoute,
  CustomerServiceInboxRoute: CustomerServiceInboxRoute,
  EmployeesAdminLetterRoute: EmployeesAdminLetterRoute,
  EmployeesCustodyRoute: EmployeesCustodyRoute,
  EmployeesDepartmentRoute: EmployeesDepartmentRoute,
  EmployeesDocumentsRoute: EmployeesDocumentsRoute,
  EmployeesEndOfServiceRoute: EmployeesEndOfServiceRoute,
  EmployeesFinancialLetterRoute: EmployeesFinancialLetterRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  EmployeesProfileRoute: EmployeesProfileRoute,
  EmployeesPromotionRoute: EmployeesPromotionRoute,
  EmployeesTransferRoute: EmployeesTransferRoute,
  FinanceBankMovementsRoute: FinanceBankMovementsRoute,
  FinanceBanksRoute: FinanceBanksRoute,
  FinanceCashFlowRoute: FinanceCashFlowRoute,
  FinanceInvoiceInputsRoute: FinanceInvoiceInputsRoute,
  FinanceMoneyFlowRoute: FinanceMoneyFlowRoute,
  FinanceMonthCloseRoute: FinanceMonthCloseRoute,
  FinancePaymentOrdersRoute: FinancePaymentOrdersRoute,
  FinanceReceiptsRoute: FinanceReceiptsRoute,
  FinanceRecurringRoute: FinanceRecurringRoute,
  LeavesNewRoute: LeavesNewRoute,
  MedicalExamCenterRoute: MedicalExamCenterRoute,
  MedicalExamCompanyRoute: MedicalExamCompanyRoute,
  MedicalExamDashboardRoute: MedicalExamDashboardRoute,
  MedicalExamEmployeeRoute: MedicalExamEmployeeRoute,
  MedicalExamHrRoute: MedicalExamHrRoute,
  MedicalExamRequestRoute: MedicalExamRequestRoute,
  MedicalExamResultRoute: MedicalExamResultRoute,
  MedicalExamTestsRoute: MedicalExamTestsRoute,
  MedicalExamTrackingRoute: MedicalExamTrackingRoute,
  PerformanceCommitteeRoute: PerformanceCommitteeRoute,
  PerformanceCriteriaRoute: PerformanceCriteriaRoute,
  PerformanceEvaluationRoute: PerformanceEvaluationRoute,
  PerformanceResultsRoute: PerformanceResultsRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  RecruitmentAppointmentRoute: RecruitmentAppointmentRoute,
  RecruitmentDecisionRoute: RecruitmentDecisionRoute,
  RecruitmentEvaluationRoute: RecruitmentEvaluationRoute,
  RecruitmentJobPostingRoute: RecruitmentJobPostingRoute,
  RecruitmentMedicalRoute: RecruitmentMedicalRoute,
  RecruitmentOfferRoute: RecruitmentOfferRoute,
  RecruitmentRegistrationRoute: RecruitmentRegistrationRoute,
  RecruitmentReportsRoute: RecruitmentReportsRoute,
  RecruitmentRequestsRoute: RecruitmentRequestsRoute,
  RecruitmentScreeningRoute: RecruitmentScreeningRoute,
  RecruitmentTrackingRoute: RecruitmentTrackingRoute,
  ReportsFinancialRoute: ReportsFinancialRoute,
  RequestsTrackingRoute: RequestsTrackingRoute,
  RewardsIssueRoute: RewardsIssueRoute,
  SalariesAdvancesRoute: SalariesAdvancesRoute,
  SalaryPlacementConfirmRoute: SalaryPlacementConfirmRoute,
  SalaryPlacementDecisionRoute: SalaryPlacementDecisionRoute,
  SalaryPlacementMatchRoute: SalaryPlacementMatchRoute,
  SalaryPlacementProfileRoute: SalaryPlacementProfileRoute,
  SalaryPlacementPullRoute: SalaryPlacementPullRoute,
  SalaryPlacementSelectRoute: SalaryPlacementSelectRoute,
  SalesInvoiceRoute: SalesInvoiceRoute,
  SalesNewRoute: SalesNewRoute,
  CustomerServiceIndexRoute: CustomerServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
