/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as AttendanceCheckInRouteImport } from './routes/attendance.check-in'
import { Route as AttendancePermissionRouteImport } from './routes/attendance.permission'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as EmployeesProfileRouteImport } from './routes/employees.profile'
import { Route as LeavesNewRouteImport } from './routes/leaves.new'
import { Route as MedicalExamCenterRouteImport } from './routes/medical-exam.center'
import { Route as MedicalExamCompanyRouteImport } from './routes/medical-exam.company'
import { Route as MedicalExamEmployeeRouteImport } from './routes/medical-exam.employee'
import { Route as MedicalExamHrRouteImport } from './routes/medical-exam.hr'
import { Route as MedicalExamRequestRouteImport } from './routes/medical-exam.request'
import { Route as MedicalExamResultRouteImport } from './routes/medical-exam.result'
import { Route as MedicalExamTestsRouteImport } from './routes/medical-exam.tests'
import { Route as MedicalExamTrackingRouteImport } from './routes/medical-exam.tracking'
import { Route as PerformanceEvaluationRouteImport } from './routes/performance.evaluation'
import { Route as RecruitmentAppointmentRouteImport } from './routes/recruitment.appointment'
import { Route as RecruitmentDecisionRouteImport } from './routes/recruitment.decision'
import { Route as RecruitmentEvaluationRouteImport } from './routes/recruitment.evaluation'
import { Route as RecruitmentMedicalRouteImport } from './routes/recruitment.medical'
import { Route as RecruitmentOfferRouteImport } from './routes/recruitment.offer'
import { Route as RecruitmentRegistrationRouteImport } from './routes/recruitment.registration'
import { Route as RecruitmentReportsRouteImport } from './routes/recruitment.reports'
import { Route as RecruitmentRequestsRouteImport } from './routes/recruitment.requests'
import { Route as RecruitmentScreeningRouteImport } from './routes/recruitment.screening'
import { Route as RecruitmentTrackingRouteImport } from './routes/recruitment.tracking'
import { Route as RequestsTrackingRouteImport } from './routes/requests.tracking'
import { Route as RewardsIssueRouteImport } from './routes/rewards.issue'
import { Route as SalaryPlacementConfirmRouteImport } from './routes/salary-placement.confirm'
import { Route as SalaryPlacementDecisionRouteImport } from './routes/salary-placement.decision'
import { Route as SalaryPlacementMatchRouteImport } from './routes/salary-placement.match'
import { Route as SalaryPlacementProfileRouteImport } from './routes/salary-placement.profile'
import { Route as SalaryPlacementPullRouteImport } from './routes/salary-placement.pull'
import { Route as SalaryPlacementSelectRouteImport } from './routes/salary-placement.select'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceCheckInRoute = AttendanceCheckInRouteImport.update({
  id: '/attendance/check-in',
  path: '/attendance/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendancePermissionRoute = AttendancePermissionRouteImport.update({
  id: '/attendance/permission',
  path: '/attendance/permission',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesProfileRoute = EmployeesProfileRouteImport.update({
  id: '/employees/profile',
  path: '/employees/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesNewRoute = LeavesNewRouteImport.update({
  id: '/leaves/new',
  path: '/leaves/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamCenterRoute = MedicalExamCenterRouteImport.update({
  id: '/medical-exam/center',
  path: '/medical-exam/center',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamCompanyRoute = MedicalExamCompanyRouteImport.update({
  id: '/medical-exam/company',
  path: '/medical-exam/company',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamEmployeeRoute = MedicalExamEmployeeRouteImport.update({
  id: '/medical-exam/employee',
  path: '/medical-exam/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamHrRoute = MedicalExamHrRouteImport.update({
  id: '/medical-exam/hr',
  path: '/medical-exam/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamRequestRoute = MedicalExamRequestRouteImport.update({
  id: '/medical-exam/request',
  path: '/medical-exam/request',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamResultRoute = MedicalExamResultRouteImport.update({
  id: '/medical-exam/result',
  path: '/medical-exam/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamTestsRoute = MedicalExamTestsRouteImport.update({
  id: '/medical-exam/tests',
  path: '/medical-exam/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamTrackingRoute = MedicalExamTrackingRouteImport.update({
  id: '/medical-exam/tracking',
  path: '/medical-exam/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceEvaluationRoute = PerformanceEvaluationRouteImport.update({
  id: '/performance/evaluation',
  path: '/performance/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentAppointmentRoute = RecruitmentAppointmentRouteImport.update({
  id: '/recruitment/appointment',
  path: '/recruitment/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentDecisionRoute = RecruitmentDecisionRouteImport.update({
  id: '/recruitment/decision',
  path: '/recruitment/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentEvaluationRoute = RecruitmentEvaluationRouteImport.update({
  id: '/recruitment/evaluation',
  path: '/recruitment/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentMedicalRoute = RecruitmentMedicalRouteImport.update({
  id: '/recruitment/medical',
  path: '/recruitment/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentOfferRoute = RecruitmentOfferRouteImport.update({
  id: '/recruitment/offer',
  path: '/recruitment/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRegistrationRoute = RecruitmentRegistrationRouteImport.update({
  id: '/recruitment/registration',
  path: '/recruitment/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentReportsRoute = RecruitmentReportsRouteImport.update({
  id: '/recruitment/reports',
  path: '/recruitment/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRequestsRoute = RecruitmentRequestsRouteImport.update({
  id: '/recruitment/requests',
  path: '/recruitment/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentScreeningRoute = RecruitmentScreeningRouteImport.update({
  id: '/recruitment/screening',
  path: '/recruitment/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentTrackingRoute = RecruitmentTrackingRouteImport.update({
  id: '/recruitment/tracking',
  path: '/recruitment/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsTrackingRoute = RequestsTrackingRouteImport.update({
  id: '/requests/tracking',
  path: '/requests/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsIssueRoute = RewardsIssueRouteImport.update({
  id: '/rewards/issue',
  path: '/rewards/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementConfirmRoute = SalaryPlacementConfirmRouteImport.update({
  id: '/salary-placement/confirm',
  path: '/salary-placement/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementDecisionRoute = SalaryPlacementDecisionRouteImport.update({
  id: '/salary-placement/decision',
  path: '/salary-placement/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementMatchRoute = SalaryPlacementMatchRouteImport.update({
  id: '/salary-placement/match',
  path: '/salary-placement/match',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementProfileRoute = SalaryPlacementProfileRouteImport.update({
  id: '/salary-placement/profile',
  path: '/salary-placement/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementPullRoute = SalaryPlacementPullRouteImport.update({
  id: '/salary-placement/pull',
  path: '/salary-placement/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPlacementSelectRoute = SalaryPlacementSelectRouteImport.update({
  id: '/salary-placement/select',
  path: '/salary-placement/select',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/attendance/check-in': typeof AttendanceCheckInRoute
  '/attendance/permission': typeof AttendancePermissionRoute
  '/employees/new': typeof EmployeesNewRoute
  '/employees/profile': typeof EmployeesProfileRoute
  '/leaves/new': typeof LeavesNewRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/performance/evaluation': typeof PerformanceEvaluationRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
  '/requests/tracking': typeof RequestsTrackingRoute
  '/rewards/issue': typeof RewardsIssueRoute
  '/salary-placement/confirm': typeof SalaryPlacementConfirmRoute
  '/salary-placement/decision': typeof SalaryPlacementDecisionRoute
  '/salary-placement/match': typeof SalaryPlacementMatchRoute
  '/salary-placement/profile': typeof SalaryPlacementProfileRoute
  '/salary-placement/pull': typeof SalaryPlacementPullRoute
  '/salary-placement/select': typeof SalaryPlacementSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/attendance/check-in': typeof AttendanceCheckInRoute
  '/attendance/permission': typeof AttendancePermissionRoute
  '/employees/new': typeof EmployeesNewRoute
  '/employees/profile': typeof EmployeesProfileRoute
  '/leaves/new': typeof LeavesNewRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/performance/evaluation': typeof PerformanceEvaluationRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
  '/requests/tracking': typeof RequestsTrackingRoute
  '/rewards/issue': typeof RewardsIssueRoute
  '/salary-placement/confirm': typeof SalaryPlacementConfirmRoute
  '/salary-placement/decision': typeof SalaryPlacementDecisionRoute
  '/salary-placement/match': typeof SalaryPlacementMatchRoute
  '/salary-placement/profile': typeof SalaryPlacementProfileRoute
  '/salary-placement/pull': typeof SalaryPlacementPullRoute
  '/salary-placement/select': typeof SalaryPlacementSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/attendance/check-in': typeof AttendanceCheckInRoute
  '/attendance/permission': typeof AttendancePermissionRoute
  '/employees/new': typeof EmployeesNewRoute
  '/employees/profile': typeof EmployeesProfileRoute
  '/leaves/new': typeof LeavesNewRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/performance/evaluation': typeof PerformanceEvaluationRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
  '/requests/tracking': typeof RequestsTrackingRoute
  '/rewards/issue': typeof RewardsIssueRoute
  '/salary-placement/confirm': typeof SalaryPlacementConfirmRoute
  '/salary-placement/decision': typeof SalaryPlacementDecisionRoute
  '/salary-placement/match': typeof SalaryPlacementMatchRoute
  '/salary-placement/profile': typeof SalaryPlacementProfileRoute
  '/salary-placement/pull': typeof SalaryPlacementPullRoute
  '/salary-placement/select': typeof SalaryPlacementSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/verify-certificate'
    | '/attendance/check-in'
    | '/attendance/permission'
    | '/employees/new'
    | '/employees/profile'
    | '/leaves/new'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/performance/evaluation'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
    | '/requests/tracking'
    | '/rewards/issue'
    | '/salary-placement/confirm'
    | '/salary-placement/decision'
    | '/salary-placement/match'
    | '/salary-placement/profile'
    | '/salary-placement/pull'
    | '/salary-placement/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/verify-certificate'
    | '/attendance/check-in'
    | '/attendance/permission'
    | '/employees/new'
    | '/employees/profile'
    | '/leaves/new'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/performance/evaluation'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
    | '/requests/tracking'
    | '/rewards/issue'
    | '/salary-placement/confirm'
    | '/salary-placement/decision'
    | '/salary-placement/match'
    | '/salary-placement/profile'
    | '/salary-placement/pull'
    | '/salary-placement/select'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/verify-certificate'
    | '/attendance/check-in'
    | '/attendance/permission'
    | '/employees/new'
    | '/employees/profile'
    | '/leaves/new'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/performance/evaluation'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
    | '/requests/tracking'
    | '/rewards/issue'
    | '/salary-placement/confirm'
    | '/salary-placement/decision'
    | '/salary-placement/match'
    | '/salary-placement/profile'
    | '/salary-placement/pull'
    | '/salary-placement/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  AttendanceCheckInRoute: typeof AttendanceCheckInRoute
  AttendancePermissionRoute: typeof AttendancePermissionRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  EmployeesProfileRoute: typeof EmployeesProfileRoute
  LeavesNewRoute: typeof LeavesNewRoute
  MedicalExamCenterRoute: typeof MedicalExamCenterRoute
  MedicalExamCompanyRoute: typeof MedicalExamCompanyRoute
  MedicalExamEmployeeRoute: typeof MedicalExamEmployeeRoute
  MedicalExamHrRoute: typeof MedicalExamHrRoute
  MedicalExamRequestRoute: typeof MedicalExamRequestRoute
  MedicalExamResultRoute: typeof MedicalExamResultRoute
  MedicalExamTestsRoute: typeof MedicalExamTestsRoute
  MedicalExamTrackingRoute: typeof MedicalExamTrackingRoute
  PerformanceEvaluationRoute: typeof PerformanceEvaluationRoute
  RecruitmentAppointmentRoute: typeof RecruitmentAppointmentRoute
  RecruitmentDecisionRoute: typeof RecruitmentDecisionRoute
  RecruitmentEvaluationRoute: typeof RecruitmentEvaluationRoute
  RecruitmentMedicalRoute: typeof RecruitmentMedicalRoute
  RecruitmentOfferRoute: typeof RecruitmentOfferRoute
  RecruitmentRegistrationRoute: typeof RecruitmentRegistrationRoute
  RecruitmentReportsRoute: typeof RecruitmentReportsRoute
  RecruitmentRequestsRoute: typeof RecruitmentRequestsRoute
  RecruitmentScreeningRoute: typeof RecruitmentScreeningRoute
  RecruitmentTrackingRoute: typeof RecruitmentTrackingRoute
  RequestsTrackingRoute: typeof RequestsTrackingRoute
  RewardsIssueRoute: typeof RewardsIssueRoute
  SalaryPlacementConfirmRoute: typeof SalaryPlacementConfirmRoute
  SalaryPlacementDecisionRoute: typeof SalaryPlacementDecisionRoute
  SalaryPlacementMatchRoute: typeof SalaryPlacementMatchRoute
  SalaryPlacementProfileRoute: typeof SalaryPlacementProfileRoute
  SalaryPlacementPullRoute: typeof SalaryPlacementPullRoute
  SalaryPlacementSelectRoute: typeof SalaryPlacementSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/check-in': {
      id: '/attendance/check-in'
      path: '/attendance/check-in'
      fullPath: '/attendance/check-in'
      preLoaderRoute: typeof AttendanceCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/permission': {
      id: '/attendance/permission'
      path: '/attendance/permission'
      fullPath: '/attendance/permission'
      preLoaderRoute: typeof AttendancePermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/profile': {
      id: '/employees/profile'
      path: '/employees/profile'
      fullPath: '/employees/profile'
      preLoaderRoute: typeof EmployeesProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves/new': {
      id: '/leaves/new'
      path: '/leaves/new'
      fullPath: '/leaves/new'
      preLoaderRoute: typeof LeavesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/center': {
      id: '/medical-exam/center'
      path: '/medical-exam/center'
      fullPath: '/medical-exam/center'
      preLoaderRoute: typeof MedicalExamCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/company': {
      id: '/medical-exam/company'
      path: '/medical-exam/company'
      fullPath: '/medical-exam/company'
      preLoaderRoute: typeof MedicalExamCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/employee': {
      id: '/medical-exam/employee'
      path: '/medical-exam/employee'
      fullPath: '/medical-exam/employee'
      preLoaderRoute: typeof MedicalExamEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/hr': {
      id: '/medical-exam/hr'
      path: '/medical-exam/hr'
      fullPath: '/medical-exam/hr'
      preLoaderRoute: typeof MedicalExamHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/request': {
      id: '/medical-exam/request'
      path: '/medical-exam/request'
      fullPath: '/medical-exam/request'
      preLoaderRoute: typeof MedicalExamRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/result': {
      id: '/medical-exam/result'
      path: '/medical-exam/result'
      fullPath: '/medical-exam/result'
      preLoaderRoute: typeof MedicalExamResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/tests': {
      id: '/medical-exam/tests'
      path: '/medical-exam/tests'
      fullPath: '/medical-exam/tests'
      preLoaderRoute: typeof MedicalExamTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/tracking': {
      id: '/medical-exam/tracking'
      path: '/medical-exam/tracking'
      fullPath: '/medical-exam/tracking'
      preLoaderRoute: typeof MedicalExamTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/evaluation': {
      id: '/performance/evaluation'
      path: '/performance/evaluation'
      fullPath: '/performance/evaluation'
      preLoaderRoute: typeof PerformanceEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/appointment': {
      id: '/recruitment/appointment'
      path: '/recruitment/appointment'
      fullPath: '/recruitment/appointment'
      preLoaderRoute: typeof RecruitmentAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/decision': {
      id: '/recruitment/decision'
      path: '/recruitment/decision'
      fullPath: '/recruitment/decision'
      preLoaderRoute: typeof RecruitmentDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/evaluation': {
      id: '/recruitment/evaluation'
      path: '/recruitment/evaluation'
      fullPath: '/recruitment/evaluation'
      preLoaderRoute: typeof RecruitmentEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/medical': {
      id: '/recruitment/medical'
      path: '/recruitment/medical'
      fullPath: '/recruitment/medical'
      preLoaderRoute: typeof RecruitmentMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/offer': {
      id: '/recruitment/offer'
      path: '/recruitment/offer'
      fullPath: '/recruitment/offer'
      preLoaderRoute: typeof RecruitmentOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/registration': {
      id: '/recruitment/registration'
      path: '/recruitment/registration'
      fullPath: '/recruitment/registration'
      preLoaderRoute: typeof RecruitmentRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/reports': {
      id: '/recruitment/reports'
      path: '/recruitment/reports'
      fullPath: '/recruitment/reports'
      preLoaderRoute: typeof RecruitmentReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/requests': {
      id: '/recruitment/requests'
      path: '/recruitment/requests'
      fullPath: '/recruitment/requests'
      preLoaderRoute: typeof RecruitmentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/screening': {
      id: '/recruitment/screening'
      path: '/recruitment/screening'
      fullPath: '/recruitment/screening'
      preLoaderRoute: typeof RecruitmentScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/tracking': {
      id: '/recruitment/tracking'
      path: '/recruitment/tracking'
      fullPath: '/recruitment/tracking'
      preLoaderRoute: typeof RecruitmentTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/tracking': {
      id: '/requests/tracking'
      path: '/requests/tracking'
      fullPath: '/requests/tracking'
      preLoaderRoute: typeof RequestsTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/issue': {
      id: '/rewards/issue'
      path: '/rewards/issue'
      fullPath: '/rewards/issue'
      preLoaderRoute: typeof RewardsIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/confirm': {
      id: '/salary-placement/confirm'
      path: '/salary-placement/confirm'
      fullPath: '/salary-placement/confirm'
      preLoaderRoute: typeof SalaryPlacementConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/decision': {
      id: '/salary-placement/decision'
      path: '/salary-placement/decision'
      fullPath: '/salary-placement/decision'
      preLoaderRoute: typeof SalaryPlacementDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/match': {
      id: '/salary-placement/match'
      path: '/salary-placement/match'
      fullPath: '/salary-placement/match'
      preLoaderRoute: typeof SalaryPlacementMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/profile': {
      id: '/salary-placement/profile'
      path: '/salary-placement/profile'
      fullPath: '/salary-placement/profile'
      preLoaderRoute: typeof SalaryPlacementProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/pull': {
      id: '/salary-placement/pull'
      path: '/salary-placement/pull'
      fullPath: '/salary-placement/pull'
      preLoaderRoute: typeof SalaryPlacementPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-placement/select': {
      id: '/salary-placement/select'
      path: '/salary-placement/select'
      fullPath: '/salary-placement/select'
      preLoaderRoute: typeof SalaryPlacementSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  AttendanceCheckInRoute: AttendanceCheckInRoute,
  AttendancePermissionRoute: AttendancePermissionRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  EmployeesProfileRoute: EmployeesProfileRoute,
  LeavesNewRoute: LeavesNewRoute,
  MedicalExamCenterRoute: MedicalExamCenterRoute,
  MedicalExamCompanyRoute: MedicalExamCompanyRoute,
  MedicalExamEmployeeRoute: MedicalExamEmployeeRoute,
  MedicalExamHrRoute: MedicalExamHrRoute,
  MedicalExamRequestRoute: MedicalExamRequestRoute,
  MedicalExamResultRoute: MedicalExamResultRoute,
  MedicalExamTestsRoute: MedicalExamTestsRoute,
  MedicalExamTrackingRoute: MedicalExamTrackingRoute,
  PerformanceEvaluationRoute: PerformanceEvaluationRoute,
  RecruitmentAppointmentRoute: RecruitmentAppointmentRoute,
  RecruitmentDecisionRoute: RecruitmentDecisionRoute,
  RecruitmentEvaluationRoute: RecruitmentEvaluationRoute,
  RecruitmentMedicalRoute: RecruitmentMedicalRoute,
  RecruitmentOfferRoute: RecruitmentOfferRoute,
  RecruitmentRegistrationRoute: RecruitmentRegistrationRoute,
  RecruitmentReportsRoute: RecruitmentReportsRoute,
  RecruitmentRequestsRoute: RecruitmentRequestsRoute,
  RecruitmentScreeningRoute: RecruitmentScreeningRoute,
  RecruitmentTrackingRoute: RecruitmentTrackingRoute,
  RequestsTrackingRoute: RequestsTrackingRoute,
  RewardsIssueRoute: RewardsIssueRoute,
  SalaryPlacementConfirmRoute: SalaryPlacementConfirmRoute,
  SalaryPlacementDecisionRoute: SalaryPlacementDecisionRoute,
  SalaryPlacementMatchRoute: SalaryPlacementMatchRoute,
  SalaryPlacementProfileRoute: SalaryPlacementProfileRoute,
  SalaryPlacementPullRoute: SalaryPlacementPullRoute,
  SalaryPlacementSelectRoute: SalaryPlacementSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
