/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicalExamCenterRouteImport } from './routes/medical-exam.center'
import { Route as MedicalExamCompanyRouteImport } from './routes/medical-exam.company'
import { Route as MedicalExamEmployeeRouteImport } from './routes/medical-exam.employee'
import { Route as MedicalExamHrRouteImport } from './routes/medical-exam.hr'
import { Route as MedicalExamRequestRouteImport } from './routes/medical-exam.request'
import { Route as MedicalExamResultRouteImport } from './routes/medical-exam.result'
import { Route as MedicalExamTestsRouteImport } from './routes/medical-exam.tests'
import { Route as MedicalExamTrackingRouteImport } from './routes/medical-exam.tracking'
import { Route as RecruitmentAppointmentRouteImport } from './routes/recruitment.appointment'
import { Route as RecruitmentDecisionRouteImport } from './routes/recruitment.decision'
import { Route as RecruitmentEvaluationRouteImport } from './routes/recruitment.evaluation'
import { Route as RecruitmentMedicalRouteImport } from './routes/recruitment.medical'
import { Route as RecruitmentOfferRouteImport } from './routes/recruitment.offer'
import { Route as RecruitmentRegistrationRouteImport } from './routes/recruitment.registration'
import { Route as RecruitmentReportsRouteImport } from './routes/recruitment.reports'
import { Route as RecruitmentRequestsRouteImport } from './routes/recruitment.requests'
import { Route as RecruitmentScreeningRouteImport } from './routes/recruitment.screening'
import { Route as RecruitmentTrackingRouteImport } from './routes/recruitment.tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamCenterRoute = MedicalExamCenterRouteImport.update({
  id: '/medical-exam/center',
  path: '/medical-exam/center',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamCompanyRoute = MedicalExamCompanyRouteImport.update({
  id: '/medical-exam/company',
  path: '/medical-exam/company',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamEmployeeRoute = MedicalExamEmployeeRouteImport.update({
  id: '/medical-exam/employee',
  path: '/medical-exam/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamHrRoute = MedicalExamHrRouteImport.update({
  id: '/medical-exam/hr',
  path: '/medical-exam/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamRequestRoute = MedicalExamRequestRouteImport.update({
  id: '/medical-exam/request',
  path: '/medical-exam/request',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamResultRoute = MedicalExamResultRouteImport.update({
  id: '/medical-exam/result',
  path: '/medical-exam/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamTestsRoute = MedicalExamTestsRouteImport.update({
  id: '/medical-exam/tests',
  path: '/medical-exam/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExamTrackingRoute = MedicalExamTrackingRouteImport.update({
  id: '/medical-exam/tracking',
  path: '/medical-exam/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentAppointmentRoute = RecruitmentAppointmentRouteImport.update({
  id: '/recruitment/appointment',
  path: '/recruitment/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentDecisionRoute = RecruitmentDecisionRouteImport.update({
  id: '/recruitment/decision',
  path: '/recruitment/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentEvaluationRoute = RecruitmentEvaluationRouteImport.update({
  id: '/recruitment/evaluation',
  path: '/recruitment/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentMedicalRoute = RecruitmentMedicalRouteImport.update({
  id: '/recruitment/medical',
  path: '/recruitment/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentOfferRoute = RecruitmentOfferRouteImport.update({
  id: '/recruitment/offer',
  path: '/recruitment/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRegistrationRoute = RecruitmentRegistrationRouteImport.update({
  id: '/recruitment/registration',
  path: '/recruitment/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentReportsRoute = RecruitmentReportsRouteImport.update({
  id: '/recruitment/reports',
  path: '/recruitment/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRequestsRoute = RecruitmentRequestsRouteImport.update({
  id: '/recruitment/requests',
  path: '/recruitment/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentScreeningRoute = RecruitmentScreeningRouteImport.update({
  id: '/recruitment/screening',
  path: '/recruitment/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentTrackingRoute = RecruitmentTrackingRouteImport.update({
  id: '/recruitment/tracking',
  path: '/recruitment/tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/medical-exam/center': typeof MedicalExamCenterRoute
  '/medical-exam/company': typeof MedicalExamCompanyRoute
  '/medical-exam/employee': typeof MedicalExamEmployeeRoute
  '/medical-exam/hr': typeof MedicalExamHrRoute
  '/medical-exam/request': typeof MedicalExamRequestRoute
  '/medical-exam/result': typeof MedicalExamResultRoute
  '/medical-exam/tests': typeof MedicalExamTestsRoute
  '/medical-exam/tracking': typeof MedicalExamTrackingRoute
  '/recruitment/appointment': typeof RecruitmentAppointmentRoute
  '/recruitment/decision': typeof RecruitmentDecisionRoute
  '/recruitment/evaluation': typeof RecruitmentEvaluationRoute
  '/recruitment/medical': typeof RecruitmentMedicalRoute
  '/recruitment/offer': typeof RecruitmentOfferRoute
  '/recruitment/registration': typeof RecruitmentRegistrationRoute
  '/recruitment/reports': typeof RecruitmentReportsRoute
  '/recruitment/requests': typeof RecruitmentRequestsRoute
  '/recruitment/screening': typeof RecruitmentScreeningRoute
  '/recruitment/tracking': typeof RecruitmentTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
  id:
    | '__root__'
    | '/'
    | '/medical-exam/center'
    | '/medical-exam/company'
    | '/medical-exam/employee'
    | '/medical-exam/hr'
    | '/medical-exam/request'
    | '/medical-exam/result'
    | '/medical-exam/tests'
    | '/medical-exam/tracking'
    | '/recruitment/appointment'
    | '/recruitment/decision'
    | '/recruitment/evaluation'
    | '/recruitment/medical'
    | '/recruitment/offer'
    | '/recruitment/registration'
    | '/recruitment/reports'
    | '/recruitment/requests'
    | '/recruitment/screening'
    | '/recruitment/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MedicalExamCenterRoute: typeof MedicalExamCenterRoute
  MedicalExamCompanyRoute: typeof MedicalExamCompanyRoute
  MedicalExamEmployeeRoute: typeof MedicalExamEmployeeRoute
  MedicalExamHrRoute: typeof MedicalExamHrRoute
  MedicalExamRequestRoute: typeof MedicalExamRequestRoute
  MedicalExamResultRoute: typeof MedicalExamResultRoute
  MedicalExamTestsRoute: typeof MedicalExamTestsRoute
  MedicalExamTrackingRoute: typeof MedicalExamTrackingRoute
  RecruitmentAppointmentRoute: typeof RecruitmentAppointmentRoute
  RecruitmentDecisionRoute: typeof RecruitmentDecisionRoute
  RecruitmentEvaluationRoute: typeof RecruitmentEvaluationRoute
  RecruitmentMedicalRoute: typeof RecruitmentMedicalRoute
  RecruitmentOfferRoute: typeof RecruitmentOfferRoute
  RecruitmentRegistrationRoute: typeof RecruitmentRegistrationRoute
  RecruitmentReportsRoute: typeof RecruitmentReportsRoute
  RecruitmentRequestsRoute: typeof RecruitmentRequestsRoute
  RecruitmentScreeningRoute: typeof RecruitmentScreeningRoute
  RecruitmentTrackingRoute: typeof RecruitmentTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/center': {
      id: '/medical-exam/center'
      path: '/medical-exam/center'
      fullPath: '/medical-exam/center'
      preLoaderRoute: typeof MedicalExamCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/company': {
      id: '/medical-exam/company'
      path: '/medical-exam/company'
      fullPath: '/medical-exam/company'
      preLoaderRoute: typeof MedicalExamCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/employee': {
      id: '/medical-exam/employee'
      path: '/medical-exam/employee'
      fullPath: '/medical-exam/employee'
      preLoaderRoute: typeof MedicalExamEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/hr': {
      id: '/medical-exam/hr'
      path: '/medical-exam/hr'
      fullPath: '/medical-exam/hr'
      preLoaderRoute: typeof MedicalExamHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/request': {
      id: '/medical-exam/request'
      path: '/medical-exam/request'
      fullPath: '/medical-exam/request'
      preLoaderRoute: typeof MedicalExamRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/result': {
      id: '/medical-exam/result'
      path: '/medical-exam/result'
      fullPath: '/medical-exam/result'
      preLoaderRoute: typeof MedicalExamResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/tests': {
      id: '/medical-exam/tests'
      path: '/medical-exam/tests'
      fullPath: '/medical-exam/tests'
      preLoaderRoute: typeof MedicalExamTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exam/tracking': {
      id: '/medical-exam/tracking'
      path: '/medical-exam/tracking'
      fullPath: '/medical-exam/tracking'
      preLoaderRoute: typeof MedicalExamTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/appointment': {
      id: '/recruitment/appointment'
      path: '/recruitment/appointment'
      fullPath: '/recruitment/appointment'
      preLoaderRoute: typeof RecruitmentAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/decision': {
      id: '/recruitment/decision'
      path: '/recruitment/decision'
      fullPath: '/recruitment/decision'
      preLoaderRoute: typeof RecruitmentDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/evaluation': {
      id: '/recruitment/evaluation'
      path: '/recruitment/evaluation'
      fullPath: '/recruitment/evaluation'
      preLoaderRoute: typeof RecruitmentEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/medical': {
      id: '/recruitment/medical'
      path: '/recruitment/medical'
      fullPath: '/recruitment/medical'
      preLoaderRoute: typeof RecruitmentMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/offer': {
      id: '/recruitment/offer'
      path: '/recruitment/offer'
      fullPath: '/recruitment/offer'
      preLoaderRoute: typeof RecruitmentOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/registration': {
      id: '/recruitment/registration'
      path: '/recruitment/registration'
      fullPath: '/recruitment/registration'
      preLoaderRoute: typeof RecruitmentRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/reports': {
      id: '/recruitment/reports'
      path: '/recruitment/reports'
      fullPath: '/recruitment/reports'
      preLoaderRoute: typeof RecruitmentReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/requests': {
      id: '/recruitment/requests'
      path: '/recruitment/requests'
      fullPath: '/recruitment/requests'
      preLoaderRoute: typeof RecruitmentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/screening': {
      id: '/recruitment/screening'
      path: '/recruitment/screening'
      fullPath: '/recruitment/screening'
      preLoaderRoute: typeof RecruitmentScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/tracking': {
      id: '/recruitment/tracking'
      path: '/recruitment/tracking'
      fullPath: '/recruitment/tracking'
      preLoaderRoute: typeof RecruitmentTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MedicalExamCenterRoute: MedicalExamCenterRoute,
  MedicalExamCompanyRoute: MedicalExamCompanyRoute,
  MedicalExamEmployeeRoute: MedicalExamEmployeeRoute,
  MedicalExamHrRoute: MedicalExamHrRoute,
  MedicalExamRequestRoute: MedicalExamRequestRoute,
  MedicalExamResultRoute: MedicalExamResultRoute,
  MedicalExamTestsRoute: MedicalExamTestsRoute,
  MedicalExamTrackingRoute: MedicalExamTrackingRoute,
  RecruitmentAppointmentRoute: RecruitmentAppointmentRoute,
  RecruitmentDecisionRoute: RecruitmentDecisionRoute,
  RecruitmentEvaluationRoute: RecruitmentEvaluationRoute,
  RecruitmentMedicalRoute: RecruitmentMedicalRoute,
  RecruitmentOfferRoute: RecruitmentOfferRoute,
  RecruitmentRegistrationRoute: RecruitmentRegistrationRoute,
  RecruitmentReportsRoute: RecruitmentReportsRoute,
  RecruitmentRequestsRoute: RecruitmentRequestsRoute,
  RecruitmentScreeningRoute: RecruitmentScreeningRoute,
  RecruitmentTrackingRoute: RecruitmentTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
